---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgAfQohtCXis074lL3bdszW0SBf6cECF22ZG/Zs0FWB1X4Udq2brcf+BWKr8x9wjngChNF76xdw2Ct/eKthvwz11aCxoOvdWjh0LgCtyth811XLSorFxgW4Mgo2MfTMDLTzQVkQRZkh25/g/HDn1kPxkVg5Q7lYI5MLww/ig1SV36j2gOv9XDGpBRDGZNyYC0iC5X9rUZxzP6EIAj+cU1OAx8ykHnU6NsIPXCpbmVp0KO6BhrMOFCu7KEBNsGr4DH1F0dxEs+oalV94frDOhEeHhGXlSC7+AqcyLDrqb42d9nhEcAbStOqzddTePFUzOxDAPp41+rwdn/JCWswBMSuJoWOdT4Y8aG5oh54+mAZipJnaSNUPSc7jLZNGkcviF8WbaQYeMjVzUk7PKz1arxj3gd3br2maEY3OWSGyXlcUcRzZFB+WvoDLa9gGkoQTXoma/Q2bzz4bbBJ2skBAP5lYA8gbWFav7HIJKwlN2RZm9mK6890aV3f9eo+yZVbZ9pzbnSL31PXbHEWN8UmjQXZPEJh9akjmy6RGoQGRN5YcTtQqAE1BlDQbAJW8gRUklomdZWn0MSVe/qxj/n0ng2pS/+hQ8oh39JxdGhfLOYzeaE0dTgFMi2IxM8nZa4JKC0cNl+BVovgb2lZez+kjKNzFBGcZSrtlweA7LllGyZD2UuSVHFZWI9khwga8REcmenn9Cla8z46fzl2pVN4K3XcITSLiwEhaaxmiC6vpqyCZ6VtRbmtSA2oisWqutggQO6uHtEljcaJf6XZKPLYpHJpxvpeO2RK0u+3/nimjHXGhJTmw=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack-secret
      namespace: monitoring
    type: Opaque
