---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgAzzShvufqxKE4zixpBZoCzN/xokzq1OS9qFx2xaJR12GpGo7TR4ItFO3G+Gbjx0GFA+FkSr7C74H07m2cIrSt+WxMrsZZvF1W5AoJwaA3xsiIUjO0RyW3/esK34Z+7VEu7FcFT2UDxwH+/fdnS5i4axTfPWzAqThYm+6q2cExS1DbG2qfvBAt0KIWV++XvVw34PVGxfasAGKUxXrd3PKtbX04JyqnSLNBtumXmCy0BxjekBNO+O9swUFT5L9U9qoU5kkSnkEspDDZ6NHrzBS4392XhmgHozb/4CxzspLMz4H5ikupJJ3trSi1Moc6nfE2d+M9G8oCIZ4J8O1SJE/vxvfTC7Nor25vE4kbapiJtuvmmcBwIYulXY14YN1EwznMBMCbq7fNJSAkjzrFxa40BS+dlzpLi5N3d1UlOOQJgZvRXMWLerJsHsHApJRIgmbxjWlc+JpSdsQWbnEYPbLOEewB5eBsdPzfRkzRPyL+4gVuaMPq9grGQYAQHZgBEppjo/jymr+gge1b4RVIlIL4bqunmWYijBxE+bwzOfyCZfxbLvixugo48AFyc3vYlXJTVp0hgyKYrQAP0qC+NofXHa/OWXYyyEYjp2HsY/VYb3r+GcscQ1akQY042eIaTPNVUTdUYdRNqW7k58tQoBqhTeNkh84RGYuIqn4HX0twMg6KRpUMuRslddjvyJXDqWzckLrRnWlB0SRIomdExz5SacVrNjtG0ihphzuzBrXfyGF9GzZdDRqrCfMGh+gfdd+RpT6RoFkDdYEdBrE+Z5OzywtTweh4IH/4TCuiHLhoMjYc=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack-secret
      namespace: monitoring
    type: Opaque
