---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgAb7UZXJ30RFWlQ0p1h56tew9FJ2g6wyOi2rj2snHIDui4Jh5EEjTMNX8CrezNuFM6N9Qim+RbihZ5tIGh/c+NgbeIyqjT+pnyn8NR10OOeEsQgMU0Wonr3mKVZzjPGJ0Rs3t+Ae4NABdX/3wORcBo90e7Ue+Yc71zuSBn8zytttArGWE4VM1wh3IhI20rlc+OEEik67A2Za1Q9s6iOoETA6+Ccg6JpYdiXLLhnD6Iu/8aetYhj2DBL79keL6vM6Mae/Uz3sDx303T/dNTpTJ87nn9kgjsTilI4PpfVRWU7m2EIae5YHb0pdcENWpHePYaJQMN1KyciruU6hmr20fCYpJA5dbwD/uW/qgPwghFU9R2I+W/gvzhes6aIIkJVNthFtKnxseSaG8qYDaFk1uG9XP0FkDzgcnLid5KJQaTGsroZah0zu3ije2QPXHUIN5LTUNdCFofiA2VT/O+SgrXVzwRypUyKKA6MpsH5j94Th8uDp5fMFg+o2x8W/bE5Ddn1OACKuePyU+ffe7iaSshnYXaR0DZomzw6EvKiT6DkwEgZGRQ+Ca1lqrG8HLyi+UMVct8W/bf3Qt/gLjMgV5hC1jxQjFwzxcSf9wRhU8YVZb4pbAjYtTP4puumW1W9ROBNLDLEARvLH7xwz0QAmAKLZV1IqwPOnQSuBa0SKPaQ7I7nIjZixjPNh4nHST4Kbroi91XY7AiL7EYahFm6YGQNk4xWs0z6uI4E0hZJ90tCP/hSriJ3BCPHgCnZyvBJJD8LgGA6Na2hAnNx9pthfQN5UGggRRIn8o+9nbMvWWPCC08=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack-secret
      namespace: monitoring
    type: Opaque
