---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-token-secret
  namespace: monitoring
spec:
  encryptedData:
    GITHUB_TOKEN: AgCN4/B0miL9CIty1QmodhgLfP2+SXCyZpwK5q6/RRhOyqIjmibNZScL0VWrZxb2U06E6CcvSSNDVGmoMDhmiGiMe6aEYEOr9aPhjhuLg+CVgJJQhZQ9YC5MTyBinrOpgAKNXkRxG2XkC5/4u/9ZDsRt7GbmtqQjG4cKi6cQpDDfT8i93+T5k2CcXx9IpiqVTR2P5c1cCqCrINq6DJQmw+qn97djsZ8tvabgBUP3mpRtMYYATi3K9COr5Dzf4FiMwwaFxCWHgAsrYZtu1t8TcQybB2DWdmVu8x6D1cGEgsoTrgAZLyzlKmBFZxiEk6NJl5TwSy2Asr8cEjtFGXG8eIIUqvulsuxueu/8Arq9AJHiIWcR/Ou6+KlOfqW+rcYrMbPXdutSYXz45gP6nPACKuhLP3xGXuGZILpgqoWEVa4/YL/F+tjLkJCgdP4MjNT/mxUDGR7buUxjrYHUQ07ly37e7HleU0L3np7GkzzH5Fu1fBtT6t38u8gB6gVRyqOZe5GwRzH/legLNgGuDTu8QSJJuBUF1i+z4EdS5Uzwp1xWKuMI+8Jk648hTf0WCwaAs7EdpIl0K+RjPmIc4W0gs3++aswtEjYLHgsOx3R2We1v2CuPqO3DgFHz/FWJuKRoo1S+DfxWQh/AMBk22uWXeSb0H/LLDFrtuzOJHbzYWKiiPliL1uPW9K2vXNtaxtEoQDi4swOTqycoOuXYOfDnriYQ8G6ltNIhaXqJlpPuP7e9YC+rwUB6QVfkH4KQ29EyjQJ9IFTHXkb7eYrdyzas9+HOTVQEkBLEVkniuBaYR91eYDNTu1B33d+E2UlHtXs=
  template:
    metadata:
      creationTimestamp: null
      name: github-token-secret
      namespace: monitoring
    type: Opaque
