---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: groq-secret
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgBgdk7N+0Yim2KcjF+Vab1MOxVQ+piU7Qr0ReVx57jwwQLxQGJL222bVeprQqgKiCEK1UNVBck403EefYUsuVAMHJteEp2O1XPRPUizjy2/zgL78h4N001abqhUCzzKeX3kShyzZS4g5xay7nPkJjizQ5pwaXgO+XuUPnCJfmIziTyr5bDxF8azoeZxP5x0Sacm0I2gUFx8Ct/CP/nK2xqoqVkvG5ymnZ2fWoXmgNdt0bAKEKY1xsFzNC78O7KxgSJNds9m3xkgBn0glYtA9nFBRW9HW4XZFj+7HkdKAkYuHComDqYFTpgPfvwhP838h6oR+tFuUuDqiDiVB8grAD2x/soIkdlq+laz0m1RHELqCWaaUPpstiVsDcrOG1/rFyrtPuZXU8UpXStpuV9CaI1HDn6XBuz3tGj0dS+2peW3PAKebpTvACBQ8LBTQAxS2m+dJU06lHy/nt7Y35mKGdeNyZDroba8Izr7xGdvvPH7I2z8XQeyKJTwSU+B+azZrZwRTrOXJ/+6LUYW7I7RtlSEesn/mw9eCIjKavMvljyTGS3FKd2XhAs+TIsxDYr9mgz/mm2tVlHXweCrWZ7S62Ic7k72hgdC5FSODFx9QHJxF7ZROCDERhOv6d+324t0C8GNdW1jQIxeQUUsZlCbfOYMUlDOeVY0CR7HPzyOpoMoq5DUqFyRalWMyhHIQSpCWqOu88kB4L/1XPx/h+tCbzOIfTHfkFed2Ek11MG78StQwXJlJ70R3cPoSQVhUnSbjiYAs4EE9TSJNQ==
  template:
    metadata:
      creationTimestamp: null
      name: groq-secret
      namespace: monitoring
    type: Opaque
