---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: groq-secret
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgByKbnX1uT3nZg2CPJZ5RnpKBLez4ZoAk3Jpp7lpBDCESNRCJemMJj4ziWlOGcEwpJEtruzmFzAjYmdW4wIS8lt2OcknitODfF5PT7D6W/qEt80eoH7aTt3j1bklSzCGrILhYL+PZMdBNBQtEUUhUGDgxIxERADswjYc4DNLJqaeYsguIAZOez+4CdxXehrSqIi0ILzqGcv6XbmzYcx96HOc6fx3uXZ4BmBAhRD6J26t3uTCAUhWulIxytce0pzdVvbCdY7mDLCJv5Z1GkjeQ+/h66wM879HboKb93SYXUcT1OhZe0IGBvVBNlVsY1x8MPpQ6TdgdmdXklCTwj6TaeoZsnHB2ZuBh/hZ1Zq1hdVqyyIR0v7iTWwHjfMemfB/o6/MchI+p8tjLYc4QgnV57CsdGIOcQC03WSZy7kfkYCPy0kTBguXit7nbLK7gmqJPvLpPZ93EzV2UZ6Qv0661cq9txGH0KQvShK/zPd/njABN30k8nbNwIDHt1o6vSyhOqsCuwJWPAurpc04Y+jRoFQWEXaHSCbTtbHOUiCNtMgSb4OtRgVyrRharGTAVyVZ+3tLJGtiChO8wXWW+HBc9xmoKRm0nsVlSpXRIZldQQgR/YzDPOsE+dqMlgj2+6KmzTaGNeajXlrFguX1dtYJEoBCp4xqeHlmA7Voo/OWhRTX+L3P+ljVHLOvQ2aGOpERXM9geoY4QqItCX6FVhgVWBCjVaAEIp4eglta8BAyM0NowCjUJmLwX4lIV+XyiMI6HChr/tV2rKyqg==
  template:
    metadata:
      creationTimestamp: null
      name: groq-secret
      namespace: monitoring
    type: Opaque
