---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kubectl-executor-secret
  namespace: monitoring
spec:
  encryptedData:
    ALLOWED_NAMESPACES: AgBhzNjMdLxXoy5qAeWCpdmlpv3VIeRYKDuYLwis3yAssqQIJAUsOuIad2PyXMh2eytdiSFc6X1My+VFtyBxJAYVaxOiOHPa8dHrDONqhkAn/S3Nyd3jpXnqbeqCl965FTcd7yfJr9GXlqgpgXveuRAdTuWjPLk2Ov3MmeVwS5MtwdxlE24aUoWYFe6WcNEu9cQEZ2i2Xpf+fSCkwOYcK0Pvxduwk37gcgffbn6pcj2wiCxOkhsGUAiY5xwDwOXlkr48fUoVDbgDB6QTgPhpqARd1wwGRX+7ig9WSbl8e+4EM6FogDm2HPUJQpgVCSwyNpee61mP154fJW5rq8LBC5YfdX5oAKNK/Yshr48Da52fB8cZENnfHViblB56H96h0E+lLxV7tp50khVQiz3Qb2mzjqGKuuLFcYADiAFviy8o0y9xMwG9d/zOOwyX+RaFoemzIz6e7IZU63pWvGy4XBsx69ZfRkn7RXTxUYCDRP7qOcCuw2H4HxQAcXhKVRG9a44FmRo3eq4UBmwcPEzB6jBzSqg/+fboFhjbME8niLmquMUP7Q7vj+cF4aYcgqh/JX+KaOWDF2F2mNH/xqv9vfA5+O8OLyDGSayfiusd9hXRT1rCSfJboCCgOYLFnT+rjdsi/HcdHuoW3u1zz9AS60IltLpDS5B3yHl6jj/Nbwj6hSSjKEsTySFzeovrSmtpU5AGf3Dui2hjE2nHjiQHVins8shkSyEHMJCMLOiGPCE2dFNnAedK4zaAhbBxPs6tyCkFCbx55yU=
    EXECUTOR_API_KEY: AgBLtT425nKctr8aNa5yStq0nLz3UkqJQH0L2YCgeHEhJIxDFcRlqljU8Zu78jTF7eif3Rq/EoDafWDGdtbcYmYWlZbKUiADdbu5AVZvz2EFrjRjsjjIUJDKhKy5M/ke+Ml6uotTC4C0i0hqiuSDnLfEmQHA9Q0x62efdlp39iVjO5Evd3DSzBpM6e3sX/+4KAPgzSuPFdBnJvZx4GHjw3GMuUerQUwmmSRJpQDLRVE8CitIjhrV9F69RBOnim/cQsLEuMPn3KKm8ILOx0A4a/paK8NuTWR1lyOSFXTGzEB7g93lq8uG+WDJJ+JMu2mkl5tt5YJ0eMYM6o/7PedTkLwHiN/zBa4SsatF/K4wOleIJe2m8VVkZcraPK7luJqlWowD8RobwcoPydt1yuLXc2QTkPG/QobTyj/oRuKvF8m/Ejbvn+wjd/4q8mNp/CnC8Vuw8bYMlnoXgNgdN78V8iKs0wij/Fd0zmKwl1MLkTv2eA1LeOFXp5QzYr/REyYJCz0ZeePo+bmFdPNXWARsYFVOngeQ1ryzBcEclkuwJmeY2cNIV7EFs7dlsjgmKk3vulOzeD/adUwgE/UOUuaVR9soB0pxhcy3nO8VRywxvpaoS/cqs+7BLNpaoVYPyooEa2g8+GWO1XXUwIEsp59VfHhVKnf+KCkRrIZJdU9HBtBDQd8VJe5Oqq93NEgiB+vve7El2IXZtc/ubFHbWIDZJ/6OhRRFARHnQz3iGkCYaAfE8ZFORaT8EOHeknGWmgDdWvQ=
  template:
    metadata:
      creationTimestamp: null
      name: kubectl-executor-secret
      namespace: monitoring
    type: Opaque
