---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kubectl-executor-secret
  namespace: monitoring
spec:
  encryptedData:
    ALLOWED_NAMESPACES: AgAc8+7sLxDRV1JlNHyrpG8VLrBwVlnDaYoli9WTCVNvzA8BQrMPHGcljbtYZtkQ0o16SXHPwyEXR49ZzMN6PQ1gN4zdaiSw7xxmRZtMeQTX0PUxVGDLe8lfe8oOJnU/VKFQYmlex7LRel3WiQoG4qLbqowk1w9kH+GshaQVPb+cvldiaZJo9ccG0Q2d63RA47KqfKCizyvFVmAv2sXXDbbGKJmes97K9XkEC200v7sBRHQR7s1/4fxZn9IBzC83Q273zpKlz4bkYjiJv/bLbCsNCTL/u9V9k82iidkeIeuosybXIP3REd+ph0fSJwJyaKZBn99L8NTNCavdTbQ9UfoLC7Dfzn+8W4iPTSRwdeaFP3OPNzOpFVFm9lcxI8Feqx1c4PsCfXUF8mQZq5y3pBU8Fj8fnHghVc1/OYot3nvBykbeV2owE9ksLSm7X5Dpq0zhkZBF0D7zSYFFMc+M9GGxbQnei3wu5ReGQJGAEwMQ/RrKQJdRHI1yHNd4fRKYPe3CngI+WDg6EDSb5l6rO+ikm3hlmTIiJiJxpjcWpTUO9ZMQblS/r1bxDaBpit6mdYrkH+7VuqtX/YcSs9BsfgSpZ2SCdt/0Q6yXt6FmvZ7QGg8FkkNZArnL9UUUcIFrccTrTYnOp9LJ4fQJxNhsvCDfD+5/kP1+23DAFXeTs+FXFsx1Qr1NBxpDAcio7b6lwXu/573vCAYPU4McWXPUt8HjbgikbGKWmQ79yd11ACu5dX/9YCMHWZ4YYi6RUOjTJAWnRvFHs1I=
    EXECUTOR_API_KEY: AgBUSKHFdrmkrK9zgMfNy7WjKE5wCUoc9CpZ4+ET6AEan+9O1LrGVCHAQQwWh8cTumG8+KAf/SDv9f1Q/k7BlndyvYAKot01YbtFz5WP1iDGwPAMPL60AgfrX4ATlniKeSVuKGngCZJQFn5y3I1xaUdxJ2UWkZW4KUr44/DXGvj1ffKIBkX9iM4cn2Kgk988OIW+ATxPx4WctUSzDN8YX8qwS6mKVhVZqII8xZ4coJa3Y1ipTBEVX31NdMUEbEP3tPVOl1qJFKZFrZkTSKapqOmF89XTdrdQoW8RpWtNJZB538fxwtFWx4N/+ZvZeKfagYlAOebzfhzdyFMfal3OUc+nS6/iK4+d6TK1YQSthDLD55vw5d3llvZRyjZMJokrkPDs9Ejc/OrfI3n4zM3TrKJ5yh0VpACZvm9XImbyTxlqIYBiYegFsFMr4c1U8CYQhvkb6psdtOJzps6u8OstPQFB4bz58SjiV1UHE8HfmbUwR69PGhWCDV9ixTtZxorK2AxXQHyN74ZaBhGvrn3HDBvE62viRevM/JWSFpFJDUK1D7bntrn66GxjY8WqpWbD/a2gKnqB9dCC8/U/uhAhzZl2C7xiCaSKeWUfRRNEs7KSdlCeC9pes6IVvnwgD02VwMAsQXk8SXDPj1osNHEA3TlY8C7G4QHXLNU0KvVOCF76qqQRqO0WLcVI0jW4kLAhM/Fm54GHa9QxTOXUZSgOvimB+Z4tcvMKu4Ewkyb3WGvQa49+6ihgeR4SxGSSj4Kjbdk=
  template:
    metadata:
      creationTimestamp: null
      name: kubectl-executor-secret
      namespace: monitoring
    type: Opaque
