---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kubectl-executor-secret
  namespace: monitoring
spec:
  encryptedData:
    ALLOWED_NAMESPACES: AgB4IQDhaKS9fT7i51DX2Wg3jGcXZBm/91hoJgYA/zcVnMkbeUIZ9cRVp2S+9fq9grLTzCyIjFXbDdOYEUZLYvP8pYFy78bSpzGV7dNFaDOiDSiM6i8PkVjuUafVjA8XO0bCE6KAzv8Dg+vqwymIob1TD2XzPvcsSr8pLQXiwA2Majal21vLrMECoMbJoWi/GnEUbY8fPJZhc5YF3XDhCnGSllDnMu5tLXLLRKrNiR/TeZ55ZjAsf/fv/E8Nr1eXFni1+ycd1iVDzewgutz8x5N+Eqgv/U8nRIRSbxhc2EhjNBsiwfrKuyS5s1NsVddV4LEQPZAmA0xWWPPODJwxCQHTNptvLhoLtSHBaonFKIURhoPAm856IzGojmmSTXNGj0FjfdE8jRIyF9ZyTXDdwrplOg4S2dKR/F/JNNyWUEQZoP7UkF04W/RZYglfSTMfGhk7n2fYA7XW3/7dqvW9SAQBU9GnhBq1vKhVxWmDh8YgbMGPiUQay2qQi1h6laoIoTBbtIu+gE6xp2i3V/CAM5PeXquelyI4i+PsPlpEH83mFGnZKvC96/FjqZIk5WYxmiDQJgJHCPTGp5E0wyyMgZYczKn1Kj5Gcy070UA28N99bx3dyFnEv/WR8vGC+zOpvnBI5xl1Hy8XQep2rtGemnEAgM6gSagtedIBKOwHRpqI1bzHp228IcOl1pehD1o6LifNLlSMrANXr4/JF/+4T47wOpxBBS+dCVDbJXjXjCbm/ZjDGvmgCRf1QnNHfkVJBaZjwN3ccto=
    EXECUTOR_API_KEY: AgAckR37AXLNvaUfidzj5Q41Zw8aVldz1SMPBWlX+gWoRpIGGzPLore7rjTxC2/Bzxv0tHEGkPnU4MKBPygvjykaFhqK3Nha/UVzMDYazuE0Ry/pEKfHy2SoipZgy+mf3P8AJcAoZI5tMjs3eNdo3JaRl+2Hp3L/owTetAH+0Dkx1svGvXFKFIvvSZFzh0+v25WBc7xihIPD10UJK2YpUpW3axq44465yVa7dZVfi9XPi9LM49/AqcsKm4Q1nMedUf/7AP887/ewwzxHQzYJofSmwe4EPg26hMeFLjnfXbBmBmJQG2GpjLtGxTqqXpNpzw3aIdop+AyeuJeswCQl+3KxWobPcIYA1RBHVQU5JOtn7w78NKOAJCm/dNws4Ov2q/HbXzcNV5zKBxbKqwNqViI9iUKinSdgZ3gjvO3SwvBN0TywagUAMyQ54bivLpet412oh7FyKgw3Og4yQusTPtB+WYPvV2GEjhCpi9BwxEedXCj3sVvRo4ocqZbUMKvLjLHwABS11HI60NLH7UDsxN0ZOl/NMcQ+gAwqHfXrtNIQifbCm+0vourjsfPW2SfUXEBDVfPRV+ubzlNTju4oe8FRq0QzK8sexPXieMrvWo5HY62KJxab4gL8WgCFAlpliNZDjFXzHC/LvF/Ssqc3loJHoBetnlm1QCNR7KDC3QgDLreuK6y+hJnK3eGxs1XpsYyHiuHbjrfqXMqQPllc4fN1ijREfpw4C5pecI8ZWqC2kutre4cQXO00+S5dJeYno9g=
  template:
    metadata:
      creationTimestamp: null
      name: kubectl-executor-secret
      namespace: monitoring
    type: Opaque
