---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secret
  namespace: monitoring
spec:
  encryptedData:
    encryption-key: AgBc8e/INqSAVzNlXfTggsoZDF/3SPxUeoy8ImVVXhv/JyPcFGQz1qs+ubOG0j6Ebz02S/C19vzpzp7ur56dIiNPvijr3GnMxwyWkimPKkNlSxInK8b4TVZa28xI0UCvOhT+xN2ohGQdJZDF0BBUMHK/PzvVsj4o1VFY5QeePMZPG/0ZtQu2AGMeXIPM+JtxWRJmth5H35e7qRMOV9bhGaWsJa81BMKtVT3etscuvBH3VKsVarGZSzO2ob5TKW+obFOZscYqfpn1GrqBLBJfKnyQd9oDXiZgZg2Q1OcorP+yfeEpHZwDIuIO5DHRpT24J43ssSluS0C7pjhBHOir5tb8iro5TVCmnXsH8Azd02P3iPYuYn9qToWCUCK7YeNmGaalZ5M0vmbGIHHmvlCmtb8HCJVp5a6YtsmTmSrJpeq5KoJFTno+u8TSv7DepXiZbprOuZIacCV7PKWr9cKxVmhBoAuVqCJKUpSq72EL1iAbVk5slhWAbqOSVZhj0Wu6YTqFEH8/ubIfg4ZJPC2tDODsCzaQHzJDTTKRXVUybcVwASdbvrBCAl0nIe1cJ6e8+uK5j+N0++vNZkaNnPaSTy6TCL6nWHLba6vpjOBu+077VItXDcGnGxFpMSMfPA799vapWNFhLpRdOBExyZKdBEatZXUGxf/BIBntHruSmWV4LyqbCo8e5wCzdOPMhjlcNrLJR8PK7fets+o2Rg4+Lqv4vGm3clWcLNPcDR8xh9qnuqzzrPjnAgMwKm2er/HOeqCWT49harbILydcRtct+XpP
    password: AgBnSWRssiQxqvygPg6DmcIWbPI47uxSMZRoPLC0Iy2jczyiv+cIHobo2+SL2WZnfx2qBfV8l23dRENeVy0ueV3EgFgVSVwy312shvCGhoU9FX2hDjzvax8pfdK/TbvghtLJh0vRmZx8f8mVMn0/cwXbhhWGw5DIy5QiMtTwMe6piXkNfOgIF5H7CacUjjsRHJ2YlqD2rNnauRM1djyJ4kazBqUxw1JvCdFJ/eaMLoEm2Z8tRRRDwa4RLxWWd2+GqE63K91FUMAtep8KgzJ4wHIftZSCqHpo0N5QsD+3/ot6qwfpQp5KK2sfC+4Tjrtps75H61EJcwKnqUjLgyluKbFZi5+bCgG2Cv87lA1cAT5U8ShfXfc78EuyOnkVWCumD+Ax/w/8VazcmRYD53jujxmLk10abQ7OvRDWdqQnVBoPXjstOXw0+alLwGdHU2Te18DO0hjFIavlA9KSptmZFvpnIayPur+jH5Po5thC1vR6+L1lC2CGX07hyvdjLPBIDHnUUTukDj5gSHflLwQoi/MMEEsSyjgoVpxmXRUAnh0BXbjjyOGkUTQDS07+/yhDVj9ejcN4SOARkTYoUN9ohhBcKWgdYhpGoRgT5i7PVRxu1zmY5geFvOz5wt5aTr6Dj2Hlw0I5uwNKoNfJrZ+qtPRqEKM35eWls4OtrsuUAYEu0CrayhMzLEVEj+Ye2U+Z+20avEVPRA==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secret
      namespace: monitoring
    type: Opaque
