---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: n8n-secret
  namespace: monitoring
spec:
  encryptedData:
    encryption-key: AgCMQX3ydpVZYNMytON9WLGbPlyWNlOt2KKLO5elGzlFUpUqdZbEjAaS4ODbkuPK8ziKbkPM/FiP6YYxvgHItOZ0CNgxmDej0kJaXY82H2TQl6ea3/xBWQQQ/paaDz7akFsf2bbLt5plVkDlgXp3z4Tx/o8nXRnH+nUh4zM2UaqlF42U9NnFh29juaImJaChXRNrT58IQnSJXXtYYZclaYIN/lxL0C3DTGptYbOYBvZtB8iBpCq82yd19VI+/tjtuGHABf908dCt4i9F0pKeTDcxk7bS2+NFoFOSfPQ7kYdG5W687vuYZYQhh+Py6jJIuDPIK2tGcj+rX6uOR/ntPX3SOet3CeMa/USk+Rd6HLxfA4DvkCRUAu/2Rl+nE1/3grWP7VCpX/TfI7BqJevuCBFIy/XY6MvYh7LHPgUN1NMfSKk7P/Iw+TAXOAQ4zxKP8K3gTX4m33c/ogJQPyBZP+PvHfF9iy8xorJwvpvbKvTsfzTx1TKga8IJ5EyeAxmEBDdZyvjip70O4lU7ERkPD2O/+oWYMA65S6kS7X01Zsp9dx5Ymt92EigAGdakxMVc49wDL8Hx96xDZYygt2EnLvi3TBFhlbKG+2XA2A395fX3TSwFfKLgNh+YajInNw8z1y5QuZBwiJeMs01umxsFLBH5jRISP7c7hcK9fWfiY0KjcVXwZ/kfeji7BR84ImzrHWAeTq0EJbtZJCLEHbeHmSPp5uWj8R89U8v9WOzfCcP3MD/M+e+2fgOR/LIGCgACF31m03g6T7Q17k76KRSxUjC0
    password: AgBlv2iRV9wucRUuGDwPbqez+0vJ+FPWT6SiC5QxGHFVqcEUmLNMH2kNM7cI3DtpWi2h7LxPw6/gVpZcqXACPxQRNBItvp144EPlcx0A0ch6B4aNDww8OvbdDoMdpnLnL6GeaQVQu37uXsDdAsRiryP111/fxVta5rl/m513CDm4XWEc7ri5SMN+hB1U6HThsY8PLArU4AxP7A7AtfhvkqjvvHbQ2i7+NOCHr1vdnfOBfhVURDgspTnKyS/GRF8SrMP9EimvDljSPVfHjxg2R+zJ4sIjxmBSwyMmwzPeYiFTBgmlJvT6jVooxI73Qy/xEm6u2UXyqVsSEipsUEzqzq9CWgMm1dbUzpunUuHCRg4tGFYZRAvyxhd8z3VhajMd5+Y6yp3w4iZSLvbD++UDEpX77NbT7Mloa4N2P+AiRREBHbpmZYHTaQhlOF6CQ6f4r3GHxMCJZ81KduTa8e2N4l74BrYcumYDhv+qZMJDM3nu+TiCzaC4MT0tEwUiRgElzalgA8hmMyPrc4/jHXeqraVzUYZ6dvSESFjaD2w0wdYw3IHp8Ee+EVAI9g3Xbmki/QSQWxoNPuNoOAFsTbHnZ5DW2suq26AAPNGryv+9v0IVDuM/smPpXgWOAVkHe5btd8S/nq5QzrYaaBObylbPUt6pclqSP1yNE/fx0pWUguOsnIagJUhzOga3oHpMqkKhJT+wr7pTtw==
  template:
    metadata:
      creationTimestamp: null
      name: n8n-secret
      namespace: monitoring
    type: Opaque
