---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openrouter-secret
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgCnc7Fvjk8pDDIdGoozP7pikqbl+JIKEW4Fr5ItiyuAw9oBDd08EYw1f4Oxx5OJUUmRc20LK349Gbde3/bzGi693DhDp0n2tFhskBICJDiMcrqyLi2Zi3c2Ystc2oqJXoQiR/EjA7AKKdnRW4ej7a8QA+yfWEHwmBqUSFWPVNHaDO0o6Io2zI7iUizt50D207U7c6Ng7JKvkiizM5CuohTdETtxf8rkEd2sP/c3WH3RiT+ntiOhYLtVpn50SzU9i6cISIMk2bT3cEYAhn0Tzj5COpK4CspG2MzPCOKnZPDSp2ph6hfwLOcwO6FH0qKAbQms9LTlEF32Qnhon0HwW8SxR49DQnlJ5qDyIbmNpzcb0SUvlKR4gM3E3s8WUrWeC0iNmmYYcDAXcB71TsZl6uUUwQGpe55VbJNo/Vw3M885/qDRd98l7uhJ3PHz6Ye2BtWEKHNE7S4S7SzN0L0GuMu/KjXY0bg6z37FWqY5nG+cSnvc0t9Q9GOisCH5RSS2lUbVotcANZkm4rUoZlVqvu17fJHwa4N640zromNctrMqtaqyDNv6R6Y0radUqLDoilvrtX2hjBTfa+vXDNyJcm+VP7HsjbK5PG2Rmn5q9+Yw6hLxY0AE/7n3HLMjT3vY5GjR89rYmjbF7BCjkEaQtVdWMfIJaAgLdsAst2cG6E/NzbnsPVNEspZGuVYfT2ab9M7TDYEI/bZZzG/KabY2K82Nw7YD9eLzKi8XizD3wboiJLMHDyaXIWMPWw2NWFY8zdevz9bDtoc0gHZJHbAgRN9Z/9ek9uV2RAbO
  template:
    metadata:
      creationTimestamp: null
      name: openrouter-secret
      namespace: monitoring
    type: Opaque
