---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openrouter-secret
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgBP6SpoYS5XgLLC1F8GPVQxNRYOQXuEEbueG6A4RAytCLRL7trBjxJEtKE6Am5dmXTyOQ2OxQyGJRin5xohfBY2cqKX9dwL44JQuyW+TnOfFWYGHfJSFVseQQszplyarmtSZHpxtmu2p8iquvHRl7SKiHxCcFOJfj0W/6+rZoXCVIYRo2z22aHVfBUmK7WdfR2qHVS0m57lRLLj937UhKoSuIws705xNkCJgzPN0oGX4T1tXGyB9rYAdZTSKTg8YjntXTKyD7bo0aQgwtu+kcOuG0pKi0YqgKs1qsbOLN3yGbrAePWyH0K/k9nlQBDC8tD/TJyfBucanTnjWF892ctR/AbaF3t5QSCyevVcs5sBaydskmPy9iUrWzJ0RNiqo7/xx0y45LSupcFr/fjMX2YjtBJW2dEImf/6cdmQLK7jaYc4VoSLExbc2X5Rlhfft/tSY2pC2rgVXz+wjGnJ5H1C4AmaOxQduJJuCcLe9kbJytbo9Ww2apBmSijRih+GLaH/wZALqElckiZsW1w9/KXzOkHrScBLpRWTS7VLw/9kWlnkPVhHKisfdlOscTJsy5Ae4TSWeciCDiT0VBrdL+OcIxnH08BehcpB11M8qEJlg3hKKvf9xk4MBgk1LEmBapEs0bVwRCxVjDNYb1gBiBcuOQCV3HMD3rRkbPzCm0wySnvuLStyY0JuzovT6F/5h4mZmWLyjo//aGpaKasA52MQFaS4jOlYR3WnlHJ6cDnWzYPGsGNXkYpYa3dcyTXBfkXFHzkow0Eokqf3yTiuQAn4MHW8zNnXOY/l
  template:
    metadata:
      creationTimestamp: null
      name: openrouter-secret
      namespace: monitoring
    type: Opaque
