---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: openrouter-secret
  namespace: monitoring
spec:
  encryptedData:
    api-key: AgBBznK6aIgjKIATnW5CiNpThPNGF0Q01fGUat57npOebMYZeCL/5UDgaCbEZ530GFJlY2XCNJfLEr74yU7iiZFHxteQ3aiXT6WgbT1QcsMwTVCC8KHrGjjVZRs1Kc3b8ZhrirsPhFDON5D3+0py9HFPHgBFKjzZ3ETrmqbLyXcadmU0hfGl211ZmNQB/vsvDviElpQ7WgeLvad/xHOd2cr+aIohBtOwy9puyGQPnHKJZTj9kjsIcSiERPkdce7DgZ7Lzf0u8KMK4K+KYs24/a7UKY9RxJpaRwlkiQiNo6q2zPXECvx1UX0jJR5neqCO/nfnVgyGjhOZV4VXCpfKlmQUPbC0krxU8T4FiUyl8f6cj6vANFgpxlK5nCFoCaS9bkksAC5hVxPFyQMzwjjMV1JvjX4Vtev61PM+Y/5/pLrmQHJmhh1u7OmPdeny0TimcDCyGYZKnFT03OCuKUyDc3xgRQ9JbsAHvceDQVKNzzx1Gl917skvQ5jdLEfurzcsNk/ujAY0LF5x8zgQV6GL8Yds3DWsCBALqnLXfhYE9PERXQSQkLMnUUrjI6azJaaWMTg+DFhhYgCUI97w7IBjhmVPQ4JYet6ICATRUhOt0iNrSTtvH+DLS32T/fRX+51pXzk4+C2MTyMYFtHKnb5AiFEw5ONj3vI9gc3yyuPIs3Q5BhzeFFFYZJh9aLeW3WjVqjb8k84Q1wYNywPA+tPm4jdVy0pPOEjsXyAb12lKb7ukc3CwuOPe4lCkAtnKYL14T6YcfK518giCTYhQMy1oIzSQABANN1Eqma8k
  template:
    metadata:
      creationTimestamp: null
      name: openrouter-secret
      namespace: monitoring
    type: Opaque
