---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: platform
spec:
  encryptedData:
    password: AgBzaI5uwueklpMQZGCg+m7VrVzA1gAbNQv/dG9UU1O8xMoziCofCRlPX4xJ4Ohj+H2PalKtMgYW2uVLkN7U502LvKeU79tvipSJsJw1QHbmOIg0Z+mJ0bA1Bq3FR1u3P9MlCGUx1FbmGoE+B+TaEXoufA22VOA5dkhq31sshfTvH5n3+ktR3XCRjh0MPyANJsD3JO8GnXcE7O9SSTSlhqOVXveOpzdmekiB2HJwu/vDYAvUIuyVLgAF1xFW2prxD7jsSz7FMHvsYccESZ9PFCjwKD8QZy19Mau3/YQztoWmIk91fbC/+05umPapTsgVRjT8s1px2UbCzQzumBvt5u/maYXIWOzzAyzx+W2/iDBicmULFrGhmF9VgCYzaboqTZ1lf8pWOw0HZ5vOMSQr1sD+TC6yli9K5/3sN3pkkAJ4mnqRtXdtgEEIyKdD+PFueQje5RXLbPVcxkhFNJ4PAntJvGnbrNXJ7KdKDv9N9fxon7RpWECO9u+AXxc0mXNr55PnOBeOLQyWEhHOaKTDgppSVqGrMh8+BxwQUAYgybIH4b0miTODtjXnlIsI0wrFIiTyNg4qM8RexlnBd0gGyeESREq9npxcuepeDRKtWAiFZZex23Nc7j4ICvskP+5vk4WbRgyYEQFxsAzhiUGqqCNa8iO7dONxuHTIpJJHZi3utFCoGDwZ7PUc+UAhy24eT4mtHYAv1ykPo6wB9tjTuOPqLYP91VV2QA==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: platform
    type: Opaque
