apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: platform
spec:
  encryptedData:
    password: AgDJAa+OE8EYeSUCki3mcPeMCfk6LaKVI+nKtbsbIyWO0aIL5nHe9OPD60uKiklP8RmlRVeDv8UFAnQaUyWytpb8ghqc1k3ifKmbMWokwzRjAARhK6Yta2J3R+3OUk5yeQ0ZGww5hRFcxGesBwlZJfAhFi4uJEyZmxwX8DMJEWRnQcPX9dpOscmmkRNRYoUliUZc0qVDF65dFCBSvgxzHF+ptBOe2piEANECxuYWQg+7KHm1NW+PtmA+2dfwMZ2M395Gr+osofRGnGEcROgdDFDp9CyUzjfypBEb+GCBz8xoOtvd8JJznpd254Rrw3j9lcfXAw8KLstFUYXH/UkR1qgcDeT0MLEM3XBgSraG3OjcOa1YHFZZ9lzUPAoJAG0APU9Lki9snNz73JAm6nG7DMQ/cPRuB5I/4GvKsBSYUDCBZkMx37ZZ+BZIP2R9sDbgjKqhB6lNl2cbK4ooC+X/6cgcQzw3/ovG0eSHTHOSQiTtPXOgOVXLcKe4G+SKuYvjQYVB8TiVwswd0JMi2wQckeZQOYCwSbTx3TdZzO7H/WGo88ci8xcNom0bXK7uV2tggcOG+CsLBbMKh5c7afL9TKkkPDckotolcqHmUWAzf0w4+xBYuCUbTwOBizkVXvPB0QvP2TQbuEKj4pmifYkT7LM4XDTk1ACe9FDuhESBVna5GSK0OMf9igVvBor8nIn7/J/2xVONdTePgMAk+6swCCbDqaEzs3l98g==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: platform
    type: Opaque

