---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: platform
spec:
  encryptedData:
    password: AgArnL02yX05tqRg4Sm12F6eg2HaKLD6GIBBcwdybO2GnLpByXKGwA8gRhBHxvWsj0k3H6974fYynIFwWd6yKIELq+Fj+VPthE8ordj+7GZ9O2sk/+YO7pvmVKYLKvDm6+cAFAOwvaFBPnwiX//RV0+eK+4WaIuR4NO5iTu5OSAFizXggHInnKFme6sVrkYJltUT2kU8FmyiUta/AYvMNXKe6tKb0z5jFC0t4D3LogObhvBAcXNjRZaMaMP902A1MqodAnh+f42kcW85ewxW6gAIdDJjVbCOkrjzqcuIh6TBUIQ40u+57DqbEfU+2XvIU2Zh4ayZMP0CPv44p3jhm20OCJzqX29Tb80h1gThpsHHsSA8i9GMks8WyiHmzzw+FYDiJW4jmwHech7fmQ71LjErxvSQEV9wKYxosmdVHqyJ7hPRBLRSjUyWf0yzpal9HaVTS2XiA0JP1Qd2/338lTti6N65bwoF2OGs8e8GfvKCk60KGD6LDmVDzqFwGA6fOtVRgE3RAfhDEVSSCcviOCwi/vS0ScjX/L+SVK4EAWaB48zHHRtLbgJi26vqe7OqtHPghd2Wda16RrM5tL7eP2mnArPkcDwV1fKRRyt/IN85tBODKBoiWOiT+K7+afh+9r/R4yLqf4RcVFQJdo0M74gf+Wr9fCINYU4vpmPRPc7fN/rFbt9lRlWfW2uwNzib7kTNBirCHYLG7HzqRg3epKLg+3vyqXYl9w==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: platform
    type: Opaque
