---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: platform
spec:
  encryptedData:
    password: AgDKt71NwmR9/mR+aAA6ScZH+MUax6P/CoufAEMghGxozFW6wmYuz6Mzc+xtCMfMAeLKshIGyVumneT2bofJcP4C2uD+HsWDBxipw+q+yUQbVoUagyE0RZk1DwboOgguCcqFnVFghFnQl0B8eoDUolMnZbRMZtKMyBW7qasowILuUbdQpcLGGTL3La0Tp0awWp4NweL4DWv3i+FiSUikJY6+WZm/HypDn2UkLM9rk/uGeDMz/W3oJFCLcqx9nYQlwYbPtpegvqnqJLYWt+OfPKml6SazTpG+gUFWyphRVqjCizcRGCQzt7ETb6ydHYvgnuh5+XZwZE5kbHEDGGRdSXEQlideTROItNct/UUD0P4HI732Z5ffO+Sn++IbCqu5V5mz8mxYYGZGGR49vBgkH8jPm2r+wgKvonAeGtFzQgZlq6yP7LggVTTXFtB3IBE2lpvW/2TGO8VuUGiALs4+TvmTLqbYeUgzSCZvOI5rrKUUcC129GKHyE+xshiQtn3bqNAeQHsp2VRayf5scYCF9rUdTJF7gDhHv7p327IJCZMHiml6uyJwrbiaw4p6+1puiuqDF9lyvlNOEqXIjAqYdZQRp8v9q0pctdNaDhfV/vWes/xxdstkiPlMJzmgQvCRmmZHl/hXw4D8rvkxYVv7MKC2L6bMPjiyDkmlJzqQeDWnRKF7Ml5pfvZIYRd0TxRsyI1nXrDRnOQXhPPl3ZIF9Mw=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: platform
    type: Opaque
