---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: platform
spec:
  encryptedData:
    password: AgAG1ZQ9o2QDph8dIq1+e1+aZGlRPcHKSPD3GTSZXwXX1lL/Moz2sRTO4V9kOzOCDf9RpsSPwrwuGcBT7kzX/K2JR+hK7v+fnEA5o4S/UY94E4StX94imyrpI578+DVBJVyupmpjzPdOzXWHQkEXRPn0tHYpICcxwS0z2M5H8WuoSYfXnsBAFic6YCae1pJcUabggzhXF6Wsdy+Zgh3xuA32S9yxGqy2xAtqWmYElTI//BPjvfbYEjYzNbP9WKu6QvUcxx1q415wjy2lCWmR7qlAO7NDTgo4Y3h5nISWvaWg+d2XwFOvSWhCTjdhp/2IbLqh6Ysbw2yk3VYpRhIiokvCAt7AhqL7sCE4qUsjbrdHelGa/jE/vsNoxZ2tLoCIx/T5a7r0EhAjTeNKW0HN76G/MDzBfubxCBPCXcHj9APvDndfx3RT1ybW0/twrP2iPlMOMOgKm37/p1Q1tyIKY4SIDMmaZ+/VUbSzBigblfGViXKzLmfUNY/FdsgRg4wHxQ624w1xFrR+eLwOxTk1KJSwcolzVg23AXsCooSeMS+1hE31/PmJoTCSvpP3CSQlXjEvK3Sl5UT+9plXqAHvtomPVobPYbY1B04h2NkrBCAraGP6vcBCl4MNohHmSF8ruVz8PRbUZaEALV7vv11wm76UJnxLHqzQaVesYyR9cPrFrEo/q/mk52lZWCQ7/z1MiTvH3S6VuZh3xGq7vvALCMA=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: platform
    type: Opaque
