apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: platform
spec:
  encryptedData:
    password: AgBizT9dmg1ydohXYNwyb4To24Knka4e5GMvBF9sPlalDH0aVroBzxryObzVsmNUzIgMt6lxBL/k8/N3BRfB5KqLVhrhv6iowmEhe6+N0jet/ndpf9hOdw3siYg7+501sgO4EY3J8clHOm8w52iOXU6jJYbwKVTZS6JrUQRTbyIuenXWwtDxY+JcK4s0zS+eiS/Izfku+l6RNWvJRLWrEhEwWvQA1cnqRYgBlEAVMTgDDZzpK2RIn6r+rbHvv/cLiTqOVM7ov0+VmxsSxow2soAVD0olP3HroHrYy8lz/wAlFYm+Wnrd4yna3aqqDc+Jzw2lIrukY9+S9345x27m3JugRDq9zX3DCLRmiuJyetYGBr9/Yv0scl4hXPZeZGyNJkveDt7flfnBW443qmhmpShtPYI2nOIhpA4fWlLihODfwhxeeq4jvQfGBCac0hxfqP+H8dZbcE62f1h1FFCUorXLFMSx8F/vlPwBhHGawj0eAByWo4NBtHGCokQZWOkvJK3pJAfonodM7g6Z2LUyNhyMDeeh8ehkPHv+Ec1cYKrzY5Tb/CmoUSxwSiLXgUGgrRIktwfY5RL6g2OmX+t1VK6lDIXYeOcpumrPng+k36ui3xixN8YH/eSpfIUmFI4fibtnPT0NNwdLetvlT9LqTTka6pP3N6xDng5tyumlU+AvTEgN4iAAlo4wJ0QAH8jIq2dBj1OF5rgRvzGQ8XsRG6M=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: platform
    type: Opaque

