---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: platform
spec:
  encryptedData:
    password: AgAYft16Z9QnKbn1YLGHU3Im1OoZ5e9YQIM/OqB0Mf8t9Ax3xxH9QLXx2kBF2Bt7Dkr23pJf2Tj0vjD3GVg1ElEI6IwldSVkVmiN1XU3ipD7+jWrCZ2jXYd1zis81hWvlT2NO6zQW9u+WtxNRfXYRnCyYIDv1rWNDGDgBeiVbXkm0qJgWQs2yaPALtF2aNTSwwVLaQUtS2bDFltDCyKRwij0jB4yWteBXGDEWftfD2ATSJlHB3eyoJKPpumfx8RxYuOoebGrYbwby3i1cyoBo7hddQ1CLgIb65g0AEElC3wcE93mTQG6AWNiXRb0hXlx2SidcH9mfJJFu+aI49D9AtbfEY57hBnlicT/pObgsI3QuaH2LDWqxcpJ3ejOQ8z+xoarWrzRydFfEGWIudCJo1GskW7UW5RR0AasJH+Phk0f5EweLPt+Lby21oX1/tsd2wUnG40vdSmcN59o0eTLqgrAEdvp9FlNZFpc5B/q40rLKBEbICReRjx095JNvtPT03UP0MVS3oZK7x2iZ0EUNh+mbq6dqoth3iuYYhv/gvjIcd8sv4WOHL14dDEfBNd+R6LU6T4VGUmSCOzH4Kd3eLIOlmpMkadeGppvbbWMviNQefvqoi6K/D78URzHHDLT58MrVdirGJatVoxSVrT0WDvSEUlo5v+jkvKAvhhxGVYo7FqQjv0ow3o1D/u1aBAu3zcfZB0fqxdklp2ZYOAgKQ0=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: platform
    type: Opaque
