---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: platform
spec:
  encryptedData:
    password: AgB0O8rl2SbibERIj9UIL3jhc8z5UZSy7x8FEPg6QqEKejgZDZXAXC1fBob8naDM1smDpZ4R70tVI8Jti+y93H+zKkaB8q71Jf0AzBSJDwGEytCo3GlPSGS0XmJpaLB3eCIa03A8m63fMBzfKazGlKCNrXzezQsqU74IYXCezVRSuZyIMygBXTKNSTBcywY2G2YQsmNfvpSg8upSvszhkxAi1/8QkRvLNGWu174qQfd3ziN3Aga8C4ovhGNGA44uywCTk4+7ZF3wjwAClr2Z9PEXj0VHCatC5eVmxG96n6gi4xELeN1O8tRlWl8NQTHPjcAGJNJ868i++XOaxX60OIBoylkFfo9qpo+2XQG4OTncQwe/qV00pjEuJqrueYcWGSBVsMG0OtpXrBUOZihWihrGvyGk8JCh5dIp8gdhOXmpF2SZfulDtaI9hqCwYk4bUKNdOyTP116ryqlFhbvLbY7k5SOAhiUw3IRy0qUOTq5cHi8jc3IEqCoyVTqkbSd8DnaKoCOPvYIGDrleut/tzctjKJltVuaakViO75KE4lT+rbgmDq3QjnkgDybYMxB4dB+PxVSpPozla1E226I2AoqMxAmtIakxGaA56NPEUGpAnPzf3R0jn77jB2VoeJh8FKnD1VoN91ecVeU24Fl4hmJ1V8VTgq/Bcd9wuhfA+qgj6varDubKL8/Ik82BcELGGfDvohONUa42Uuq+gEWTExA=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: platform
    type: Opaque
