apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: platform
spec:
  encryptedData:
    password: AgB0Fk6eo+Y3qqaiH9m86Uh5wnT+6A+Xi3YS0ugE98AFUyT6Dp0PMXhKm3su0mnSqSmynPmS+3qSi0Qi44PviZqI0KFOujp5t4D1wx7pJZNKFrb1SdIu8H7V1r7Xr7DdYNOA5rXuUJF/sAVpCstHVtUS/amL6wsKU+zjfz2FNb+VJfrbXFNv9z0K29To2jDr7mEjkYnSyB9hqj3Eby0FuGzTjptT0v4swKkEWKMGb7AVxqxD1WHBwvAb+Ui5EJ4oPxeyeIn7J3k5HqrX6HsUxa3uyC1vObL254yzOgDh88ZkKu58Lbj8OsOHlQ5YipL0h/EQsQuFb4d8zHXaeBDtcT6/t8Gzo7Zj/IAdKUIOLTvBK5Q2TvEbpAY4HqlgGRZRTiGNt6IdgWkvKvvDFplLhtjU904afNE0FS7DaQMW/7SpyB8/m10lmsLY4dyVOZ6V3qSvQ3Rmi5pcCL/FDbRNqoX2F45Tbzm3hMyfBwOmrDJqn11QVtOgoH8YwUJdiPYs3h1po7xgWt0Sj8y5lZiAYzTMQQE04p/M+qBzJx7Xe5Hxtcm7BEY4Xap9MoCCr1FBLMGamqhLShUcfIqmghd717Z3dreYLldDh12RSUHSSshtQQhn4kjCPp/5cSPf7xejVcBfuM4+CnB68h551i2BuXoLC0FFLb+lZuZ2Wr5V4jlGtGTXJ77c12g16g9Ua49jBCAA+xmvDRvDnR5Ej+c9XH0=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: platform
    type: Opaque

