---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgALANZGvwl9RCbLYckcZFHatBuAOknNZOS/nvMoDtUj5omzXXA28wivK/M+le3OXtZS/7vhlYA6rJmwt4AwsS8uFDlpYlKsDpqyRwmaxE/17Mmr6IOTHz1S6sXqdt6JxSgFG50KQ8muDPQENajjMvQAOcTwb+PalmJ59uAQViiCbOS0kPt8LetnGJljHxKIznrFcJ7S1s4tf/iHrY0XkOz46wMA1zfzvqUlSwfcZOMXnQq4xNq7qFyurxRSN4Y+iFU8XQqzOxzRzZZVZS4D5Stx92zHpguuKkq0jTb5QduxAbLmvfC6sTpgWSXrdlkLMqgGtOAO78qBSbS8hR27Cp1fffxlJGfAptkh0vJoZqf4fKDpuLxtFo9J78KAdnijZ/sq465zNWvbbjytm08HPQZe4fH2IU+PGya4QuVnKL89sVaZjmHWQq2X0SE+o3cYv3viZHiqJl//mwPeETwuWEqHlXk/2siQ/dJQ5+hyQWze1hpug8CZWoTbIDqO+gj4q6NJGPZgoK9lDncryIbN+zNHHLBw7m7Pf+IRz+wiqJXEUxLGOtPv+55Pv+MfUu2B4tnojBYf7WMEYnPx9f+ZVUs+8qYMyEBZcJWwWkGiAdbok62sgvQg7ft7Ca4A0BGt6VRjx1eyCdikNRC5nM5ZF0SWyFKMUXULreMO/h0sHc8pAboxkq9BXBdGK4rc6RwjlgS3lFZCG0Gd+iihm41Z4M7JiEf6V/Jm8IfxZbBjjFT6Kkkb8hKNNL+xKbRxt23q5Qlj3S9dYEz9ZYmwH3zaCEtMw9ygPPk0dj5AXJQdIMlvoDRa9Qxk6YwlmU39CtIGDsN4r+Nf5Y+mN9xcKp2Daqo+ABY=
    password: AgAbL5mPP83a91jjf/JB8RW2dYHBWK02Vmyf2PwKytyD8CjNj/5j7PjCi6mKRBKTN2GQQ4KhrzKlBBMDI0IgBy8Y4NquZmGRhFlDx7K305bpa1BCZPsoMQF4BH/UQI05FL9k/LsAgdBOn/VZvZHDgn+ASOlnbS07MptOHdUZKljEt6mczPtg8GQ5OrHBtMuAjz7LEminlLYfspzlEQ5J3WOyX0W5Cdo1q3r0uIGOK4amftCRR9vtoZJvKymXy5nFibP8BJCw757Mh1HVs/hcCYJbbG9xpWr+B14Vmg3ePhz2DQSiWqMwwarcecbr67s7PHhg9dWlUury90qHTUY1Ut2BjDog79l/OmVDEGXMXl0wxGqYq46caXvb+gg1DbJPZyLXq9h3nDapZUM+9HE2lKnbKa7ljUx7A3lhS1xhtoOHOe3mBhkfFDgYmlYX8zfwMjwAzjRXjtH/AaIFDBw+5VE1CmXlIkJ3G83K6g9Go8II5yij/6wHB+4LXC9v4mRbnhi6+xpCfu4jakvXSWJN8wQweB83kdTiDI4WV9WskHIzuOmoD9iyVcGy2caJb5ALAXkPW8XF8a3YfCvhRyKE8Oe0Hs2OHqSo0oOtaYUlx7j73Il7F6p3/GTPqtDtySGyexFf8W6Jy52x0t6MURRMCGgMaOhV41BfCmYRTFz72PbSjp/NEuz80E7gBA5ZMI15mAjBBMw20Z7Ssm6YAD6OPYaS8289qcxZUw==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-staging
    type: Opaque
