---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgB7OARz/aLPz7f2uK93lU2M8NA/rWCOuPBZG79Ya83Abq/8vUwRtgAttIhp1KsPG82uNdys5WjsBpQX3o8El7NEtWfnWWwFoEwsYuwck8MWuDn2dWX6w2pGW7AqFsVZ1ZRfO+9erDnQd379/0Z2G3CggxGakmpAysSp/+eMoX/aTbrdIOtJRC2x8bUdEPnza/7oNjpI5k0vfEFfD9ek4gNNzWpUAvzjdvdIo0+g0IAa7spOeZiSLNvvNbypfQAn9q5nQl90OerfH5wwPN+D7MUCo68sF3yqALJ1KPrV5f/syxqvmGDD5RwLco6zoacIO2cE0sly0+RZh7Nv5TU8tIYTcLCE9f3FPQAEEDLbR0ouLne3MSaI3KCdR4ZPFLzQNRgg8c1G3t65Li2LGhDePrGBsLhipndv4xmssbk7Btcqzao3kdaQ3KVJmu0RFlXbTfB44pnHgXSU4G4S1NEme53zHcdIJQ7r04WgDz1gVjfZWtKjsLrOr5bC+XGYsqVz3DkE9NBcaUWeTwzK9zeJwIglCVuGIIELJjmP2tKZquCjkokSEH8bMsJ90htS0LLLYTyhRZTeld/aIqq4hPg2wqYvw1WmzLZjLozpqYv9XRlxKhi3KNczsU2UpGRKVHqV3uGqI8Y1PyfmDM91AHTgwyScFQXGtlei0+ByeVBeJeH2u93GQxB+72VcDRl5801DWuQoQr4SpTTphe6WLgQpNw/2Th2MWHzjnOcyZiFZO6oS9DzGbm1krpMD4FkT0iq9iu5Q8iD8A4j+Cs+qDTIcKBrgqFWB6IoPEc4YeE0Y35hq4QpkalrKv5kPpmm7R1vDcsuRpC8LgzsPZ59/2llgfAGp5QQ=
    password: AgBZxknbos7iiIRmEcA3GdZPwrANbBw6oL6YsELBWEnjXwFKdHmsM5k0UlKJ0WkSZI83u0neTHmWtq43eSuReIZnECCmT9sN4ekYM5k4FKvuoFvyAazb6wR7Eio06rdIjnrMRRctoaFhXLBbfhR3O1xSwNGrpht0RveEjgr2jqqi7UlW92XY0VO7o/zeS3ovLGYK/6xRiNj327PuaHMPSjTQayFHBm0A6trSgMlNGye17KPMA/qifWrp+/SJK2qeVWqQHLp+td9o3qZ0Wqec7YYn1dsCPvuvKjAx3p1LO6NCqk4Ts8xkWhHSYu//ksiLNVcNLrLh7y3SIK9wUveFgiqZ8TAF4cv5qQnxFqHpp4Zb38Jv7ijXCO4WPiHIWpCzQZgr12cmRLkDzWzDjPNl8QDsU1mwKdIjIc0kSFytGCgyXH/MZmQQnOVj1TiQpwW34sfUahPcqYluuPLkOhKnmn0PcZmIDxNCQgCAY4GLK94p0rpv8riGleZ/HOby6Fs+cliBdW60aMpWulbOw0S/kPdRCxodIPvqq3ps/1dqhsV0l9cqoFhD663w8IL22oiY3ARpgaWO1Tin5lTuHQpB14xrZ1q1yheA4GvgqZXryLcC6XMql4ktaSiqdSnakluh3ycOhAr43x/HUANhyNnAAONTwrbwOwjRTI9adONzb2d6RnjepRk4FtpF91m29whZDNiSPpKHUirXzCEaqEN+qwDlsiaIS0nyyA==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-staging
    type: Opaque
