---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-pull-secret
  namespace: vroom-dev
spec:
  encryptedData:
    .dockerconfigjson: AgBg1zI3ZtW7gh1BrX2gKE4KBxjKHsbVLxZ+MyCtc53fRud7fWJu/mca1Mso+mtZL562T/PJCmU33cs4qjfsJoANW40VCXcHXOjmydOyoKv0vB9qz7JkqvF+kV/CQ8Zi/Tdw4x0EXy4rhZqEQVDdVk/xGK9qNl1FdgzMh5SPu1lE4SuC3yR8XY+LYBJ7yl72s7uIQANS6zdWf5vi2V6NH4hrpSfMND8LTsQ5Orv/QvL/yY/d/RkCCptCPp0iGk1rcke4LJUZ7oSH3uMWQ1l/DWh+eHxMrzlxGo/BFzud2LFnwvuAI2LppioKNkb7kctdq53IdHJ4jZRUgglx3QTsNq80pZqY9ILPHzvcNdysAjgzRfvzctXdzkYCgHdr5s5l+24lnGq83eMboKxVxWztn/zX5xdWqQEkqG+nKi+d24MaD22ZFn8mzSMy7/wFX+kHEKf156B1+n/EaOsATBmY3DdgVVev6xLh8X73759PubYqt9Y7WrZnnJTVQnybUd01/ICNlxlM6HBgdHxQ+uIEZhU3OZXeLBiymD03Z7OzlIrrXpyQIfRo8zZGYi/OtEZE7PCMu1E4QiFZS6XG1mISWJRCTnSwYMCqQVp2FgWcuQxX5fGYYpkf3XtKQb5BuniNtBEGSyNN3Ku9PNyvEM4RYLNJljshyZqbxEVw237ooZ3/XQ2kBovj3hAcwmT9sjgV4Jh1+lH4kasvdHwy5xeEK9XrqG4QBlm4+iS7vJuiD5utuRL6aV0QNA9/d6u0iGqj+6NPsipHKeQdaFU6ATCX42kJpqF+g9Rqcv4XQ72IiZkInuo7b/x0U9ktWEZXWrS8xiDtNZann1RC7L8i5yxRYB4otTVlFb1Yyn9glKBKhWQaDrHe9FUqSeQfVKKR9bPE3ki+Guy6Y6Xn4+4d7veoyAzLNJOOX4AhbOU=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-pull-secret
      namespace: vroom-dev
    type: kubernetes.io/dockerconfigjson
