---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-pull-secret
  namespace: vroom-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAxqenyq+HFSgquUegBrCfm3jw4VlpSXD8BOWW8L/c4Z+U/xGuydM3qr1i0U/ACCuAaDsDHldh0I+2k3WHIdAnJxaG3fvVibBq/fVVbV5MgB0j61t1ND9T+mdaCxgZ+4HccoAfq9YkVgGpkR0A5TxHDFFEFKERWoVkJXDg0uZZ6YjUpqxHNmmbeyy06MX71yCjz2kUwVcaiLOQvygEuzoLkh20hj3oTYmkrIJv81CamBT+owxs40Tp/HRifO/oYHsf2B/esXAYXk3uTaoDf1eaO1lgEr7qn3kws+yOdsivOlNanm54T5DxAzDxAK2Zx3mies7t4TDrMChLDgw25SES39zL9HZz4/l+5+DQx5HW+wIdJjoT1wkdcyt5zaJBliLytkkBw/icw1rdlzsUsXegH4kdYGA9otCne9gg1cwTr4t8vGWESALL/rWmwvZF04OdLhXS8cYWRbJg5aW4rcOCbPEMWRFOxb/MFykZN3tz7KeGkry1K1PswDEeYLA/PIteyJI321Umj1pGLc/aJIsyPlOKFPAWy6u1Fd8Zi5K7UE3ILHQgAmNCSu+kvpHkDbDgYYqExvFKYophc0kt0yIDEeNcYInb0zEK9SSynOsYemMYYBVkD+uwrlXXDwka5Y4qNcuB5nwZTk5ZWY0ZW2QDg4hNxf8/fef+Rmui7j7qrO55zr06Saawolqg1hOsehSk/qXZnxj6YBkf/bkjYpGkZVbtTNfNee4ZRislg6pz/lUVRKpi6Wzz1cUyc0UAA2mI5bEhkITIBkl4CAsIthj53xdjQNBYtuYLyP6JcEnNbB+wN+y4y77e+gmTLCGEvY2yVhUpJUf3Qa1JwLWxROXdMt1AeTAjjsVvzoWC2tPXOrB/RXBId0t7a/NYX4NSNXi+3gcpajhFi0Xtvo7EHwyP9Mhld7DWiQAhine/3lXd+2qAPi2TUMW5KLBITNSqIGJmIWy+aeIunKRTe2orjn3XNLAIvicy+CZOLdm+nMEZCN77S+nQ=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-pull-secret
      namespace: vroom-dev
    type: kubernetes.io/dockerconfigjson
