apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: user-db-secrets
  namespace: vroom
spec:
  encryptedData:
    database_url: AgDevt/UhDpDmdC5xebFps7+rS43++6VPGkbn3E9cPEVdswzKD7CbyvRaoWFY0cNQDDdfUMq18smO2EJHWjz8Z/o02l0dennIWZLCrK0RTK7WR925UEF37JYun5oZe12U6R2zvwCggSgik2c2W29oq/jlWtHGK+pKk9aUOH/OsyLcZylrKQI6IDHyt0TOl6T7ee84JlNGWv2xcNPGwvqqKfgPL4YzM0FC9FLYHU6/5qikjzofZfWKX266lzy/rcdGGDxrJ/lcTKjLYnRT4xs9xUvdC+rPZjTW98rZQnbdR01Sw3v0JPnZ51vQrdkI5duDqomAUzh+aaJeVG/JUe+PzMqXfwTiFQGNV957+xA2p/54B0ncw+SsM0tD/dMCg/0rSkRXr5hnO2CB9Ke61lj/m+0YlftOHCBE8eb/l5U0FFxyGxCC8XwE8pNErJstF++F5q/YmmdY6DIr2ytB4YXi25ZJihR7+zp08R0+iDSDEWaw/5OFJnA/vmZhaMsseHgu7Ym5B5o2cIc8b/Q/74b+Z9p7ls69MjhCA4r4Hxc88sYmj56IVistyPh4zfuFHxUL7gIi8iVvV32WmZ2wx92JCY2nszOZrZpGfsF6WJ7FNiYo5fu4q1fmens9dLJ4NRG5bVXRjuV8BaxoWTnHBgguy3CPyFpAugmYxAJZc1ncOi2m5TVgUt7fyTEI+IBX81aaASaGIqW2pz8OE65ULTz7AAqmryD7eNGzxIhGP69qfQaHkCurh6NbkJ2VPz3Hd3b/vdnPylIjBXmcZyWawMLX+oDbNz15ZZLHmRZJ7ttMehttvV+
    password: AgDIJVMBbk553368JK0jxFARYWHHk/iH5oQYO6AVMt+I5cKJmtD5MJIQe44xXinq9a26EmrKIARxGjUaLTkcprXIMWsvySVRWbI2P1+rWAwgDAh66+DJ1V/Qp9Nryhc4usrBweZsmlA4ggWcYZOS36150R+Ny5d5z5o3EQbBGdglWZWsIL3BsdgDlQTjLpzJn+RY1xVXMxjdUltNTPokKgO/Rl1ym1+mrWufE6bxhfJFQLBtmrFifO8j2Yd367Yt9g0trIqwQAhQ/K/+Ymaf4pH+gb28BfqHppwlYFCeYHH+weZLsfieaOrNr+mmnXEM6cg9Y/CjTALMg5HExJ1FgdaelZt6DcnRslUpShE/uPUrrkxW2EyRO10F5vJOR1QTqnsBQirPfmLc5ST27Jet8F9WqnGjYEqlNECraO5AUpnicvUjVCFE9ANCbO4sMkStXAxS5YhlkaWcv0gZxaj1nm0q4FZrd6yqF+3hZOmdHtU0V0qHyBRAwzRn2KVGX0k9F3Iu+4NfirnMe6W4GfiTDF053sGZD1F090Oz/RoDaNUa38woYkdvand91osUgl4+Y/EiWrUY87bfaCktCZ+5zAmRFw3b4WvidMJFsaI3oKwO/YB0maD6fqDjsDnWfRPfLRJlcQ3codOw9HhxgfrWy1eQ4VZL3SkaijMbPTySC0e8pG35+lBXKqfpDXMTszkF9BWUITfg24NVuaSpP5APew=
  template:
    metadata:
      name: user-db-secrets
      namespace: vroom
    type: Opaque
