---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgB96kUV4IYDfbSfGzOqUXzMKA5LwDOGmuA9iqadwzrCTtzpfGBlC4P6cnYt9JGIJfQgkaEG0WPYU1+e6O1LqapF2vuAbOi/ua+iS4EYJXyt4s0HaYe4FuypnFdPGgu19229nN6955Tu4m0YeoG0ttcVA8a+D2UPn5dVNXLq+z3Ysrbs8chwzoZNaCFOjvSdKEdpJwM/ZUjs3BYFIYZrG1H8FW+f5kq+DJIrtrg9aIddQttryiK6olJxCQbb+NZtxnQKGl5aJ///PggcdBbYaF3O05rAJDxY4jZvLdmUApkz4WI1e2lv3kRqC4b3+ovfqABn3zJowPVX27MIEtLzuLdXlXR/INdc5zNfFoTsL34RKdSf+QS/KComJDG+O3bHqUsxaUJgtQppI9aNM6D5DRZOrmjdKg/jxLeM2tQdtgEX9qrwOuDabStUuJK/By2xyx8Lfv1vojqMFIr970oa8dRMa6FzGHtykRZepv9VfiG0gn47U5rh760yTYXwtIwq+k+UfrV7FBjWdv2hVJTYlZEQIq6dzwYCX/J8ZPTCbqeiJTtMKVZlUkVyaU2PfsLJyubWnudb3K2Ecy5WKzaCiIq49alTU30Bb796+HZF2AMI6q4bhf367jsOetVEGtZmrZEckunA/RrHVmSdi7icgSyAbdkWHM9zwGVpgLkKevwAswBgilJXebZBjnHZsc9MK3fx6VMmPiuU/vthzxonlgw74d+QINc9Sn7qB2TTIDj4MKJZKkdMaitD0s1XVIBPhZCKUZ/1W9hQB8sltiWQU4aD4IVAKXc0bvs8xO9SsXC54fGFLhP8H+HMpFSt0V2MQ4jLNQ==
    password: AgCCMIKreuDlcjVZzuSyhnjua0cm8jc+qVEg/kAI4FOt0smMqWWziLhWIuGFBsToG8Y7uSbtGv/26r00g3StTjtSkWtIGo49X16LWlQo9QjdM/Qkp9LmKTXLAP71h0u1EgLdszJ7Gynbm+chRMaIo7CryuHhgxTqqwQFsAGCkcb4duyfb/cH49O+lV0z3ueAPQZaWazYSbhin480YU3m+ZxiJgi7ImrU8zzsB8BoTGWuKF9G/npRO8AcIyhAkKsak/va7zPjr2GLZ0CTAEKvIR0hPP+p+rG5Dt7w2QGo5ez+7UjKAxY6PcSSsxIRlbFadeAfgBjcWzELf3Z3j+yvwn4TLn913yFq/Ts/br2TgdL/HIZGmL82OGJQWvktjzl9o1+bak9XmOStsnEQIIstIrvSb2rTHLxcwF4R3/jt3wh5sjb7CYh9gvh1o7O2oTlZk/RvdqjH/SAEhJTH+kIW1iFhDKcf1pWYcPHXxc++liQ1vB/wtuuQ9aVLBBkMCfhdcwZM5+VjgecC4XI8ORDI8rs5Bbx4ycex+AYjHRzmezBZnjayzBuiqlTs3WVZtqWK4EJcty5qtj5SGl6XsvsOGdvU7vIKV4WOyVp77XCHJ8DPRgNI+fCVnEEE6+vlB16U03iR8nQ/mxkOPnqOTxo+QCFMN3s5+PcVf1JYL0vTRO3kY3IUscVtZOzzz/3FR1ZotcphTmLsW280h/R4fdajzXE=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-dev
    type: Opaque
