apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgCW/6wSKjP1b7Q33wH0S5uzdqqW3mEybmGer9S8M+AoLPNeddHL59d+GpMzUGg0GNA+jbBtqx/Ht2BB+1H3FmyPUT3xLcLG5/o/hTV1eq5O4sTmGMVcPs9bcOL2f6O5hCv9J0rxpl5jg38t7X3i0YKFuI6L+mmLCP/CFBu2DaDhqjhLFYW0+ZOaC/wItj9wHtesUY+Y3ZIV0CJnpZKd29Pt1XRPNkZrNrZ4MHLs+o3UhviujcPLxv1EHGRNl8yhneEFLsRVU9WB0tIfzOuRXO3GilrgC+Lfb3A4z5kNTwEEGjkOM1dpLS+pf7X/odQBu83a71GNjb6iccjvMkClfWzamvzZ7Gp4cake+tykYP+GZPVavR+g5Hb6xWZGAo2YJ8sop84nvojTh+Pr7cdXh/pcqhqizZadFXBmqoOfibdoQA3gBo/5jepnQ8qPmBcilf0rFrPCdvDxCyWXmM6pzec3RBzs/xc/2d0YtXDdCjfL5M8nQLZ332YnnVWVrb4t1qaREntK3hULvtPlv+R7IK3j0UhuLpGvEmbx1jqEk1JGo9JNWOJwCUQ1wmLaonawgxle65wuWNWV0Psy/h7mCMGYskCBX3He+kiA9ifyErFDiy6XlTYxp8N69A/V8fVAqfF2hYziW6Mrtqh0dZWVFngpx6yxzO/XzHafMR54K48Fljtagg1/P9OmIvPxEOIMou8dac2PBndQhbHqZ/jZlAQ3nEITkSxj8G0r4OzP6iBli0Aoa8k9z0cRjQ4E766XjBQUzuWb5ExhewkI1OEawiU3pqkQmaR5ik6nHqDWpJaYWSHUE99OIqeSM7XDwkglUGivCQ==
    password: AgAcSBYgpUdZdBJ84r48ZjGDbJgNe8G9v/bRQuES0Xfd1buh/lsvS7qAwOTdClKyWly+t6pNsEyPfz9Bez+sqjEyjAPbpySx5kVrc9Bof5ZbSNuwaAIBRSRY5N37/Fk1L2bmoJD2ZSIhJuyoPgS2ntjBlOV+33CeEEmj21bf0x7ZXlcaAIsDpgelvIoiWmNkc9GqI/GaDm7BmOysF5vNb4q8QL6cmkxCHBQI8DA35vBnrSt2yK1fiijsR7Y3Osm2+vUaU7JUc8sId+MtRQDHXqWP0KZGbcwLM1CY76+yBqYpf4KeMcSXABL1t/7WcnIwFIFxufvcvm+Vg5p0R7QSfqrhSUgmdvvQvFoQ02Jb/cReDRnL6h9UgnITI4S65MeXWovrgqwBwUCZBsU7TwL3qZkHpF52q11ze9D164ubbZX5I12Nq+W3EibZBZYeNOzK5/J0+pU/ojRyNf9teSQ3fCme94vIJjaa0VsDaSGKYeJcAdD86cE9xXVRIG/vDrw+87uDunsmAEiLX1ODAvVvJj906/yHDYWWqDIBV+jtyH760E+Duy7QHi9zGKPXWw8QRiZqFRCAzrPv9zRw/N2/W7WOZH6y4rukmCa9GdeAOVNuUpGdU9DUkEGK6hW4o8NQ6wGUFHImMTx++7MF2aqEZDiOY8BoJYgTymkLy4qhab8mUWRbjv6s71Vr6K0MKxasd4F4XmOD+x/g9yAf80khmbM=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-dev
    type: Opaque

