apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom
spec:
  encryptedData:
    database_url: AgBrSJKf+eYE3/WVpFp5Tt3Y/U0FF0gekKKmAToedJVCkpdgx0j0cdxr3DXy3blXx6GBEdy3f81wNnUVQgMqHOuHbe9ClCxI8C/X/mtGDJsQ19xdLboLbNe9MIBKurPW0yQLYIlpIEGUPAFINRF58uMzL36zxLvDTYk/893XTdQgz6VydfctDQiIratVRqYVwGIfTgXwwazkTIli8l1ydiHbXt3oN84dVKh+3BpdslFZ9YmyK5zAzY+nIexn1avwHo+7I4BVkIic9An7GlC2sCvTEPIsdUQJp08HloJhKkwflCU9wvIFjC1+6vfkLLLs1jeanxHjU/kdlKbLvCYOd6SFp84lwUFihDYWLJIohHtFQ9PAtYIzE6/m2ZkpA8t61+Buf4se38yvDJ6N9bSTO+j+MzRWDsuCfbEF1I/dh3//HkCTYxLfsgdMpPSEE/4dL46J7Q7yDeeUtNoNY/+0JjvuJm4TJF6+jhsGAO0MrWBcS1rmzGGxAiYGA/kFF0Ma9RBZ2utOxKqwMn1Lsj33xkvIX4IWLUhE0D5Seo9aV3/ggDQfQPPSznQtujhtnyOahVJ53Jcy8/qFWnwGwpyeltnNMssQu55VrqdZoQqH3Z1cYTzw5h1zvR4BsoQ4gLhGoK90B45M/N4eb/0LZi3wUGee6WyGSVOGV+spcmOCIyizVQpRXJQNErzmNGssfr7J+ohTAyxZ/oYhwC+2xmdejFwhY4NZUPE4lRLjUWKlw9g1RHYZsLSj8aGOrNJB1krdFXUB+QPz5n4kbnruFWrTHJcLBWqn58ORCpU581hDnY6HETdG
    password: AgDjBtlH7w3I7BUC/h5M8AXvWy+twprlmDjhenBqOLWMak1lgxGjaozK5GQddsFybXMPmHI48NjvpQrIxZf9yfmQnA5nQ7Aj9RrawxedAVnTp4DKhquvi/qYcuc8pZiync6Wm0liSgNLDzvGudb6voROkry0k/Rxje20CDNV94KNIXI1eMI7ruyCshrsXj6XDiqbFrJTnMf44zYBKWQWnTfLwkj31g3TDy8b/P286Q4lyJIVLmynw2PYlLDxD4YVLrSgOBwfjIqHmJYSqL4aaUnmuA+W3g34y7HsJPP/dy66coGKyWeSjUnquJT7RxQVvdI/Z4F1Ys8wqpyZjZH4pI9hAxTaSkyc+Q9nBdSuz/ffaR3OgJPTV9q67sqpld0wFYNOgo6RjTnzbw397ngLHIrYpxNZqmMiABTPGTreCWkyf9KEAU5fUPIXQu2PEpbqqrPIRgTZQd78s87zOMsuHJZQn3UGMyDvW72aLrc3sAXQ5GDZzscD0XGnhL1ddTLoSsfGsGahHClcrcshUG6BGPrPwyaBa15y6rCWpsF7dHwvLSnL2P1zX42USS6f4Y7Bt16BEwxyDJM0A51+xOuVHAoJMWHczJ36L4lzeCi0IlPBb2tNsiv0qjCif6WrBmEI0L7iodVwISeOI8Y2IxObDE7mYIgfmetPg4tUxFEtFZVoitnm798r0jth0+fZnPEA57tCXEWkG0K/0xEkLU+GqZU=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom
    type: Opaque

