apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- secrets/ride-db-secrets.yaml
namespace: vroom-dev
patches:
- path: patches/resource_limits.yaml
labels:
- pairs:
    env: dev
images:
- name: vroom-mvp/ride-service
  newName: ama2352/vroom-mvp-ride-service
  digest: sha256:257d670b997cbd10c9461933600c699875c7ab6f00c0065740ed62768e7d0928
