apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- secrets/ride-db-secrets.yaml
namespace: vroom-dev
patches:
- path: patches/resource_limits.yaml
labels:
- pairs:
    env: dev
images:
- name: vroom-mvp/ride-service
  newName: ama2352/vroom-mvp-ride-service
  digest: sha256:33a7f4dc9c72dc31c4a67d4843a2a69133fc402a60446441d6d408b305c835b1
