apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: vroom-prod
patches:
- path: patches/resource_limits.yaml
- path: patches/replicas.yaml
labels:
- pairs:
    env: prod
images:
- name: vroom-mvp/dispatch-service
  newName: ama2352/vroom-mvp-dispatch-service
  digest: sha256:b24d567eb8c69182b1061de09d8a68695a86152c686e5cd9b60f23fcfca15022
