---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgCYr+DUsOGn9eLb9+fE7DpXqDZ0CqOiE+UfqG/1DaSPb5svzVsEWEg/sEbJh+9pXybw+a7+hdaDnBwvEvE9+QjjXy3WdU13U8c+l0/eFkTaXRAoHkmVWsrzGMNNiq/2wWuJKNXkGcicPRBolnY+bewzg/H1sd5aV4opDbRZRNXQepXv0XgqJ8P4xL/PuwSB3Zgq7zMdma1sleR5LmMxxbjmYhnZ9fdQxQdOO5Xq8wqTmTJ9IEYlE8yk1HMisntgiQ0aAwCJqgOeqXc4tMb11NxeQPVqRvuQHOJGHPXB/KkrK0mpfTB7dv0meAuTWfbYynWLsbqtrA1c2ggs3cSgLZh8aWTif/VYtxmyisvp+HvY6pTLmnRioIVoJMAE7yQ0NKccTYbcT8FTNKKFu8JtlhdyUrDipMLktV6y68f9Iz9USmBHMqq8WCRku4J+Sjys7mha1npRIW45vF1e1pTGQafLPEKyRMfXHoO6IsqpjOPs68QtjRoFVfzDTcFvOt/2ZKxjB7R9OAYl5BzRSXul5vAmArzSG1nv+mhpr4D5uriAKC0GUTyLUcAJ0xLE/0zvSrYPiWGXp7P0E2p/r64xe39UR0NhwAHhZWTfDtxhfW2ryfGLwwjswmyhDtWT6m7tIBCov3dd0es4JqFhna0fTzO1Dwn4409SV98P5XkqW63AHxrP+JaxpE9zI9TdOXOEO7zWSvGxXh3juhl4DFLrSMexaUtw38Jnakiyaum7u7yKQumxDMAr4WM5jWUG1MefoO6d5u0i0yaNpeCC8X+faBr3GsMlTA0+MfECmq3O5cImgciltwWgGT9UKz2ngtJrLlvHZWuDsLwXeZqXYpjmqaYzv44=
    password: AgAdqaLsK0mdxzVjMNB3YLVBlmDLb4P+UC5H1SB6qe1iQfJND/Lep7yR5VCMkzOvZL3LuNFqJ0ugAb6le5mXfwtwHuK5CH/xzLQ+e2TAnCiWOi0KlJ3/S7E311eOhKqH8EHfUo5KCn4iz1JpsqPzvo/kJESnpvwVwNEXdi+9L/UnsD/Q8vzTgU3bfF/4D3V7f+rWGktaAf5DkUnDamf96f16ieUiPAS8lG38V1RFwkgsoTr33upbfoOih+eA/4x9NAlsPHrZmJv2DD/vyQO5rv976K8gAfaDLMJ1ikEE84GhHDuU4Lkk+0N4CBIp2SgTo6HzUxRwSrhOX0/aJj81jc1f/4QZ6z/2qgUWLtJE6ZEfWFiYBeSr20pA7zOjfp7BWuRm3r5J5kN22p3O+PpnM5D17pFcXgpbgqUtMpGRhtIvgGta28Rd7NioZZnlnxzLRFVmqesIDd+bxHlHIWu8XQ901UL/73lq5Dk4STOCZGOR0orJGuMqYSLeERaSxGj6+ME2ZlUgrSuXFf+f3cpP83vgXuIKR9zsz0nUIGVvc+DrIR9pSzrtimg6/90+jbWwAGAHM+PClxtSt3sNy5TzVkG1BQgg7sPA7zvRwfSkMx3UhRn72TFT4WRBJGDOMKkvGjSLKCT5F/QVqRFgLuVpYPZk4p1qeDRdDv+XL10dlZyQPdOMPkWkwnxWS5ACFLrW93Y6eopBIytnqEELmvG+QLGL2aYpY55A6g==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-dev
    type: Opaque
