---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgCfb7uP3DueOiDNdN4ZvI9dZTDLu8TYCv8a1q8rYHOa7rxjk2ZvRAx5YmPlHCUIKSHgIlQRX6QrYQctC4hhKSV2tqZupShGLVgCIJCPjse+MgI0ZiKWPIGV0d6s6UCX49JdtOQMdgsQFUpKmiZeD26YqIn8NnRps7zMn8CJstVvqHmU0mao11f8xaXzbd3xfTxFAw6Ddmekp7vAlY/i+8ANF4yPOIwyA0c+om9oY6YDIOQ8qEZ8mxtABnqleiyBI9UebcPZ4VjXvc89k+akgVx0946hyleECalfJA75wflU5ewfdHuo58hR4r0j/F5VJWjcXGEwr6OJPLy1H4cVajOgGeOG0/wEnUiD4zlNuo/5E1Af9xgZG1yGZf6EdH13eZ8dXjxaxl4SgoBqiPCmAuzDOaxe4SMpeAXPMoQI1sPm8p9tFP1zNEwFMthoWuFbR+U9agyQE2K3DetN38iaNcvFfKX9t4um0viyE7h6p823Dc9s1/Vwfdglqu8nh626z8Md6G+RIHfQsLDB7P3SEeoODHDxOcwWBR61//5+ypoQmVd0fJq+jTso7m8kVN0zjWg6AsFLiYUgAK1SYT09I/iIRI9PK6ipejv0DTExKac67n35UzScnCt5CXtLNP3K13EI9cEwPCXGuHihzoWSqtetvpHDO9dF9YuvQnyY77khaeGmn9fsH3zaq5GRY8a4L2Uil+pa1vTZFIwKOWXCmaI5aRuH3KtW6FUkNPVeWN3Uu5vbAYvoHXeDwJcWz3IJc9UAEQNDLrRNhxBnzsD2a8QLo55R5i8vWMojw5AZHUHQSWo148hZsxkiG6XV0iFXc7IWQoDY8FJGYRu1HkmDgLTeS/4=
    password: AgAlIMkptrc5jXIbeME2olg6vAUQSFSoLK4K90QnDVMXXoJoaps38Fv6W8xPWnjYVe8tDOsGEE/dh9jnCdrtlYkCaWEbHybR9m+RoOBj2rJTQx7NVNR/z2AqiIbFQCzZQwc8MK9qUvB7Kt4Dv/vht8Fo7+jSbbMQEo2nezKXtyUK9H26chUC7PTWbvd19qXjRlgVog4KhUdYoriXIvCXCOB/Y/4Kv3JlvhXTQ3VL19oqzhfPdpYncSt3/2q1lZuEhYHVjBlVGGDXSi80OttPJp/AnP9ch/fu3aaXAYMTu/GCLvtFnmAZGtfclc1lerEiDtRS2C7dbF5+Iy1cbtGFuDOM0HJbWdsi4vdq3q8QumlYDV31BFLaS1VJst12sQNd8yezjCWd7A2tRfipv6DHSnyanU/kk6CVjF+Vz2OQNvVei4ju8vuXEK8MafV8jkxBvviF6gL1o1eltPx16zfhHlJY+E5UB9edoPpai/0yyk9Yvl8ypYQm0yYWP8YjI7F5K723JmTXJyIV5S1Igc0J1TYJqUZDheAtn9Mz1UKRxExMqcLpnD+vpRYjG3Oj2W41Buq9Ha2ogI/9vVYCeWpqR1Rv7wdco77ytSPVv49P8Wgz9Fz4z1iF1gtqz2+/NrxawMVHQkdldGMRCYHglBqfqT5mVr2NTyISyWRSW5fc/4j5C+LCmm14Eybv6yXrZgWyuJn97iSs91gDlZ8GCrvF6RHY/Mv4MwSsfQ==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-dev
    type: Opaque
