---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgBC8Tua36IqXnnEQFhj+FYu8cgxkXgt9m7eTN3PlhA/GVCp7gyfnqw8TVFQNFzw5fAxnXEnvNDDDoYRUrBt2/eihV3jXbz+A+gyx8PVrpyla6/6p4Hwz9A8P8+w9m6+xGo56TeoaNC7wvJAVsdf0H/Q5F8mGud11fW3+LNBDwzO3CaHVsEqgaWtf8QbzgNVyifcHXWqH3Xc5AOkiaj5DEcapA7qpNsqk1+iKoQlfucYXh6HWtkBalV0ITAT3EnMls1oWmiyy5ixgxw182QqLpnfatmBdiUFLc2AxZt54C2hBtR0CjEKSXb4oNgvYSKB0W8BK+6pA9yiufU0d5EDvMQ1kf9Sgl3llTbKMshV6mRrq8o0JM9tq0fwVoWtLRZngPc34Qi0LAfy+3UqOT70N1aLKdmAxBowc3upwQv5B7sMNx+TyZWIMk3cSRpDekRORrsignWHvH/8oU5LjFg3v9Sq+EDB+IX0aLNRTYqyizTu0DxbypXc1YN3zp0wlR2/kr04196J3+LV5N0wR6VdHGwl6GJomvmW2OcXXI6mqVUDE0CedyefyBLZOs3zinkOy04ob2AgPqZCqbmr2buNDba34p9aNkfMZHARlwYdm9sjXbIsHFcK8WnqlsZ4QxcPEigBs8cglPN6V6hEqQo6Y0IDW9wIGBVn71KRlVKAtQqywB/PZShDPjSg5Mywg5kyKZ8LCxLBbm4vpUq3kHqI5gqVaqNx7RhPJfUvY6JNLqsRqLZN/1EMkdcLzCDSFfui8LsrFEZCL+9CTqKXy9bWkZgq0IG6vvODo5rg93GD9eTerCz5OxHWse77NHbKRkWQH7WqNj3hEFZPpbKqTn7KUxUJ6V0=
    password: AgAqKlCFfq/Sz92uG+asB0cC0lekyePNKwIeUx6HVJrBz8Q77rU0q/Fqm1VYmTvVG+AysUszRVvaWbaeejHs6Nlb4AmO5a+Ch/HZOi3jUQI1gpjadRdS1iMzV2bul4MtFLDdkOQ/0e41M4/FSF8C9N1tk8unwcSAD/LeYQN3CT5ydsvrSz8aGyk/3vaOz+xzhM8moz+8QrHyobhBWOpPxzMzx36cGbcqQvyIqLjhc3ci98JShcNLsXLqtBVnjCkwOE7JCIFN6XRybnHjCV99wi1FgT5XliDUn3bOHcvIt0mv3YS7yfHD6s7jhEHVMgZnz5ZJz925R7ykKDOrGQo5BaGD/PMXkFrZbZ0OWhxh9kpV/cr+URFLeCEXtx6f4R2u4RK1s8qfOloMuX9wJobPX37NHcq2T6L5qGK7X0FvtM6KVasQZnRHexLVD0DZU89djbTKTHZOWpm3OTqhyvKWQDO5cV5XeoA0TqkASv8lZg2+lRR8YPelW34378A2U1VeCdVtHOTpv6RMECDo76O3TdQvMixRNjVzRa2sb4weX/qarCn9vq8GLckal6Wvmx7qo+qqQMX3l70ziHdg+4ig/nkrp5dh5N5mdp5rCZgAZZqs0UC0S9Et0cqYFndqTR9owooCHmPGT7mFjmmc32Rh7nbIwl9sfeGUnA199BamN2CRPe6NulVAZaSYGeAQctz7zKSscP55OY4PmdaN7cRZlXdTV1BqFnlUJA==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-dev
    type: Opaque
