---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgAWtARRECgd+lheq2i6ZE7V9UspY2ZUboTOcw8QWP2VRPtY+YgK7eA8f7ixzOcnri+vFbfPeoyMyFJBLOSersnB41DlgdQ4ZADrDYEchfiFLPiEh9wmaEC9wLDeuAaRL8tUKQzrpqtiGCwnYaMbrY9w8F7JqQwoWfEc/iAdWa9/goSQ0Uf0kZo/sioNzVmMrvVLIW0uWNkw7N1RgonP400CsYx5BR00ENDF8D6qY/h6U+1QZBspQ5LiGB8yCcUGxd22I/ed/s9+fCPMuHfJHpaFYWlLBIR3x/zspC5R8Iv12NB5RIgemIBqoiKErWc4GUPVEtzKI6jupFH0G7mI/DiS2i1Pxdyzqm9HW5YUMwkqijoAT0Cn+Jrjrqp9wcQo/5yBaJUnX+J2cI+rNuIEDoxCJapdTMRMrZ2H3Loc4GDjhGKfEg6/aht5eRI3uuwvOoykHvut7crbY3i9hTxkyTrDEqEXkxC929Mgt11Nn23XKOJ0ldcI2KOnlfTWlMm74+F1cGrfEzWaB0uyQIOcXW/yfjHRhYwrfB4IEHaF4LFjk2repQKWjFJLYG5zMss8G7AkjNNYF4JmuwX/umCG5nq8X1iIP0+y88gLMXGaEBGtBrMbrOxphIGkxqiq9WP29M+Yu3R4gcxUlucKUzZfzA4PTHRkjNjeKR9fA+B8DGw52yT44IIqhxrofb37YOh/Sb1t1o/dxUINbacedXMYG/WeXXvGoqb2AfA6OEoJ8chMt3D2cnHt8IvdJPPerssfsNgv7iE8Dq7TV2pGeWDJzKPEh4ppT2epNgzHOWYPImAAx6plZbirlTu682bXie0an+bv+w==
    password: AgBqzNx4do6M90OEBUpXi2x1OyqnTwfCljar5ESx6NPRAIXXeI0hsJiOm354ZIVnTBAIjOSeshBskaj1ljdFDBQXd0sLM+ub5CNuRdYAaqbgznSREOgURIzA6gLs6jBG5k783/UkoP0sf+OBqlH+LkRLx1U5WK2UAkWO6ASvH6q3qkK0y+h4mo9PjKGSLaRJglWqorV3aPYyz/oMS3ilItNLTAwXUlEzk6vvMiOtiQTHOpoEd8+BJqn0OL3+lfnGmEtxC8iLhmsrpiG4irEUcmW1aLXwLqUunJufXofALhgMqp3Gj2wsuVgemv+gHBOOIe7WBdOjdOUX27RXzOdusxv2dyQ/v8RnVj/lI/bfD9iovaat5Fvns5FFNkjDRrXeoHDPvLR/neGyXuCdXQA18YliJvBchy63/elNUcehVdFnaeqKaOjKTAhK56hxQNyPYoFHFSkeYu9OLP8PX7a0nxmejsf2fHZ+w8qtSQdUetmwcjw1HiCY1+vTKoUFVOSduMzRgGMaINQz+9+o/X53/tl4ZQMfdkGMMEUCguUGsrMruuKeF3QU6weTaMViXYbxSXZfkJzF0V8ZXbDrsFWu2ELX6cadWvT5fUBzlKOakqHWkoz8sJM8ogGi9ZBfsyHJh/TTCaq/+V06UtCCuNEmonoxpZYsb1nlsIST5nQj2UFBnNddLlQMR+pZSM+lrlGc/Vk+AtauumWtdUWBGEh1INM=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-dev
    type: Opaque
