---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgAtXmUAgJLo4vi6vUaqaq0G5TkltLHrborkDnEuCXv02eEaz/w5XfzadW9a/mIk4Sa+EwZDfEkC+nUH97HljwXeqaFQ3TZWqYOMwq+HL/XB7+qdO9peOrQ4e2oVn5vJt3avF6xTmeWmMgrgm6yMRZSA5f5gtZUmzU32FcmTenT9GEZ2+gZ+hvnUzi+dtrQqJe3Kr2QAkQNoF9DFKYAj0l2l7HYRSDZRr8lWiRuenRM1zYpcZYmfx3Cj19MgQYyY95BSsYPl+mLJkK1RINc5bODORVXlI55ybJKIOG15a1AvGe7lczAACtByXsUHAuIRisippXQwhSeJbeV2dIO1SzdnzY3O6T/VcdgFoyz/7yOo8tSOlTjoQU3lUGdc0yB35BP1X7tKq7ZVhoAllvLzmlpPyAGFZdnKAJ4RRjf8kwtQlipwsvznSYy/d+xMTsSlZPE53MyKQLqkDKpK1KF6f/k8rBcArf+kX/FCSxJ5nWX+15U23ljx1YytPETRATo5gQccE+U82lsLXklCXpp7Nu7HCTT8LQPGhYZxmJI+AWo69W2zZjKDvpHH14I1meA/jLpt3CQrvPeDjTR2tRjmecCucHcvoWqz/mS80KUM1sbDqj9kyreT66batEww7tcqcNqwTdoRtF4MWrF5XeIAKVZqyI0z09J77yATOsLxwVQXLJ6R/+qFCWvVAcDkwb0RTEJ6g9gphVoRiF7s2aYb9RYHvbDfs/H7+Bn5r9DLn6VXsOocaWIEl89Lh8WAp3ZZzmlCKOWf84SYJBCGZ55HL2FUuSNr+DEQpF9VeLlRX47qUOwaY5Wbo5CHTgfIM5mG20MIeQ==
    password: AgAIgcnBKJay2ofSMxNOX/nyrjl5YwdMai5f+3PfLCqYblbeV6I8N8irLNKBIHwfZ5eC5PfIEb/ELDp9dw+slukYTbxD3qdCYfYPr0o9sZpLXOZm4FQ7yRk63mtB1lnSwkGUGIBRrnKdmf3fIhqUdvZZrdRxQhYmatRUhZvTMiDViRx+i8BN3+juTspIy9lD3pIAK5BAbtpU8S++OkKGog0HUl9Fxntv4RLvTOEaT7WtGAycb5sKvQR/x8jaKNQ9yF7GgUn+xt21D+RvAfFvbhDI7/DRjhY803TgmF7YFoJRF/HUevQHWnqV3G+DNNVurjTWqimvQPoZj+O7IQuWQqOLThRFyuW1eAzlkSUfJ3q8XlzwJT21/N24S9O4Tq64JN3RR8ABARRHRAvJQdgVnByI4sas5QttUfWeDzYqrUsqjuEySP3vxvUwNFwz7jfVzuacd2XWfsSMpR+xPyQsk6y1wJS7EQeQv1C4ovAZonpP8OcBd60EQK9JYeOo/om5T2V50mfiHjij9nM3uLJpQiTYv3wZPSYC6O7mRhU9BG3Bs+jJF1YVOlbNo5rRG1VBrMhDBXL5IFMaoarsbWllTh8z5+zvNu3yxrk5p/Z1S//r89Itw3FQourtDsk2+NBR8YR56oGcNInvkIREmg4HtXUgb9VZm8qNJPk9JFGdkJzxi3GMz+K80FbrUhPqOEg7rWXqBndjW+tSIiMBldZu73Y=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-dev
    type: Opaque
