---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgC05Q7taCI2cLu/lbK3uEf56NRF3QQEBFhrxAp5wRPqB5M6jUW6TkU3WD3oolbK1QpieWex37U/fXf7OjcuvjOxq5U3UqhrjdHmkYmTLVb+tFCz4lhNpl15hMwcYXbqTIcMWTnHoIuBfMficNNbC5SgSquhW5C35Y3u2lLlq07J74oW2E1HYBE+ynpetTbE7XGhAb3OZwJoIkP50F/ZczduaHz5VG5QohRIsjq5C2CNeswvyBy0rS9hu76bRGyoZJQyz0+/IerptqkBJ9O/GcKaYeCumhUkegw6+lrivEMeheRwyN3IbvYvKU0yDGIXHUFL7yNa/262LvQlRCjJKznSXEPcgKrf6hztRfkdjkXgW9WMhwIptvv2h3aQ3yDNm8n+gKFmRysU+OnZBIObdGZpG+49/TWyopfDKywQCtyQj1UCGeCxZ0TxSjkMSY9tnmM43V+F+ZseL85cKMPFO+hwhE2836E7IagXdVoVIGR8cAshTSFjR8qQZ1Pcwv/VUwYGdiPL4EuGIT/fIcv2UlsJoVmh08NG3d3JD0Hvu71hbUTUphjcSflTRD+cv9gcvG/4LvQGb8MccPoti5JijldVnwLNCeeICoBwq5WmPMCpqxlra0dx1FTRoNOJjLXC4SPuPlZQUD2yRECYbeyzpqwvAm0QOoV7IsrMfSYx6A9TCUhwkhl4IDtuaCK1w/zMn13XGJ2BJXYed3Wtf5H9PN2IjEWR8hk1cbz8AAuHJ+Jqq4B/x2zZ0vDGu2kUyGHj3F97I7pwxGSBUceyGs2zJbsFhgmQmCeQQDjoUTtaCzPy4jOUxfZijLTK6Zg94U6tcbwYig==
    password: AgDYwzBh/XhBIQ4dlcPNNSc5AKs1J0DDG6F/IsN5qZ8cMaYYEpCmJfqtRjYcp23J+DyIHVzrIsH3LVGg8nKrrJdwE5QsPYzyh1qsfPl8El+aLwki6HEj4nsFdhUsqhhIyrFGAmk3BqiOi+Pqktp98frv7Gkrpg+QPm8U2mlMiojw1jDxNFL9VtaeXBmTu0KixoWwUbAr+V7ibTUwLVfeQ0abpgTn85D+HR2L51Wiv7lyl8RjFBSyW7HhOOaEgTk6KTyEH2DnUfhojbPA1Dpo6Y7DavL7vQ4wFLU3lgN6a6dpN071FpduYjyqiHxdWP9SP5X5cVHnqww+9flYZJn5Ro0R7xMyM9I17L2jGZXHWQrCBXkTqaSi2XQ5EZ/EArFCyb3gNGCq+CX4we2XpiiJyJGQ3DoQAWaHyxTJrPhgpWv2RpLafViStPF086rPdRrawjsqlYfYH8k39qablvWAcyHUg3GBH76jSlbG3ARSDqxrahurJ1rQz2arZyibeGsppoR+a3AbWFFLpSdZA/SRVjivAoHB51SUzPk+272cWsyF4seqsqcKU+r36ogs4+UfXKJeeS2/VGi1S4D1MhVHsZv0CK4o+/wvJKVlYk8zTIVvwjFUAUM5SaKtkGv6zQqZN3I1wJox70hc4MP7KsMoIGYW4LyPnzWL1BE4VSCs9ctheI+rbAOgiFow43OfUiFniBCuyrNH4zuTlCjYknwptfw=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-dev
    type: Opaque
