---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgA/9RLuR+6ouDrLMVGB5xXDbwNpjvTF10V8BjMEtDAHBWF2JIvSn3NkphX3swf4vVjXENIX45m72LGT7J6nNhavPvt1BhGDNCqv8xJzWx3QDMHUwGROwrGWUslqo0qFIlai/Y87+x+wV7Im6aQPcITFTWKwJgm8XhQXwuF/nBnQ6+OZLT1uX5KpFCH+NIwh4EUBIRpuEzXB8wxp+7cZCXV5Fo3A03i8FiavwwZLIarZpl5F4qdtPJenkI/1HlgYDKCXgYuJo9qaVROkghcG1379ojxSPKM5ZdmZej6Gji9Ca8r5JSbcccbZ8ks1RgyQUaE2qNMDtcrnseWkodaarzD36IdJKhAck43S2Wl2NkMTVecwJIJOjTKbCwI9VRK9lAAmmyWbLY6vihSRSg0qlDjSyOiFOAn9JhXi5nZzNeiSRCkX/xWtm0nuFDOWVfGBaT4/VPKnREKTHUVoq/GPSgJ4DWCoIO7TSYEBLhbGFcqk5+NBNdvoNQeKRwsqCOBAIadE+cVHMvtUwiUOUXtTjJK6LHZPYEjsKNI6FeehCHaa/LbChxcxB2688FCseGbhIp1v8Qx81aZBPu3dGVaM4B8Lnw4Jr5Ta1VPYiDPgO3RlZ3jrsIJtrg3etdUQ/LwnTvYLZZM//oqLmH9uNtPK3ihaIWTXcs81FWTCk02NPN++aP0ZIH+GeQIDr4qzgbCqaoviVq69hMBKrQ/KnrQLncLUZg6lDLSeY1qsly879mSiNO/DaOJG5Vcq8XODrhPOEHb+M20/i5UQBNQqgANctJGhTwiJZwCS1npEKqzvWfxJZlXgFOxOK1bge77wqs1i/gP3BQ==
    password: AgAmOpFEzcDZfd/kr+Re03aIwCC7/w+sB+DVJETD5InQuGF2qDI5gVQWLqu0x6kBJlbOnVxqlh4dv7cmOOBFjpf9HO2HK5DPA8968LVQvRYFdq2APxj2x9K/DGOed33BZxnZu96UNusNBMnK9hH3omOihe3S8lDg0tcU2vkKg0q+G0xjFuvv4VZ50B4h1C8RrXKKILKhv5Abhtu1WonkjuN/G7pH7MzkhNqSnHXLMXqpTy3JSwljFY6FbxYFw8/jX0pBhSpEc0frgmXCooUWK//uJJX1CLIjM6WpR3dnGOekZdWnctv34W9ZGIFrnGoK2/OFtQpwRKgYU2/AOE85CDWUtixlzzA1/A4L6PiOZOS+ntBv/Kao2euinIEa+i3ocQG/uguLtM224izrWpLn1BsZgvXxbbZRkWzfUN2aX90sPvEujhsqGDn5TgEP+D7RAuvbOLSjVedHdcB+wpU+p4Oxv7VRVC0DeAAr0CrWUy7lPgSjjfQpHytEE97sgpV6aw8bq/s0vWoCHuqRTi5OpaWmkJcDOuYBei3NtTbwPxxEQZmgV/26AXVq6SAHed71w27vRPdy8mJlvKw67KPNMHDcf7O5A96jw+1rGnpFldaNtHDQ+mRND7WfmDrR1DcMlEhhWSn7xN2XlEfgZifxlOcR99THOW8oBo2ZlSUPJzbfDokF1LqSovEHm/ZxQYqELB28u2EtZLYKqwI3T5+yfUc=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-dev
    type: Opaque
