---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgDZc1yW5oCNpy51BuSq86RizMWQEzj409YXi/c6gQnyLchYH9BUEWr3f+rk0JgQ2A9KJEpubIH3H6sfuDBADVGqK8XWtf/q0pUmKrmmpsQlBBxwSv5rfTrowa3gQYmgKsNMnTUzE9hjGlvq8Wt4VdXufYO3n+VSJ9eh1d2cdKQ3yzR/3GMUVnb6TsOL4HCYlwD+ldrxZy7EEpjAjDj5Xi/ElMFocHGawCTK8ztvImwZ1cqxfAmnBB2obRocGrxwF00ZeWqcxk4tmbQORg3b2geTtyf6ENGXW9IHwBMGfe33EqZhusymJjzJd6d7MuTL64pA/wMcfOKH8HTDjEqTGQ9MqWe1HIqcUPEemXamxsR02KzqurhguNE/uaFcnIrrvRnvoL9YxeBteXm0kKDSJ5oGQatxsxk+UnlhKjOY9KbScZmeQDY1QMh2oBngnyTSBL+8obqU0RsnsWU9yfdmKhC8QkEkia74QQYGNiCsupCML9Dsbzpm3ynirHP2lpwFgcYz2XbE3k5BnkSAy/MuGt2tjklGeB5zRLWdhNnESQpqqUBKefbK9iP6KQboh8taHf1fJmw3y8ZJuahJgDlf1qfUduUmMK2NJjUlB9JNn6zHgfqcm7vZ+YQ9XEikJE0vPz+rkNIcY9VxRNoOtWnhfE/g6alC3214BSHJYgENjPebJwvErZ81hgmdTSRJ+wx5zMUj6/fx2KwzE0pCD2BiuZrFGGhoLb1Af90zxaH/e7iEaHJhxoO/A+HxdZPYFoY26HnzCmsZ2W0M77v2NhhPix3prnYrU6x5GqWMHzv+yJzs7t/aqu1L69MAmGcHteagendRgA==
    password: AgBNpYjAJFLBxV6DTpKcalezdYeHHHNXZejfRHpSQELhFrhdj4uXJmJqjXtrHM1hE3uN7Cs/u4XW23wlJN13ML3QKWuOQNo+t6P7p61CdZ7uVc+jw0mckTDPYSE6aiJvjqILHg4/t+v4GlA2sKWEtsnDICBoM18VSdytyqRUB/Cpme/kKCbIau+DobJfbIRdrKNxVms00oLOWvsjm3LT+jNYZNhDkkZLkze1LozZhsf/KCEWvWZn75x1Ocep6mgn0aXr+K8HxCj1GqLmKWj21PIa/bfzzH/qdAHQOn6U/3kjX5/y0h/Pm9E5GBlq1A7yLQcoDxr7pVQEic41HDwVmLeG0kQJ7P3N8SqsH6936y+HfzFslWSJStncfUOkxE8CErhxPJptZU60CRlLmjA543357rrOi/PPqd2i4mSRTFWJmiU5MtXJie0+u2c81wSMy4ovRKLblkvqpYHSnU/X1o68rWxRK9HK7hs/HD+D//Yfq8mjtLDTgj4c5+aCgPOcdGaMpQKl+JSyK4+cY9eh5tKeXoq3s3PRUweduFIN31Zi+X5G8jh+q6svZfqI2zHHwkZO57mvtAjLeAHQhGYXI6jLP/d+eUhqQJfluNgIc8LFcmJiBuqWHMBQ7QUTFbjaYqDku2VLF78OF9xeYQSn6q0V0enUxMHFnxkFc/B3y2WizN01Zh82fl8zlB4Ifn32bP2B8n+QoTX2Wo0sO9Ql9Ww=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-dev
    type: Opaque
