---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgBnBEmAdatXpQZManb+kuT7djnTKWpXdz8ddcxtbl29m0NazAx/X8y4JjsbRK44jIdlDPiV1WVRkEXbsdzWjCfqYO956hB/E1gEBhNSy9TkivMdsvQiOchxAXQtKkP/zvjtWpXjDsDt/TQD0fjgs354rcrX2xIOar8i+gtYt+p2fvgdkOTiHRq/6ohoM1J9s56a5s4nhdlLKi03xI21fYKpPHEl3uk1Cdv6ZAjj7N7LVl4FowZzkKl03nKTKmeK428fHPhwkg1et2Cpd97egs2mBe5frYwhxi7i80FjFbz0M3kenAtDwxlJnbUMJsePrD5XKfbkgf2ozxl1je3QxUfKOxfx69vrD1dtfrct7Ge+z44ucEuRRKfPwhNHgq+BxFa+ffrKJG8zFNaZoI+ba3JuVt0TL2JPD8zQtv9EOn9AdKeV6PYhCQjki1oaYNBEQj6Avnkq+1d971CO1DLy9KLLmXyHZ/314PwBT0BOJJn8perbRj84a/uOKtkCfXcF2gv2bftn0t/9pETh5O8xPqyUlw2DxiAapwtabWa7CuZXfZ6wRkD2U7SPGRgVdcafr+jstAg5J1+zUKf987IgUPat7/4pgPMeSGqnNZ/o2YTWj1QEt7rHGLubJXuKMr9kfgjtte+nJ3gYibyQ/Dp2JarCMMr9vmeo70++KXtmQrfuRtNqx2uSNJ8I/eIu7KLy3Zwg7RDCMWDg3HLPmEA3/kNghfGCNI8ejXhgWZovOxBHg7ki9En9gs3Scvv/wqggkSErEXU/IGalp7uc7mVNhqlmI+6mTa7jF/rqNJgYDDI9AF12NcXEYfNVzTBVKT2x4LwwPA==
    password: AgBxfBfNVIzUm2NDsB8OQqNSCLtucnaGuHQGxEzuM+BMEhafoH4zIa69lR46Xie1CxwBfGp3PS90nw+GN3cg74LK5gVNiMbun7Qvf/CiHvs6q2hvM8aM1xFsUknA9LyyevM93J0AoubR6X5RpScJESX99h8W0IR1nobGU+HyhmA/7NUhU4xNkONBrWZdOTCkmaliUW/yw8pUTdSY3w5XLPuhx5/tF+x99XZMuhxH4fLqdvIu5KzHydfasGLWGvGK4IW5BgEFntshHkisQGW3JUtcZtLWnaT/3H0NiyMg+I7SA0TiPe1lHHccA6zcTSOwb22+2AR3UvW3C+jSTllkHlv1g/3NklAQdptlDouwBc7P3Qke6BBTkA0hO1e3cXKWVhtFR2ku0040oeRzy558DvijmqX4hKf+KktDrsf8CgykhNw7Ir5OW41SN76UCEBVwP3dGBqYgat0KKfECJN8LGJldybouSvm507F3pTURKtdSAjF1CCJrMSwACmAqbuBOnqmc5IYcxoTeRPm13uNiwDgGHU5sS7BiU4zh+gFw3GjDH4PZREKLlucuTG7Tguee5wqv6kdgtCsAYZANr/B280jIV4PBwo9MbbNGWa9W5/sbXrBkXfOw1ow8mY8okW2li/jVBAOW5HyRJmZc9eTZNULiv1SIephOU3eYookAT+TBHXEAR/yyOJcqHNt6E29QWBJGln6QUD7OxWRsJVSEWI=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-dev
    type: Opaque
