apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: vroom
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: vroom-warehouse
      sources:
        direct: true # dev gets Freight directly from the Warehouse
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: https://github.com/Ama2352/vroom-gitops.git
            checkout:
              - branch: main
                path: ./repo
        - uses: kustomize-set-image
          config:
            path: repo/apps/user/overlays/dev
            images:
              - image: vroom-mvp/user-service
                newName: ghcr.io/ama2352/vroom-mvp-user-service
                tag: ${{ imageFrom("ghcr.io/ama2352/vroom-mvp-user-service").Tag }}
        - uses: kustomize-set-image
          config:
            path: repo/apps/ride/overlays/dev
            images:
              - image: vroom-mvp/ride-service
                newName: ghcr.io/ama2352/vroom-mvp-ride-service
                tag: ${{ imageFrom("ghcr.io/ama2352/vroom-mvp-ride-service").Tag }}
        - uses: kustomize-set-image
          config:
            path: repo/apps/dispatch/overlays/dev
            images:
              - image: vroom-mvp/dispatch-service
                newName: ghcr.io/ama2352/vroom-mvp-dispatch-service
                tag: ${{ imageFrom("ghcr.io/ama2352/vroom-mvp-dispatch-service").Tag }}
        - uses: kustomize-set-image
          config:
            path: repo/apps/notification/overlays/dev
            images:
              - image: vroom-mvp/notification-service
                newName: ghcr.io/ama2352/vroom-mvp-notification-service
                tag: ${{ imageFrom("ghcr.io/ama2352/vroom-mvp-notification-service").Tag }}
        - uses: kustomize-set-image
          config:
            path: repo/apps/frontend/overlays/dev
            images:
              - image: vroom-mvp/frontend
                newName: ghcr.io/ama2352/vroom-mvp-frontend
                tag: ${{ imageFrom("ghcr.io/ama2352/vroom-mvp-frontend").Tag }}
        - uses: git-commit
          as: commit
          config:
            path: ./repo
            message: "chore(gitops): promote images to dev"
        - uses: git-push
          config:
            path: ./repo
        - uses: argocd-update
          config:
            apps:
              - name: vroom-dev-user
                namespace: argocd
                sources:
                  - repoURL: https://github.com/Ama2352/vroom-gitops.git
                    desiredRevision: ${{ outputs.commit.commit }}
              - name: vroom-dev-ride
                namespace: argocd
                sources:
                  - repoURL: https://github.com/Ama2352/vroom-gitops.git
                    desiredRevision: ${{ outputs.commit.commit }}
              - name: vroom-dev-dispatch
                namespace: argocd
                sources:
                  - repoURL: https://github.com/Ama2352/vroom-gitops.git
                    desiredRevision: ${{ outputs.commit.commit }}
              - name: vroom-dev-notification
                namespace: argocd
                sources:
                  - repoURL: https://github.com/Ama2352/vroom-gitops.git
                    desiredRevision: ${{ outputs.commit.commit }}
              - name: vroom-dev-frontend
                namespace: argocd
                sources:
                  - repoURL: https://github.com/Ama2352/vroom-gitops.git
                    desiredRevision: ${{ outputs.commit.commit }}
  verification:
    analysisTemplates:
      - name: prometheus-checks
    args:
      - name: target-namespace
        value: vroom-dev
      - name: stabilization-wait
        value: "60"
