apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: vroom-mvp/runbook-retriever
  newName: ghcr.io/ama2352/vroom-mvp-runbook-retriever
  newTag: v1.0.0-build.27-d2b4881b
