apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- secrets/ride-db-secrets.yaml
namespace: vroom-prod
patches:
- path: patches/resource_limits.yaml
- path: patches/replicas.yaml
labels:
- pairs:
    env: prod
images:
- name: vroom-mvp/ride-service
  newName: ama2352/vroom-mvp-ride-service
  digest: sha256:f2db7dfc7431938468807aea82ee7c5e5ee7345c8f0b7401a3032ee46a07b73f
