apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- secrets/notification-db-secrets.yaml
namespace: vroom-staging
patches:
- path: patches/resource_limits.yaml
labels:
- pairs:
    env: staging
images:
- name: vroom-mvp/notification-service
  newName: ama2352/vroom-mvp-notification-service
  digest: sha256:28f44e1d13f16583b4c0d339d6111dc6b07b2396d6a1efe14314b3c6116d8554
