apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: vroom-staging
patches:
- path: patches/resource_limits.yaml
labels:
- pairs:
    env: staging
images:
- name: vroom-mvp/notification-service
  newName: ama2352/vroom-mvp-notification-service
  digest: sha256:9ee16178a39ce48790a441d9fdf4c321f2990d5486fca6080356fb77e4c1729e
