apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: vroom-dev-auto-promotion
  namespace: vroom
spec:
  stage: dev
---
apiVersion: kargo.akuity.io/v1alpha1
kind: PromotionPolicy
metadata:
  name: vroom-staging-auto-promotion
  namespace: vroom
spec:
  stage: staging
