apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1.45
          ports:
            - containerPort: 16686 # UI
            - containerPort: 14268 # Collector
            - containerPort: 4317  # OTLP gRPC
          env:
            - name: COLLECTOR_OTLP_ENABLED
              value: "true"
            - name: QUERY_BASE_PATH
              value: "/jaeger"
          resources:
            limits:
              memory: 256Mi
            requests:
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: platform
spec:
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: collector
      port: 14268
      targetPort: 14268
    - name: otlp
      port: 4317
      targetPort: 4317
  selector:
    app: jaeger
