apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - jaeger.yaml
  - prometheus.yaml
  - prometheus-config.yaml
  - prometheus-rules.yaml
  - alertmanager.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
  - grafana-provisioning.yaml
  - grafana-dashboards.yaml
  - grafana.yaml
  - ingress.yaml
