apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - alertmanager-slack-config.yaml
  - monitoring-ingress.yaml
  - prometheus-alerts.yaml
  - kube-prometheus-stack-chart.yaml
