apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - metrics/prometheus-chart.yaml
  - metrics/alertmanager-slack-secret.yaml
  - metrics/service-monitors.yaml
  - logs/loki-chart.yaml
  - traces/tempo-chart.yaml
  - traces/tempo-ingress.yaml
