---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgCl9eOrAoKBjSgfPe8nmC8F5fUdDHxedsjtIULdr6Gt9F3Dm76kebBHg5WOs/H3CflAthmDDPbahctybETA7K8Lc4qOTxcvJe4KhGrcTIA5pRQQgJJszLRpJmk1KRuTqHEa3hFL1StZK03xfAmktFpds45dtgMiLzsVbU4v31YpC7otskqi9mh0b/74B/nQ8A/pn0CApF6ASilCfc3vU2d8Mc1HaZ1OE+XQDMgoJhjePz5KvLmjASEf4aX68AEgSCeESlcOr7bNOU8E4h2WsgCknKEKP/jHQ7V9P78FKqrXhaWbkSUrfLSnyQwkrwi7NLmApHPsnUKrKSva0+1+q5VW1ay4hVkje6K1mBCSVNefAdCzOsAdxbmYoFUD26E7JFCug4KoBSM63e+rHHBK2aT22OJDPgKsPPh4zVAnoQjK/k8OAAQzWJ2HFiI+g18rV8/tHEY/uIsweGy1JbQqeC93yp1LXRKtasJLdgzZMen31932FI9o+gxd1C1aHQDbhqZsbf6K3VRrP+U3vh8Srv0sCnqphaoCoEyN6G3dCDMemCjZgr6RzJxd+DyGrVt7ZRnG3GMiVkKX38kxlzWDj0xMk6xWbJpJRXZ+VC3KDGobjcohtIw0fAPMcdPiwiNuyZhFvje/x27o5olkayWxf9ytC1vQlTdtBnuhxrGZtLwWzFn8T3wuCPEho2WbubisyQTtN6SyvhONmbce9Nsm6XxfW/nW/MWM5z7oIgumjIj3YqcspyvWRDsbPPJ1lcBVgSPGxf6ZxvD3QXDzqEMpVvMY4WyUHicbJ50TphWG1SBwUFMRaz9dCWpdIYBlVz5SUe0nNw==
    password: AgCnTE/aM3q9CQx7BXTUZvAa6FxacSHRzZPC5q9UnxTQIYzuodYo5IfLWH8K9ThPgna5daJJ68ifN2dv6IR4WqCsr3Pp0kHlSO4YI03XkZboyq9jc05Rq/bvnDQh5T5lwWq3I+WOItHvh8BReRH0pzqCW3uQ6/kHIBigGAHHZjx07AvuBranytjEWKOv6+fSqMMQ8nKNBb3gYdF4Y6TsxCGLJJf48j1Kl7R+lDmNMNRGReQn7LbR/fhzFm8RGn6NGhLm4wIX7d4KY1PiShmU5MRC+P+thHAkPe2SDENLTmNm9/EV/Fb7yXYBWE5waYrvNCC2U0y+zPMbj+tn/ZzAU13Wke7n5oFgYzGraq82P2z2juRAVHhEnycT8+k3hMvAjo+k2ixDL3111NRnJCzKVIMP96LEKLkfX5z4XVRZB0Ixt5dS7MXTk/SVvimlLBWUEI9r5/7cT1CUwjLpWeYU/tt37BFYS4GHK9FFMyYw+IZKChMpjWxQOKoeRYBPFAZxuBCqtC2+h7S1UUJHGEqL6yrtpA8sRIX5vi/v73lWT2SacM0sgA3tdEgqen3PSnx/dIPywAQYH36PDVDmqlHyNKAvx6YbN2bmA86rTB+8a0dBLUY/OJZ+bjiaA1gyGMU7/9+eWYltmod85uiYxOt33egM9Xhar1UosiOiHsRvRO0K1sgA2fpbXSQa7CYx03uBLXgkcqedFV/IXE4RV4oaQEw=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-prod
    type: Opaque
