---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgBJnYrhf2/6kRg1DQTOnABrFy/FzRWpWfXJ3WNHalFyTkb/Kcq4ynW/QO+c1nIoXHjTAlF0Km4u3xilHJ82JJN0jl4KKVRWvh9T7XxU8MaO44AigcjYgk1g1ad7C1spobIu8IKbnO0PvSouE3kzMFJYlIrWz3iSXlm2BmQKBp5LMEjx27u1CeB5WlMLEgrRlkQgBQYWoVZkU6kHaPqEnV2zyCe7MBDv5R39t4Z9plvPcP2SxrVVHW0PHFT1XjZyfBFvpJvf3sB2e9v58mZSFVRqh0Y3/IsWm++kjekscaQaVManWQxDUH/2EHZbs0puOGLFsjZJjufqH2OqyoxpcupYlX4EVj+diLaGWyYyfblKqUUe2kFUD+nnqxm/uLFL+2GcpizGpCmuHIVVRKxuf6CfMRtU9WFJAdz9ycSaHuOwBy9/ojNtHVqov/tkmXswegF8XNRhk9wHdBQqcXTbRcIZzKFuV8NYL+j5ta8cUktGrTBzNEEiXJLOmX3WfaTXsUARnQToCv/XChkp4OFpFPe/QrDygy3gWb7ud9J9li4ti5n2C+orTpiDVp0LN0fjEKOthDcYIk/i69CUsY1UiwvGXGUI84jWasgu1JBrZ6SXDsv8DAX9MFqa7StSXrihLMcOo/MO3gh7Xv2N25eFm0wtazkf/Ix9zXWUqk6TwEA6ThAsi8pqzplXerM975vwFqEWmOo/eLuiVMnYZQ0OBjpQ0xFpeJmwl8WEAfhiNEft3XoixhjRTKyuhlNEGM03NR/i96ze7KMaKtqulcgrZ5DTQVgbh5EmZ7/OrMAdGx5dvcMn4oNi108o1z0yVrwEmV11Kw==
    password: AgAy6lUMqgg0ULHzr2TNNMr/QyB6TvN07qsUuSqMX/TzwaUQYL05ml0i19wdMbj1aMOInQTBvkAEeVownWXYm5ArIODiPC37ABxhg4Cnwsk/EVmXCPkR8FwBJYMqSyWrCTGFGjtAZX80jxLIyr9cWjPp9ROW8X1gXid7aHeTWIHy8vzehJnOtU3oh/i5Iwix24RXYl9xPtBHLt7xi41sj53TsKsiM6cns85FUHn7q3YF18MEtGBG/6SlrPmxFTnJXyb2NHk5e8GdCfvDeo6Sth8oJUO1YodI0UR90gA/5eTJDNdEZzRiplZ0yNJ1fzqkx7krcsAOgkGWqM7opYRf7RJXMy/Km6z4zM2csHASvQw/Vfc9k3ngjP31FvmLSsmDMBBeUI/Dzg+0J8Ao6Uxvs7PO6nORYaE9eIcoeCEQpmsZ8ZGxsOUUZtc7y5VZSylZrbS8YLc5jbqz0XB4PHwMmFDoDTJvBEqSJVOJKmifgHKak64aiVTZ2AWLo7Fh4KeIBbq1tlAJa4V7H4dxVtz5uDG49WBcsPZcqkyCmQp6cx9eZmUQBdT2N61B8d9u+0FEvnDx/+xUQG0UgROQ02cCLft5GKNakKkOOVLa7q7qkUtT5eteZhBBNDC2Y0T3osfTSZZ5aFVb0zinwpvknNtMQmA6F5Z4lZVp3ERkAUfo8JH7DCstcZLM3Er/gC8glCG6s+rpnYnbB53OMhCqJhlm1SI=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-staging
    type: Opaque
