---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgCwkgGriyyZIKihxFboh6rMflKr2SyqBuQu/7u8+rdIr8wx6CsNs3NxFBudoruzWo4yXZVXZxR349hXW2SaAkFs+sDmCx0xUeaXtcDI0/9NmvhE3XYOdWt8mR0W9uZ9+U6GJ9H3oUo8yFA5dNQK6tEgX6Us/ZAp/Q757HtxzxiIeMW1F2pSlsCaxOjnE9MSPnH0J9NbjNT+qc3Nmaq+va7Efdsc7If5L3JTMoEcbxL9MitatA7fMjtgmJtuYlSHsLEyEjy7e8qB80WTkhq85RLDcvwuwk9T6sqHmhi5Bnac0O7KsYTr0ma2IPFEX63LCnbWKetnmLXIW1/AsgB/1JHaRKAsQWUK2BN781x1Eh++Ah+Pg7xHL2HfcWOFK/tK7NlNCBWkX86CiAYQmF+EoiRgommKXR3+DtnqsEnAuBvo8KrUDGlqQAwJ+Up8g2uJbOdHgyNd6n32xOH+TEQ8g1TDHEBKmxb9dHaUEnvGHRxlhC9uBr7oF9VHntK4QjcV2yQCKqagawJmaonKyK16pskNg/evJdIfbsSlETEdm5zKhy89QoTwH64A1Y2l8USzrir35+5szfyFsMW6URt2wYZOCz8o4ALSBD6+8SSFjzJuiq+DzucnU+RuxHZF+MqAU6iNJms4vH6hBQKaEI6Wb4SYmcJbaxR7iLww3m04aAkhSAE/q9jfmbAOQ4t7wUGMiaXhlYZ5UngOq+MkPN4Vx6k3F4dBsX/JsromjbxtVJXaPpeSusPSCmvTkLHGqFXGhQGncdODPl9+LMrKoKU8JE6pCwESfAGIQS3g6qAwR0ujzrAXzxKv1aAVbYGxWZeisQKZJg==
    password: AgBozudwnhJbKPSeHi56Dbk6U45Kk172vAxJvei33wH65tDHLK1fH7sy6XlhCwliZpBYtUYt44W3CD7TyOBPZxoVWkt3GNWtnOI1stN5tsiQJrF/FcLHtctt0Nmhki7lfNyJRAcSzxGsFyaPA6iiqQaDKZLYpk8aPspqssHLgEB1k551hROi5TMdBqhcLCmX1oQpGmpQdmc86WbW6kP07T01U7bMBB/xzgIw+mP/+uMYE1XhTawkKx2J2LIWvVaL9L7lpp4/UH+cL9D+YdeZz+yBYcUYSlPHdH1TRxhWqrbrF+lfqeL/9qQAbi1MWMlyqQqLlF/K+IQl4sJ/mTo9jhlLISNZFvo2MG9G2GGtfvuUEvih4Fs4/V1h99/T34T/DupECSwoVvvsBEBB6AwnHPHB+qqn1+QQ9a8oTzxb0+T7aV4orBDzlXnsNK0p7v3MO8XW6K1GHgIyHE9xJS3ERmMxFqsD6XbjHLAvrd+koVUlrOlJe86geqUlXsC1kaS4sIHPorY0Lt8jbC5cUnhYiD+byEh2LDXTHqmeRDva06/JyDsPwRJUYhQkHo12/ajnNOk1Lrx19rhpwuL/hV3oCOGAJp7IU9ws+xqPU6cN0xkDl630StUE9kkYIfQAxZ9UJFUBgEiJ/1pcq+qNrkg5bC75uHVOg7V4GFnEv5i+ZjNGR/Kv2BuBwbymDaRjDlXF866fcDm+CIm6SHtlDZUXwwM=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-staging
    type: Opaque
