---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgAq1PSSB++LX8cKvkxVQ8GRfpuDno7Vg/8cne34nnoDPoQSsilpipP6qkH8IjCtGDva7UIUyXbmr0hvjgSjc2e/uL3yLy/YzNq1/5fXIbOpL+SrC8oOxRCZ8dvUeoL/zmpNhy/q5ISa2q4M5z8k3ApvlU7Jj15ZG1LLnEOiHogsJz7f+dv9MEx7AdQqPcePhy7BdOcyHwAeCqVEW7DZS4KIkevIOZGbhb63zZSMawvH75oQjGzCvIv5wFj+Tf1D82PL9nyZ3OmapSVvoM66LdBCx67UEix58AR01TBXfkq4ygYY+XjVS9UmMockPVy7t1uXpHtlC2x/wTlSrtPbGBfdfNXqFSVqrqrdbqtu5QmmQ+4PbC86NP8YcrwOd4WUboD2bFif2gDx78MHMhH6tRAROwHRriloCFNEkPvh3BvMoHSRlLT/ZLsgPLzK3Y4eS2CmciP/TvUHBLQ3b9YeORN3Tm3/AZa24dKOu+L4QsWgAhpfvZ43On5Gmakuf/lWjp7Pf2PW3UW8edYmezRL+sPOc74Dm7F+LlYl/yUKY3DUsJ2p/CXXRrWuloIUtEfunYUtwjWikXMMCBFPGsBSHD7ZHufh0yR2DUuYFZKBc9ZsPc0WzTTYP/Wd0t20pNpQEzq3TJ0Lz3Y2pJn0njqSvDSZwiKULaJsixJhctYzRFlB2MB7MDh4HKSXnukCmGX+1RNWu4J0Covr6Vq8c6a0jmpc2mqoEdw0xoIrIiOuI/YcspkbNxMU+3k0n4rSiz7Lt6VIk5UTqm6fsJUhRkYd+u6UCyyq+VveXOHrv95YtzfsR47ixcr3btnL+JZdEDtxUVxImdDohU1Xm7u77FWdn/esnh4=
    password: AgDK+X8SP767bMyTDywc9VA6tZiySGrl4rFnHQFZ4fMj7d5POyZldrtwXvxImipD9NyAp37k3OUG85sKPFZAw8GOHxGnN/1SU8wqVBi+uBJ12dsVgVRS9DAEbVaMr/ZKy6Z7Hrugnsi5jpv9Pyao0d8wERVph+pd9GLuDzrrLHJWWmAp2R7VMKU6aZUhAbP/lV+dy6curgaAhux+W8rYG6KbBfOKWoXRZsSZQp7Z7kQ1Me0L8irB2yBNAagVKElLOTY3sTUJbsDh/i4OadeX5hBUodQ5YJJbl4yU91fFLVhVi8nSlAn4RtHnj5akf8/GmQKXlfgK/8HRn3NOqoGCBE/RTAw97wYx/5Qiw79uojr9vDmaXNeIo56svEKZt/XIlrWvSJtF3ckJeTLG4QiNd2EZWDTW5UQijJcPxUiRoWyVTWVyMTO0EFHG/RZAFlapf+J0eUoRgwbXX2i7KMxOp5QSMePKKRFKdDcFL9MWibi9F8Nev2J1EYLzROUsHHvObq703lqyt3d2lwAhaK7vQT6jojQYZn+cvEioFfQcTXK/qHmk/HwEE97nSBwmcI7HacDS4+46RcuUz4Zh9hQq39Rzc5kdZ8I7XHM9dZjrjkMVNaEpyTqANSuTVNK36+G4wYhjYpq3mra+SqEOIWKmqrhrtOi/UC620yi2KvdQYk/ydPijSTKHs71eR8Q6GmOle/tkQ7QqabPuOO+N9tCHBe2kW4WqDtHobQ==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-staging
    type: Opaque
