---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgBc5svXqNsZaBA1ID6VVK4ug2pPe4ZeQ7g5gYBSHdqBcGfGieetc+tBZKbF2Id9LJuEOgbo4utTUuBdNQf+VyZ50MbYWMMAWmPS0undENTyJXHYW6pKXPbP2v22xmJuQsNUUFSKCqpueM4gOeEn3d4NMUmutn2UNJ1o8BtSJDGnZt5aGnAELOwWADjL7XzoFRjScTv3dufIvlokI7YHjJ6f412kMz+4MBQ173pAFn0Hk0e0TVnZTCzTKsj1uRDDQsCdMjhmxzcDVqFCis5xKK4zcoul7kFjn9r5TOeZIcMupoD0FM/oGr6t7rX6tUuzOwSIfO1lu1x/V+w/QGwVpOVOwfXXvCxHpFAgKcJyltfwpLKdNF8eH4Z6l9H1bd5RCLZoFYzgFqTNgOtC1TfJ3jUzX/9M8WNcXO1OVrG+3nYTLzJndhU+BGo4Kk3cTZ/3WlrnE5sw+8V0R72+RfhjG842rAzXskH0FHLd7R3Nds1RFTSGPJC5E1EW8FkQwLnaXMunF+530hvoROKXe+vWbNNG3N/E6x2zq9Azq1ODmw9ZEDyQyM77DjrMe1Ns7wHJITkjJe5Hh4xLYoIMl5SoJjCH+tOfQ/+8ttX3Qjxrb0ZVwYxcFXPXo+/CWWnu9n78+FFmqeMQFlQLfcfCghgftxJbMcuh6CJl2o5ZzUyUysQ+PAc7YE8oGY/gXqDGO1JNfxVJ0h0krJnzle4BDBR0a4yRX0+/WiHw9lAUHt1OkLJ5zINgjp89xC5I6gknrds4up5JCIZsSKmnCYrm3zAfqBg16RSTPSZEkGe48DcnDovJbtNFvezrwZqrxK6X2eEiFPC2/CZN6BLqp3887Lioq/wjWyI=
    password: AgB2BdCTO1+4kBYdabShOEzJkG2qftchiSEvgkK39kvIzeG0RyUkBJyp/KD7/6bJgc7srUc4ChSyRlrXrMlrVis563hb5saxKkXi8PILgBQOKV0+8DbAuVOQ9JoDPoBd8/XN9txkE8FSF7RvfEEKQXWBcSuKuqBKt2EYeUQJ9sq058IuywMQbewzgjpOl5gf/mKUKdbmepTvpDFtdPnR/A9pLn7PRHugMhhLyF8N1+ThIeT1xedHpRAUrf1JtF/vPHrRIyP3hbuw+QR8W1m6xtoY17u774vRkTS7nUvbB9GXKFmM/Tw5YDKvqYUIynIla9IHEu3Aqyzq90xvzjHOiFqvNDlxYdaZb9DZQ1xNVcCBxZ3IEcPkwf6B9unOZ/eqgXELnja6xXG1SyObu6oyrX6piMO5kU/TA0AcPu/cnxgLM+CulvcQWtxAFipz9mqlWUcWcvHcZeQ6H+EUtBUdWHbC4m3CiZqzoWXPlSFKxbwDpS02aZ5rzUwiNerCqdnpUyK2XE319ZVI7mf70x14Dxcr2P/KsolYi3lm6UPu/9DO3gyZdEEPtDOlkfJxA38UlmjgJ4TYDzmZGDCPrIi7WDKB67Nkv8MX+ML3+hDhaYBWt4HY41nYcuqce/5epqvb6OCjMYK/38QYhCNbFPijibqWX+pJa7ex1exAoxZkFGwiyMn+wNkyhGbJWZeB1035M1D1foJieN8uMVfCYm1ZE2BziHYhlzBQ/g==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-staging
    type: Opaque
