---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgAJiofgyY5dzn/3qwAvBVWKVLy5f5DfTATSDcmSlZtFBKF8qCJyQ0t6NqoR1y+SXl/gLCpazzpZlzlzjneCzzrfCAMEpPEOlqM40J7zYhq8K6x7sjFSFKLp0q6sqoeSMHUIwX0qbPSs7qCRB7+Pz+6EdtzWFBKBJr+O6YTBpODJXPFlEp0Dmh5UHI7D4TJaYOnJdpzGHWnSLHj3CGFGlzQ9mmZvZCtrr+M1JytPteAm29dFUtqodyiTO9ikEbIrn3ZY0WZhCMjjiZIoZ9Wk0cSrqF1ylYKsFcw+n0V+68CDgx5lZobwYEQXZyY7SyRw3Uo/Unk6ezONB4B8CBCwg2aie3gVbFkj1cV5AO8V/ihCyZJPU9zDOyC//63ssyEVdjeSoEKSQqU4Jm0lHcI4FzeHgxSPI4epgMaL8NQEwncD7ZVN0i12lzKK9x9X1WRQ4suQMHg26Q6ISn+VtjL5/97GbfmArXfRoG23YxJli734uxuWbyfqmvlET1a2fjuzV2lHL7RfEq16YH2AaL6Esj1XFgUUpSlcrvUauVDcHpdhX2hPKD3xj1pL7l5zld5siIJVVV1ke0GFvIbP0JtY+hkGC555LxqGcNcJOo3wYlu/WTP6TR214Ug5q98+d4YZhtULx+38rM4Nc63ZPeWRhsVTUCXkFXjRHg+TVZtZAD6xK9Ivp6CxvBlSM9HGxuYCxbWDRPEfOa4Erx5E0MNgKV7WbDB06gHTnj1l+jQ6Rc1YD2P9tHhh7WNJ4m7cgD4m3avA5ELCIFaIvrKFaluDHLvyD14zL9IwzRu76POYHELuibSwv6hVD08F8yhG42LTqWZMW3wKXicjJZPzGlaLluAFBg4=
    password: AgBXAxKRCZQLj+jfTaRYszL6agTC2l28Bcr18rHPkfbihaxIIV8dJt5fTE4N2oQpzYvyMiAvwJlrT5jteTQYeSQm26bjSbzR3AhAZuxlyxnh7RxGDICfiyMqvfKmhdyvuVHEp98u0ry+FM/q0yMsgZ3HG3Q2dzbV/wzPf/By4MRcX/rQu7KV4BowXz554G4zYrNgRPMHnBc67BqCVFkK17g7vYLQE/JTUV08vyLz9IcwVumrrydawiLLbhiM3yfMySfATrfQmhDjkcYk921rORyZdeHc9fAImLKSXAgFDqQrl8MaQsFdKZNG6gu6KIGPFRVrVxY6hbVDwHAU5YfgJfFgXgph5V+fgIi6+xbg/iG2oijBniK7AN9vTB4iwogeybzoJU7sWRl74bFdG8f+wY5i2rXxOx1AUTZWJmXN/blPQjCfkZeJbhj1EI7nzyjJf/dI0xuPfY6dYX6+5hRrVjfjRDzBzs7ZNEVWtxp1qwoVNbzEf0QmDXRCsSTkw6IHqlPHkCMxM20rQ/kC1PhcJJ/PmzSZyAi9hCogab5LEGbEb6pr/53ZtFkilriREoGbk/dp+F9WRBl2KLK5pXplOD70+v8Awa2PnbYX+0s8viaolGTXYZeUKQCljrEX+XDJHvpqGRz2cMvb16I+jx4PzObF4ysmIRrYKGLbGrjnuspFSA/Y+cpQU8q4ZEjnh/xn1YRsFHfjfG06zz/VIRqNZ2Y07yFyR7Be/w==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-staging
    type: Opaque
