---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgA8Bz9zObMAupl7a++Ob/3VoCUUezCoKkQMhtNMZ1ApCjBRPS1evqy7/uz42cr6GlVzCUhY0tOEU7ZKHpFFGpYOQ/zFuGVlQbj7hNqPrgMI/I3KIzm/uHbPhxd7BZK8MzIENkzEECYL9YFbUOxx3GHtfE4mMg1evil43dOXvJFKkKsxSen+YtYlTGmNZ5PSeEpG+asELw7UlmUUXWSI0NHALHsOGPyJDMEozAscjhwPDqTKDAti9OyEVPXHFtdKBtYUgPju3JrTiPNzOP5TJ71ywWlgOPFXmrGzuJ6eIx09ND+cOumcsbMmRgMxe9NHS296qiHr1SxhOwG1w2Ub1svux4beHeDl2ztpNE2kCj1p5R/2u0eb/SttbWDFCF8cvUSX4v7GRjSm01tsa8dABVpidn2o+POn2/q6TknkTRWfMHZt71eVl7tfE2QOC0Eo1IgP3Y66/JuXJ6h2p/F/W0CCXGzpSXEdfuW+v70rQtq7cCvxpBTrYdDj3k7EgBLzK+1/SHNGyCVcj4GqADQkL4r40StsgYM4oecYrjcsQJXpC6NXn8KagZb7M+CjyUVd4gD06Q7i12ydV4EdALhZPZ7T+4EaKJ64F/4t4j8cKn/f39tabBK5Hft93hN2Y88v/xBHsM+BEqoGPTIydrQRt2McRVz1LnzXUepSMF6A2To6CRFFz+FUzaqpLQWyrmDJEVSajsqkRaT+XkHJQkbnr3b+UxyptsN5LF+8KXGLi3aK+6dXsqzYOXKIi3rAylMEh6z0P96yXmBoMX9bd0zSPVVdY3qR+/GliW6sYWfslTRaL/HkXZ/k1ZSP4RZFKnCl+6eSRQ==
    password: AgB38ackA5Ghrfc0/Q7NUIzLWVpmqyV4TsO1NpaZJAQv8hU7soBswq4udfP50IoxBbj6WJimVH8nAOltIu/YQuFA2/4GFSM1M30pYuocGOHBJSpHrPvLw5ovnQkdKsEN4DHVIfJB1crUz8/IAypIayuQ/rQho2tReLIvL23+I3/jy3M9Qyp8KjxsaY6ki6dPnNVuwoDTtEA9F5rHPjhBo2fW1QdkpcTz7d5u9jj28FU6uwHRZpp4WX+g/s+pKm9Hr4DwCI4jJltp5DVzx+eUfkc1O2B98tkXA7lRZx4aVZ/HmzWkYjwmUOYrRXvT8GDXPCr0mCLKceZAiJmMcaiNYGbiFEeZ8eV955bc8G8rIk3NMJ8uhyoyWgw1z9R4/KtDWI5uNFtRlLwKbkLmLK0r9JLPIRqXNyrPDldy53Wv0L+XWoNySIyf1feYXZ450V6fa0R4XE5XsEipiKMIwwc02/cppeayAj++d7cUX79dZD/m2eafFPg300y9zD0XP3nUKZGMmbyJ3BU9MPKm9yD9B205+moyuHp514Onn1wn3xxMCefikvSfk96qeMR9K18mCs4pIRLCXVZI2/dWQD10yrRZPiAJhwxENQgnBuL/xhUypZSOAqyOBH6ncPCO89hGWRz7r3yxv3VmvzcJ0n5Vb9hzIR8bgWZhmWA0YpBfYhCKL3QsW4qUhjCQKkKPQ2CI57FabFCyoAC+cKvfYw7brCQ=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-staging
    type: Opaque
