---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgBtva62wPKe3q0YIn3D/pSSC6DE0p5Au8K4j6HtKF0RBEjPuo5U+kkznGJ81DPdzXwvR+eM4r3j1F/6ibzX8z/YL/b8Uq7qEo6h7hBjiouNMMMbcteqbebTuDATPPayTud9Nkae3Oly0FCWgIdy6hidv3n5yhhUWJXvvqDt9wXQLnWa8l4yekGRlIkbeZ3lUkX9WZL4nty8+lDIILpNlsuhIbUM91BbzMcE5hA/OP+Cb+lgxmZCbTMgoI7C9kAM4ZXgcIJFbmG5MR+MfAxtyi8udDbXIyrnOusYnTrJ5giTA9tbLq8rDdiBsyzR68ldOtkKnLaK1e76trGsJywBXqqY40mP0kSguIkP8T7zYnvL9GDGriMh9AlhmggCFHYCUlNG2gCNGvk2+6dIMN/HVmPJUoHJ8s9P+A5itWaSPOdOh+twgJpnUga4CZSaIHxKy2+zM1i6o5eOJQ4QrSMbKCQdgI0GKZKPW6m2Fovv5jdOyLA/BZoe2mcRbqtXeKaUQddJ1simGfs4pF0NMNHCYCyuKrAlVDDLHA0DbyeD7xiZM5yl2HWQ6NGV5q0J9Lf2ju8APfMpu6kz+7roThcnxVC/O4k2/HIQErrFbshCIb3/MYRH8j8znRKuVFdiTaBRXzSW3FKGPnXvdhchGZt9pFFDokKqZKpZEw6qc0Cjxe+SvfxYvuEX/sVrajqTgnXWFgYDzBBRNJe1Vy/2lAzzw+vgFW1f8GbknJkp76i/MD1dmaor3QfeueoJf3dSSUlmFo64Scx+jzxPPhijCPxGwDAqrwY0uXykRAlSBaSjhdouCGSwuS8135hJRgcJk1Y0KU3rlA==
    password: AgCZSthuE+3H6SIC0McnhK/1eJ7B6d3rWXCkCmpg7HpV9d9qsHjPZ9QYdYhQ/iUYv9tebKG9fVAlG/wEvUS593FQP9swd+waxCkMihOrt8cx5PBPeb8FHkER9sTwaIYJom4Vuq1EibQGGKzfUzVzEWhlBHtwAB2I9F6gYnmaxZHbeFT/C6LVU9vTXbEBipSgWNsxSpTv/xuyN49mxOGAQhc36OpHjmke397W29K/NrOVmm06BJU3ozo88QzyGOUf0DtBGk8U0ZwbuqT7EK2BrGoYYz3bt3nfCWwTSOA4nr5+I1BNFekjOXOJY53pAvu8EaJKetfP4EHNY90wlt3sWOcWmWifh/DDENGgICcOZPEEAkoMj8CYcRuitb/r/Ty31ZF5was346qMREBf8CzLPNXU5T806f5FmzjkKOL2s7qzVLJdfHX9AQSoXCv7qmWntCqI57IJONpbYLeEalc3Y2s9UtNT7mAitH04rWh2TCRAuQSL/VdXQHGpeL4olnLWDz6VWKKamMvl7JvY3zNtBmcbY8h7qe5Z6pagtjzcSkhdv/tw463H/x6r08oLmRZnYV9tBs+bkuvURGgCwcgdKAbKGGpFpaCpXxAvONoPuVeXNaPV1W3jOZuly4ci1Txd5aE3qxuecNy1lzgHsXAbb1tu/wgDylTmxgUnjODMO+gIvK5u9OYkSBNXrei+9S1G4LMbQ4uRY0MOU55AR+sU1rk=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-staging
    type: Opaque
