---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgAzFItmRQujE6A8peaSAbm+hAHjY+svMynmixbvuqqTOVWX4e9ejGPlyuc19y8uwxdpDFwbNuHg2pWqsDETctdrko7a8MXg6Np4BvIHQYfvT5ZzXA2fbWrxW1KYJLuYrZkRHVg4tLvQuS8IMr3y0nJ3Mad4zPZ+VjitPez1f0Q47EYeJdpNnVPNuNJOuqD7tfyXeuIeSDdlvMusiyVrhsNzwLoTp2GpvuNiGYGhRESbvknqra1tdpi0KA7HF322riZq7sSCveoLrRCn/ZOP80XJ/nanI1kaRxG4tqxlUryrqtmLiVfb0Xv+0eAnNQELsnuwoFP+yZ2uc77eOzv9gTcanPhZ9OgkPm4tA36V+itwbNvAuIO67g5sOFn6vJRWoC0lIBYZRklCkCXGvrvYW6jDccHFdfYU/5cX/+mxj7B3K1unxQVTB4xliER62WYuV+FwEELR7rROAqFpaaJ77I6qpoobkW6DAp3poq3NR2bIW5K3zrJrpa/9vEBYBlWslzA0qQ2lGSmSuoOUDJIOGBsvQrQi395sUSg3lpq07AuINf6RLddRCe8U3mrt7uItAVE192eXG4RDgVZBxsi4SPYPPdi5s10tPurkpHulxuakgLUevQuwp+PQJLQL4E+RW78iAA3H4XcduV0rz25y0r4XrjSTrmej9WD4PKDGvwgNEFB30zUDi/KAm4+fprBJXiBTwgg1plqluBbIg/GcKjI9Madby5uG4PjpdEixslB9ho/aQgI9vQsYfBcrzySQWWq9PKHv2ovqBIo2gSPbTtF1I+LtruNcwx8S2q2nDZMj1DR4SSRYYfK8ewQ3iosRlncqfA==
    password: AgCL88wmlcfSJ6d+8+AVIqYcn0CCm4iwgHznCJR7qapvHPWfakDdBqT2QaIVVmDk7ZhDEiG1AxHFEt4hPePFattGUWfncf+orI0pIWbls+Du4yAyB5qppfMFoGXato9dcqdzKfqRlWc5X5ov2Mg0u/ldvvgAPM0xgcqsAkIz5cvgBDhmLYFpRaybmaGwlWYMzyJsUTN8SC77LFgZQzWLrrh814AC0KBWJPU0qVYic/nhWWONVTFzLWDCBKDCj9KIx2K0vECW1C0JW5XN9NORFJlG/9NVjQd6BNBZc+S7XmB80mOCs38RjF48exgiiD7lIgk50hYfRw22QyxZT7ox1idZGmrZKOpCf1v4wJKwI/xrsOQTRcrkde57vOOPtSRVwZJyNqOsh+s1EKRAhOdmZ4SNfYA8zjYx9t+BzJposdCv+7BXXU5bCos0+RcH31DfmU96BnzWxHK6r0CP6xfh5VbqaJkN6G6e0TBqofdOX5o8UmIh81WK/9WqHO2qE3ij88Th7Qh4J/+HTVObUa9t7i+NXU0PZJRj7zSdCFv93UXrWE25f1HCJL5fdbOptY1xRvt5oLv3/FtpnFCys5YyRFKkGLtzN1jA/reRHsAb6dqOLM+6kpRsLGB9vE58LB8yHO8ZfJLiu0JpgxundkVVo6okMAtX3bd0n5Cpb+ixgGkjBXB851cDz+sH3aCtTMHD33hB4xrh0BNeB0Jh4UtoPJg=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-staging
    type: Opaque
