---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgCF5QHd2aDuWriny5z2F943Iqwb+E/HZW4LSUq52r7gyV1Ucx5Fo4RQM8g4+FQ/gNJwmLD+1edspNtkPpaX3Z9kt82oKi7BKeSAs9VWJc8ndKfrdABZcxFHarhWFZi+4T4UeROo1CM0Hm+HWLvj3nMTngKFtibTpxrmXKD4vJQJGadfi6s78kHnf/K0hiBHYcnvrPOZFfCUcMVCoFqOvzfXVmWK86kGZhrc9ci7OI52zhZLII4YhSl6Druqb/jM3FF4Wqq0OcMyFLvMhbRTMvqI9ubCEm0BunuTHvbrkl70ZeWwINZw3OSkR5CBZaIIydCkxmhVkSxakf/gL1mZwdps2hO8tNtiYWayt4UbKtbghb2tKeWIKKflU8TDj5mQvuZ2+u4TO5HLwCvaf+VYLPjQJPAPaBeiR4iB2gLrH0FnlX0LWK797zwZQHlF60sv1spa1q6LdafyRioC8+/oVwHif4DskIvpCCsZ5bTUYiKX9Y6Dn5kh3i0vQT0Pc8yO5Hkf5LjkQCrlh04Y0xytFVdVVUnmIomDxOwi/rT4+d1BTXl40XVHc6qzmfDJakjcnGgIHcs/E2fhraoSmgaZvB5ZLn6kVULPAR8ZjeybD4u9CK0tVKogRLaoD7soSnE1GYhRnvNWomNPmeCamQKf6XwN8eoFRV2K5LGUSNREB4Zpv5AzxKuzx8uTyzyC4vFhHFWKCArwbQjGLtEJ3AKbj5mwHnwvoE0AhPZmDLTWuF5mGiYAgf+a3DxWqqjsX7j8OUoHs5qWIPDofvnCSWEXrWEWOwhKzGCIXhtQTm82oTYNSSD0jBdB/kPeUxXyhebrNw653g==
    password: AgAgpan2mpwGu3oN0L7iCln3ORzENZXLNsIBiVsiRW11HMn8aYj9lzyFvarBV70wyeJohNkvpJ92OKMbbMzDuvmfWxL7KvgHlMZTiIJI1X5FjEX4mfyQ70M3y/M2Eb7qynfiSwj5z/sywrppPl652QKclTEXE4zJatTIqns1oIottKyg0tMfpq4T1IGqIzft0bFK26Y9JWMt0Av7gUUA0QsLuDDabRraD+7HJmEaARrf41AVljUOnLOK1YOAZQvLpIg/I6LbDvTZifc1OSHU3xtf13uRwtSz9ZQWZ1e58IayEV1pPzV7WRKhMFUCnIoQD8wuzTzlzSTve+Bw9spx8ed+AbtjoC/NA1XZyw0DQqCMR/wKOeQQw1BizyxMoWtV7tn/KehIIZvk28ZP1qRmer+iDbig5oQdGY5GUMJLMT61UtWjFZfbGJTtKPkMcByEWhTBly5rfgjfhcilU/8fEcWg83vNifIrvRletp49qpFlF048/sk8bMZdIi1Mw+lzuX8YWzFqwFIRWTOUHwPwCrxKYtHV4+0wA0JckRUZWXYAlqH0nYF8hX1uZkvlBANwJDdu2d6zcpNxGeVBU2/AtkTHeq6KWYWmGbsM6u2nF8ay/Pflve9/6A567qbnzmrwBFYKiaCpFqcpdGkjcGsSLWZ3/cCx2OwO1wXhUhVvnp59nLBMjU82fnyTDzcqGM2cfeXTcfxibg7oDL8UqO59D9o=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-staging
    type: Opaque
