---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgB8KxQpvmp0hWTGm4i4rQypiioC5lMCNoOeqtTJBdV0aIdxaVsNhZPG/jSrYJArmpzg/Y0Zy4La70EqUaY65Iif2Sf7GcbFX5G8rIWOlEolCV6df0i83kS90PaLPs1H2A9brS/XwYnO2+X9phcA6/miFHN+g7oVq7vcBSvx1BdgLhek3i7umXf8LSHi6D5GNIuFnXUpwz5ne41CGq0ifptfG/top1L6DU6a56Osb/sNcM6Vg3ETqhWRHPqwi/YfEa3VwLc1EfkXfQ8lDRukOihvNNDi/VdVSh6zobqIp8SaHjU1HfudLVGoj95Q7O2Td7Xbb/R3ouEntl6dchoPm96idHIP5TcCWJfOe0K1VAFpSbesmu/QJwMgad4dcSArGz/S2kHqOG5JPG+Qr42bgwyPIR1Wo95y9nlRgu4MyjnQrhv/sD62LWohTQhwy9gBC4NCot6ABQYaHyolUFN5+CisCtevLafErOvI1kR4UV5pwxgfbdMmc4BDD/8By2qNPPciiOCcO++TdnnI6B/GXKoOneFsS9PJjl6mvUB/x6InRbPXiPTdk64gasrdHPOkA77P3PRUJL1ox8Rr4aef/W/sYIibCB6lYOqYmxxQmCfhKAporAPtgTVyjRPPtHyZbmIaVDwR7HZjxJeLe9/ugxIFQYp+7jqMibYeZjFV50+Sogjjo1FecVP2MhjdXJwmNNpNhpJb3GjcBWk4xn5haEqTF6MXaRBQP7HcyAImjN7OqrcVWrcCyNdFlz8YAK86sSYcTv2kn8dcE98c91Jl20h+CBdidCFqY8d6cJreescsWEq1jyBMFJxkRQFynDUZceD0GA==
    password: AgBpvv5c7NiemCYYOwHF3+/sTuQR+MlDjyeq/5X3iGaakJGsYO3y36mHNZqOzIKvkct3b5Oa6j2w0cNK4evC0W+p+pcz94qCvBp7lvdpQoltQ6yYbap8HGo5vapNqhN3EQu6pTbIirrr0ng5nvQ/1qcXZ727ckn9r7K9j1mNia6VdTN4DZPHqY3hET59E272GTanYyqqulJ1yxh+103dewDc6VSjJDocPwv05CaAsawm/Ldui29XSARf+lUBYUrOQ2J6l/TsvUUukwN4qsY6/7YtNPMeW/VxZjmJdb3X3vBxWOZnEycPuvv3l2Qlu59ltfRtM5P6uytkWAiktBHBFWhu/fpKN/b2w36YXZ0QN5r2a2OXtvSr2MAlWVoxWwv4P8MYKpGudmecD5syEYf4ZEbSGdkEEje5BjcYGPlgjdgc0B3iM04khD+mPZ6058FRrroFAQf8bOM6Vcg2rzZHvdyCRrMaSuLvJ7eWevwScrSBZooljrNUlQZcxOLZPDnDZXPsFkpAsNfS/ouUZ59eXewugmXNy4c88BpQViXdBDeQs4Okv5b979VkqZLM2zpDB62Q3qPTjRhtZPgvmix6HIPKOeQFjsujNUZVVj935ofTjEpFw3TCN3vbc6fYirkIGy1sAV4y3QFfrt6TrVuthXvav1cYTVNzbwvw7gqdIlhCcPm8NJwK8aLx9GytlCO0rzMBo/Vd3YRv9Xi3Hl/tQEg=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-staging
    type: Opaque
