---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgABV/2DOg9NIO6iVUTNRmJb6zLxK3WuLAUOUSBtjKOQisDSDWnsFgvFQDCxBuShT4R/4hrqfXtWGndpZm2R+KEmHyjgwIAbicO/TiPO9fry/J4oSuYtYkloza7KVpOWTXo0VcLKO5Ppg9AZfAlmfgKA7qyiek5+kvQOspeyFTjyZ58lx5FnS1ImBOxoLVJ97gBHRoAJpqBrTqz3p4SLXmw6inK7iYHrSw/DXeIBPfSt92Co0PCwNlzJv03YEhQWWrKnjBkuIMAlYABlw1wrvDwIxJP3d893EfmGoAUeah7o/s39PIz1TzIVuSX6athAUaLdZtRA3CSE7zkXGsbNq6jg4B0H87soPwrQFkm10MmHJg3mw2Wx/wJabNndrnWEGpR4s/BAfN/MBSNExX8rW4LHwEgQB+KRezif080Mptakw1wTPjNsvEc/pM0puiszPYMD1CP+xoFwxm3+0RO3LRnZlgrNSXMxg6e+spWY/d6OW9otS0tDb4v/uA1hMWfCHA9K6Z18hcPQ6/ka+/p+x7KKIm3hUPT630YLYkv8HYrW1FYs/P0R7Y5eD/GIt2eDmIROqKhp8z6IYrq0dWU3jeKjaE3/I13hqQ6IyLA04Goenh+3CApaVGytk2o44cjx/SAtF8gWfDKm+jfsFyE8lR0yJXZESV/Cs3iMdyScc9QH0nYHQIlT2xDf8Qj8fjbUL7oAKniVxsDdF/bwCOF47XVTdJ8nLjC7ecXqHc+75OZvcfTOkiezQ2AuRjBIlBRUYXj7ISZv/Jr2kwzkMWOFnhb6dWQ9O7wKi7hA+SEe9SzzBXF7flgzaGz0UppMyq9kUfmzLA==
    password: AgBjNBeR+UiWLTvapB2VwQeRaBO7PPGFoE1qhtZI0Sg9+2VXHHgngVxIuao0vXOWmxRgtz/6UTNOGjhE2xwkl61hnvBPdoP1XBzxWmVdGsiNmvVovTogRoXMGtWVc+E/43Ka93RPn6ii8EaC+VbU0VAHj+mASbEDRvSHDT8ctmV0jMNDTN9yTqL537skSBKBoZA5hLEjZRY8BbaJpSrjCNg7K37kNu6ZdvJhUS43AKMIJdkyRHKN5vfrLMSoLVSu0EATau5H4SeDLFN0DpSxbE1wwYbY6WsAjSgpVLoMruUbqIexMaA1YnqB8P11f/5BmeCrk2sFjz0rqQRFuuqzvngj23icKDE2WzqtWECPg9iudTW3HGuZKWakOylQRl9pIvy6X6MjQpG/SBaB/2g8rBUthJc7tVxytTqW0WmAdXjLjZ45BVpve0E/FMyjtkqCBqucksTMqQHkMuQWmjmL5jJrgIQVu+IjacWqSLkNAnSfS8npyETELVJGU42zVq+0HXWz6igWn8rdvm/wW5MkPORnDn2E5l2zi0ZFTIBHSuR5cH+zCf0bN9pYBNl4MxuPczRfCC1X4gYAXYshTIptx09MXaWybgZE4waSSqFWpGgkYdp3XDS5zWR6VjW60YR+Psh1SRWcRc8EjheUttLc5J2ModTjumdJs8aEbkEzCEoIos0vcpZi0mzp3GqbXg56CeVteWTxKW4M4zrqE4P19Is=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-staging
    type: Opaque
