apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
images:
- name: vroom-mvp/incident-agent
  newName: ghcr.io/ama2352/vroom-mvp-incident-agent
  newTag: v1.0.0-build.59-b8f5f1ff
