---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-pull-secret
  namespace: monitoring
spec:
  encryptedData:
    .dockerconfigjson: AgB/Itroq4EgOYo/mFOBC3fG4CTd8WG3A0HzUoAAJ7/fETOs+ylBMW2ohFMqJzcyVCK/gxeBh5/c2ZmMAbzqXFtLM6fXJgHe+p1au5wZRU8PziNUeyfLn1Bp9Z5qwAM6htdrPh7K7+a3NnHyr7riimgc0dIm6K1efD++UXTENtGH72PM372MKptii+/ZOb049+fzPpbSfArtZlLM7mJbmsdYU+afvkV5aF59AP8/wk7FpasRp40W6iUIl2y9Wks0+f6WnGyafBaIjSklLd54kc7CcpgSjQgv0wWNLUvViSwwAceRmq3yu0ZSr2gsay3hXBV38b4OjeX53U4irDrfsJFjf3DYO136J0K+Rg6opJWxwa/V4lOBk8gjFi3R40YroABG1+6LaAJL+LI6VycLUzd4sIbgc/MCUAdGCAo6zO1XE/Fcs+4wTZ4VwKyxT7dTWVyqV/DtObh3MC3/v4th+EywrMwMU058x9bCjwRQOGmf6tc5pud/q8x1V1/wUTaZssEVJLpiCg/7bliP2QoTSp6tnv2/CgxpMGvJDPHWlD+TxGi0/hPuv/sF4VBVKJscYJ0UIiS1g3IHRJfsGbe9pXgqqpkGbFDmUJr0X1PmcdURh1/qce3QHwnFkZ8wKFZflQljJg4xvTF+AJIOQykwrkqcGt9F1QmNyp6mzrhZKXwzYQQNZsm6XC/VcfwkjN8m8d8uFG/2ZFrZ9qmcgrd7kKP13N06aXZTXbX1lt8ylddJZvWrPvNOYrmPiY7JxygZlvcAGVUJNnSApBEOdkcYyxgbHj8vilymOtvuO+dxtHrI+WA1roUck40p5qiUsy+t87rrGF/qgt/FgpXS4sA6HrcjfSgv9HCN9sYDkvjSkejYqSal0YS2MMnZqM+TBTYftIuuSTSKUODlRtn4H5KVw4kCw0ldJtHzsZYY1GLwp1NWLDmQahDXZ1/lXL1nXT40pWEmt5o8nm/zLRGMai1bygK0zfl9w7GvKwV8OS8/clkhukit2Ds=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-pull-secret
      namespace: monitoring
    type: kubernetes.io/dockerconfigjson
