apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vroom-staging
resources:
- ../../base
- ingress.yaml
labels:
- pairs:
    env: staging
images:
- name: vroom-mvp/frontend
  newName: ghcr.io/ama2352/vroom-mvp-frontend
  newTag: v1.0.0-build.37-fb71da81
