apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: vroom-staging
patches:
- path: patches/resource_limits.yaml
labels:
- pairs:
    env: staging
images:
- name: vroom-mvp/dispatch-service
  newName: ama2352/vroom-mvp-dispatch-service
  digest: sha256:9031fed4eb512878f16a1cb0026bd26751f4ce06e9c0f38a7c2d81ecb7014bfe
