apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: vroom-staging
patches:
- path: patches/resource_limits.yaml
labels:
- pairs:
    env: staging
images:
- name: vroom-mvp/dispatch-service
  newName: ama2352/vroom-mvp-dispatch-service
  digest: sha256:cb364a24eb2b4f96d14403c4c4b4d10dfef36436b5c59c9524fdd2908e859c4f
