---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgCMlsxgrLpbEjIy2f00+wMR+6hXSuGJ11MRog3a1IHMqZkPYCUwQdAikH2+JE80od4ZJ5kfzR+Bl04FE0wOZbzypq2ojbkBOLuwWVMQ8rwJLbq0/nX0njEZeTK4VSCDVQD7OqCcepSb/6ex93pYqLip9/zEW+7CkVhGsBlOO1lFx66Jjob/nv//WxFUynpHgIt+1uUlefJ0J6r1S80Mhn5x3KihH8NQBBBJAaNhrA4LGbeiOIPd/yZS4PIYw40NlcNeHbsRKAxH7NJeOnjW/hIlYANJj8K56iY5hA1tXxmtwlwA3AEZbNXBz6amWft3Q4wQO5JYbfmma2U5kWRW1kHHbZs/9NcSYylf//7lu9J0ovy4DdetB1O2itQ64N+38NKPxO1hqYceEC492EgYuS1scfeC7Oaz2t2H8i6BwPn4cNvGjpcLzj9WLDhoZZsn9wqJUD8rwIDONlwt80/ggrGM2wjc3wlGj0ZjRDeB8gs7yJbpbV8Chc9X4+GwhOAt0pYnRJTifuJGyE7RfxBMQL2viuzF1r3rc6IiKDSh9Aj0JDrSwFYrJZg4bIqdVFl4POX/3R426gthNaMMpoy+v+ZYCdMv4WBZaVI8ZplUQmI6utjw0+rkaPi3cg/U4yGbdk8Ll6IF8ndeKu46pbv9Ji88rN7p9EQN0ff4affrjHwl8ucG2/+a3W5cXDnHk5MEekj6P7CtdxU972kIz5H4v2NyoGwSJIfwZr6+prxohHWiw1CTJSvSWVI8JTbcho3e96TM4Id9rw5L1PPlgtLvtrKDP0JtGnvILPGf5aqMNYyrpfAp5YQiJw+rjmLfFMw5+q58WMoAhQcq0uWY2LBAtm6IH/Y=
    password: AgCZvoteoFCYPTWysAj6IYi1W8Mum5W/Zwl4x1WWzyJVekxNX/5jlzF3w0k/RJxVbIXposDM08WOhdq5UrfYnZpf4vuH9ZUc1wsPEycuNdhertzmL3c7iWjWUaLX9HoE0bgxkk51eFUlasxOg+k71kTTDyUwfhientkUWu0dz8uBQ0ZeEbW6lZ9WFvrQ9LmYiIk2AUITtGSwaBHMc7eomCgKOmXzMVrAHDTv0e6RkQpyYK/vEQOuf6JxTagqi/Hrw1jMJRLSfm91k3BuSxTiHEEEhnWUzrP0SerhYrbWetURmYN/hKb6qSytX7mK69OH8FtgFSIhLxhwois6bRKopbz/JrVvOrIwGDseRScfJlJSMhixMjPX75mhgz9odbhfLD4tMTOnu7S+dvclARt6WP1arj//Pho7ijlqKtaC/hFLGRY6FKdSgs0JNblYxpyvAYR46gyM4+KzruTQnpMZ31ywmpjgdV1ZbmHf0rZ0l8AmJ8k+gVOsx3NoePE6KW2p/uyDHIPdr0YgmCI5fzaNsnFfNXdgA+ra+5Use4O/ptxBxWm5l+InULqsHlJTwNGTxiZn56yADPBfo1+Tl3FBP5ov+NoGye6ROzB3vcwkV3s69AgcEJ3NOIJ7UP8CyBck8vjnIxf92WcAfYu9UGzWglFdxavbjKeLvad41LQbx7wjiH7+zyHYWL50TJIapON6XfIm1ckLoOiHq2k/1ZTPhFq1ptzC4yQ77g==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-prod
    type: Opaque
