---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgB0ezvdrGb/9D1FLUpsyQFf4b0ZQnEbpY9aZ7x0tN/vK1aP426AOtjJPWUPaMdBSZAWcmn7bbChd4I87RLPNYMR1DzZc8PYADAUw50O7nA5/9PIHIcLKLU2hvVfIVJVEW8h4/mGAObsZOj8hgbW4rbqJryf3LzZWZG2MMG3ByhCV5aERNMzFTDWCXaQGGOwnffcVrzNiItFw4tbWEDA1dMDUmid/cJ1sV3SLlC2szzgOocSBYM8YRyLTBJ5CKkzHOdvWHIss/TNhUmgV+T9jyJETC/porJJcb5MbTN7RToVOBJEMPsOGhe5lVwz6VHynFromaMqxtBoR6dW3oUlkLWnNGszrpk8pW2Zy2rl+r1qzVE5iJ80znE6F8r2G4LSXRNP+wXeFh4MLkjyX9RMvgt1RTyQf6+k/LeOtk+7KY6nyNi/zcDJhOGFiKq8QFsh1ROmPx+ToWSVVAMj1ztr/jGKn87qK1h76uHbxyW3vp2xGfesmeSkqZxr7ph35CaSb8QaP+ZnFAxQ6rlxNCLAY0cqDaM2ID/b/OAbWBc2Vd6VunJOGkPkez9g6VnvgFFrwMnnoRR7a3jPtJO2gmq1p42HB4XDDNZFIMoJB7S35Th9yZVt+tJ0UmAo/DwXNCC26pdeL8QzB9jeiljpPKqJNQUlFMPI1DiReb6hW0A+grU0FbpSB71u1I31s3wz2XacZ+qKIIFjQC2svV2xnGQE69fVrRuIC52/35H26S1YNF9dMCS4i5/m5UVf07/vM9v3CdBmSYdYJ2xDPj4cS/vDrfTLbO57jDFqxW+zIxsQNkOOAdoeVith+L/40KsSQDOq5VcT9ifFbDr+jVkWNH438qirItI=
    password: AgBzx9wYjCAbro04qrqC29MqzeptIijG2p3HOqrtIZywEBCWFoOVyKYyLX6oV73L23AwKk6v3qPw3sPwMSTsXrkrFUeHS0f3eZdANpenTL/tqW+kF5ywCqp4qIrXJG6jxDdy2fsM2f7c2Yc9LScM6dJXcRAokowoDUOUQk5OozRVSrdvpmQXZ1iAeigmdk1hMeeegrqzRtzZmjZK95UC05VD9ST82M0QOUbwsw/7dUJKKx4ucOtWqtmU4wB/jKNCLMNDPt+RUMUXfCwxBxriLh8ypHmIzNDVGcbTT5iQxOTvxqz43Ff45i1EyNipFUx3lTXKnY6iMUTpQ7Oq3b6+IpPnKOOEjsr19m0EqTIKQZGFn+pRRniXcUCm6yweKMXEbdKZcxqyqropjDIvdy14iy33+CJaffKRWf7WfPdEKleizj23+IIVHgnkMdB8ixshM2IdAnHOGf9G4KwqJrUUDQYa4DYrHR03/xi+RmKafuPYHX1TudSxfh8Q1M7K7+N34irfdtaaFVg1O4Kwcapm2ssHp+sLeF0N8XbQnlkpEBIjQ/GyyJ697ML+gJf1uvwoQb/Qtn7ONx65lOyGIBbDqPFADwMqlaSz/nniEJm0+vGAnOGJSU4SGLrR/QWlgL3Y78yNj7JvLIH5Xs0bJt9WdkkI7jq8DWJxErneU4UVa8LMlQYQN/SQ86535yX63VUeTIfs48Lxd0afz86+j+0CiVaBzcSABcLPxw==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-prod
    type: Opaque
