---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgBCM54XxQWk6RXZbNwcm+YRKFAYHN7bUmr6yIVFMQj9av50DvkheeUwlOE5Kf22EG0uefE4y+5BLlWY7QLwUqdl0BlfZgj29D9Uj4FbSs8LMvYL7jJ4wx38b+AtDNxgqj7+Pd7RLsRymgZkTI/dWvzdFQYabcQ3OL+6riFER2Zk71fzOCKlDfoJ1ZuLx35xNyt3RPMmx0Mpy7bkgQfLDhyDWhO0K/4kjbQuNNR0BmuP9dePFoIYToprqUR9Auw2Sy0ARejVBli3A/XwNuBT6kG+rSDGSlLw/qO/031bwmjHj9BYhfYpw0sLr1tHGrYoraOXv6AN4ntCJZygKPCLED3HEXiCLYGrXk4y/4lkR/5dfs9rIH1PR47SjZYOfpe7yqJu7NZczz6CQEGn9OxhVr604iilxPWiqaXovpI9/dmYzks+Tcc1+ZAdqovtWIF5RCBhhkoEr1oe0vN3cYLCYM0mSb+K0Wx8R1LP0EuSUD3HL6+ekJl7/eWs7gG3aXmoc1viCvtohx+QUHEFlkvW9E+sZj5Qmeg0S3HFGACWCqd+c9YXYQDgrcIEUur71hpRgo3ArLd4x2CLxAFytslnlbCkskK12ypuyoOzOQessBmjFpuLbX4BnYiPDxNtHABrUUsrNBLoTGVZzzNaYYRuP7KpiaVF3WMH0e3Mk25UsZYUFCZVexsVfM+xp2tC68TJPhLZ0YaAdJpv3A6bzOqHFu2NKGTwlAz2lb2JuW3l8mDw63uxXRNxeQc9mQjfKMGhh6WuLwRU/HGlXbG2ugwUxpPdAwI3PFr4J+czX3v95UerdlFcBBJeeTBS081EU+UCJrh4secqAFN++Q2OsCXKieoNRdk=
    password: AgBCTRECjdDMWRNsYJTRCjODds1mZMA1kl6xA4zDwI1zrUhO0Tm1FHb1G9UTTsu2EnNk5iOxa33gN/MwrQf2Oh7xsxXdFAINSPVkxfJk9IDdZ9+n5mcif4U1LjmfEzqspg/dhMOx0Pr0NLJHms0noWKfQBMk/Q6N96N8Y1xp8G5x3oHQA0QTU/f488/oFBiD1bOHDL/bUwe5I0IybgTBtByT2/sN9DlHcBAQuv18y9yfbj5G1gDdQ9xujNUk/YQ55JD4Znhpl5b1YecuP/chv/uv8lJMOeiexVwQYA6nQAj0EmdXhXYqOMjaddvCq2nKhinChPl3EtUbJsCf1gqsq+r37r4tHAlVM/pGitw9OzrbtDJLYSVuicMKVYlGlnlV854S01UXCkt9KIC/YRuiah4iFKLgUGdKkIkRUdnrR398qrh8fybNHcE2rF8uF01ikaTlCpi1tEHhxPdljUAQmOKdW+1BFqp8hniqmZoBc9trjZcf9eFJcW/tiCQxXvwpT+hbHxrOOyLE7ev53PvUitOoHHXUm1ZjB4QbvX+XdD/Vv3gWUu8YK3jdt2IrfmaTFQXBqpukm+NMg/yhujgRG+hqR8i3/eAkNd7tnlYiJyvlyo7wsKCf5+R9qmz/lsrDqnIyl62Ct1CF8s5PM5zNGpFzvj3X/+mD8eK2K/sCR7tI3greOSIpUqU65fVDLwum89T6Mh9GdYdHg2rvAncszwKF9hy+eKO/Uw==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-prod
    type: Opaque
