---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgAQOqrmo/WzQWsrUGvS57Tz0pf1ai1rxJ2ZC0ehsn6wDywH59nor0YUcLU/VXtdxHa95tfQ60sGHHQh5MSg4dgITlhTpXexQHLUl5OaM7umHye5o8naScK622wx1og2aFCn8c87CtxOe83zH1JE3E1tIP9puzAiKOeckw+JxOqh9ceGR2b7jZzaKoZovBl+x88HzGuwy4RJw0M8XQDQzfFHSiX1yyiXw4n7iRkOw9OqahQryjXb6bk+NhkyEUehTq403t/gnyN2xfZgb8D+vSgGNa43vLNPBIwSngIDxq7LYftfoPb6bt9J4bihsNYjo8BO3BMCiV2ttnwtMVzX656hj4McDaU3rO0nRM1BVjyV3W3XHW9YmUQ9nrcJHVfYFFxKB5VzIbDXCfnIPlLt/GRPhjpcBYlP3CzxIbBrmO4R1Agg8X+75BkHyoCHMg6zN3n+x5qugOP861vEIRWIbYHiaoHuMNzI77OUYvcx7LOgBRvRCYVsqTLP/Xee+loD4iUNLDAs1rBR14g0i3FvH6zNjyWHfWSEl+1+Hft3J5rhOR1HGV28m391+47ZH3N7sf+dmffT2FbjoPHxRjvXY82T/wwKfp+FMGk2uCm806HuMd1rL3sDFd9d90GIjKWNaIW3GAWcxkh58AzMuEylvv9lqyNccb/LnFQiva8gPc+Tb5Lq2QJfWqu+HAM2DsWwLZwI0Drrhxh+/V6bKhKEaw3oNXI3n+k1Jkr5daYGOx3CTfFjYmWfh9G52tvCiLGQCLRm/a254IfLlAPgG9cE1/OoMRa3ZwpJJcVrLgXmWdFbHo+NVSDfxvkEehbFIhgOyQ2e0A==
    password: AgCY2xfCMY3c+ZkWf8TFHh6GqULEP4NKsa/UG8zN9mh9beVdGuksVmA4+KBI1rdeX8IgPosSN0LP7Z/dk3HiEIAEdasURsKVPBUJarOXs6opscdc/P6DdDmXxYi0VkKbU8TQVus44f3AujWiKOYEN+wkzyu7kyLfXBaa5+6VYsQKw5k1TcqXkbDVSiXcb5qoH+ZJQN4yqgZ9vlUWjo7Yq0AGvy8FijJC4AIhNMuwZmOhnS5l3JxxxOXcwRggdGIliYFbgoiBDd3LFJcIdXP+3mrTgL4pSd3sF8uRlnMU+CNEVh4sdo3AjpHU8bBEoLHMKwvJekTedokO6vEbspolOrxdJ+RKgvi7lmbdnl4Ef8KP9q6GZSQDtBVEmvZADUs6jwgMyst9baCFcmcAF7/szfAkHF/iegjFlwpKm4uWGdeDAUsKDcZepA4O9b0WGzq5EgB6HHmBHw+F+/KAuVF4WB+e/lpE1LuaJUnbLe/veekFJKhjllBjysfv/JPButggfGY0/b/+LZ9lOqeJQYC2QtI8zLO8tNYZNDSkXczZY40RiyWy149yOszB68FPDKtvxAJQ8kL21mVky5K9eMJfkEAZEhsTHTAiaJxk37wFVR2p0iOatIf2sOIq+eOmlCpb+csGUUetgan/dw9uqZoj/BnJ/vBP/RLYeZPA0iWKJKeDRMQciH93smbnZVUp37DwAiRYTzsDYstmjjxBvZqIpp0=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-prod
    type: Opaque
