---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgBTMnv7FvqHHgUREqoPFOj9j1MwU5RF8M29W+aCRuqPJPjYfHSaXsv3MjjI4OCtSbbm9/yZ2SC9kfGHbeHhF7R+FTxGHElb4GOjUGinIiomg3lDIVgdxAWynUbHgLr9dG93Muwxj0aXdl4Wx8Sb5WZVWb4zJx7mb758GIr2aY95VPUm0au4PjHCdzlF1mk4jmsZhIhSqA7YtRVz/n2poTgv1rdiwuxTQInkcGNY1U02t1KwlgGdtgC33H8yylERRjTUrLBPUY0bb4XkkWzYIIRuhPrtWO3JjJjhe0a9ecVj9M/UFDzLlLF3eAZzz0sOmGytO1NFybXKb1JZwSQROljJASF4XCfKFqUWQg9KCh2mftRkJsrYd6PivNHHQTUi+E++/oWF43zC6oAX64FD0l4IAPu+YD90EbW6ePvRrEH7B5PkB1cnTOSRhf5sGQ8qyR/Sn9I0kiKRoK1NKCWwbh4ZfmdX+YvbaOlOv/+KstPL+QUY2Y//Ij9gJcjZQvkGvJi8DuISp1wxIuwLWlBR7cvIhj1MmSX0MU+KUjMmsIXWJNPJvEOaWqgdX2q6hA6zCJjotKdfCgpVxzbK4cGBOq4IDeX9loOQSSnXAT8srTlS2XZc1TbldUvuU5maDZioC2ZS4uIC1wYzOdD7BIhFTl5J+9mgAlOT3ZqkZRRcuYebCrPd/AKM4AUhntQ9NjZ9ZteeDVypwFPYFoNfNfkjKvFVh0PkZ8mK8LdtEEdG0kuZ+j2nZNZW18VjJtfXzSAyHgRMPhWpFLYFB2QVlatmKPgj+cDdin+LRRcCFlnDzGbJd99kHNBfHgT25ANugxy3stFE9w==
    password: AgAb8Tl8XtoObElO0/+/UvrstACi8/MS4jBX6qfXHtY/Z+auB3oTSX7xH3szP5zGfWP4kvAXFjtzSCYsyaRxCrdW2Sxk3Xnz8n+pGAzYYbLD/gNconucnQl+76ubI8NqgeJeTgFPW9Eah7seRuomDrEx5wIRFGmByGt+2UK7aLY+c7031UR7k/mOyzXRXqJPOBT/5HyKjgWw7zZ9lfaQ8aJXESyGwCE23yQtm4jF9ukD1MQWdFJ0G5nF7cY1Wjcmz4YMYwir+GF4sB6kwfZqIDxHRVw93NqEGBu7UIWB8/Uedz63wKBMI9s6hVopDi0wCVoJcQHgIxjnPg3PlBJ2Fx13Sy2+5EyodhYJD/6qRPwDr2Vp4/hn+6qW9qXEc8oRlEENCNnJQDYxphd1cOuYLFu3DSDf31YMjiNb0DFGv7Ss2rTAEcbh+FPP9wJZeUU/NK7KB+dsRBQcv3MukOmaAg8V9BlAXh4XQ1wbrIjWg+PtmNOUZBF5xch9AG/sO28HgXTEUniCIr4KTXFhsgSVpJ7BxmoHVIgSf87BFcKuriAaHJOrb1hXkjCwte4rr9rk6QpIIXmYGsvFvol2T6Q3e7tDIU1EwRfcatKvEfJioD9GBc/ELhy6xipg7DE5p1FvrB15wyJmthJLrJCvXBOKUSUXzLfAT3okUDpY5+rx6iGFDySucQQvwXJcfpy0oC+DnOyYH6nVTAth4HJV1BPvLWo=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-prod
    type: Opaque
