---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgBKsxjmYFJr+Pf5gWbhp1/dlUpFJL/f5Lw30UkAi3WxADQpJPVQGFmL5fUoEqVaREZeimXr/Gyblw6xmqWt7FhH6WSn3inTJ1mBH8P6wlBqqjWMIbjSViY2LuOUR50bp4GgpQ+1L3+ToTxQF9cKHYWqm6+nfjZ8flPh0ipTGWEcoOT5H+Y4vdT47iCM2RTQL2jSTFm+ZoA2ZXcLEJiapAQ+kyxRw4jDk0jZqFzb4i8v+OgVfJ8nrj3iipil+rOstoIiCuNkpOF7nc5DsJCgEhSS8W48CO9OmlWIvD0nRc++29VDpFA1jVyLagx0wvoNL1FBih8Wh+sBo+Sh6rnlb62WWZojhGpkkTH6lEGqb0djs1S5rK1THTq31uL7CNQ0FtFCda04kzcJVFPr1CcxphRPLQ/jxFwaMI6M9YkOkJJdBz3+A1c4H8EXFlQGX7qnoK6eAt9EWDGF4AcHBt4e0ty/bLMaMQjGkdwUWPW9CPZsRmRfZu43CudLnQ768mZUiabEgYynA9mkXqdFG7jjziUm7WkNNmrEs9HsaSTvJU4Hu3HW5c0lO4bSJYlMvCXbDAQaSNH9Yxtf+8iFvjGKTXKU6+7GdP2lvikW/HsxeS4LAQzl+YnBIskkyDWN/dhr5jm2OWBqgpOhHYe1SWQ5pdQGVqR9bEyUX/v6JbBD8e24lxrvfKjCqcCjiTL0FJ0xujN6XcwXMsvrXAk1eMjkIhXlYDiCJqw7ynNNG3bnpT93cAK5Cthp33Sf6cu+w7E0fgj/P/eJbn3Wej59cAae0GTrepxw+qTJ3C+UW2ClYS0k6E3ujezJxZN0IrhQ7CJU5qbJDg==
    password: AgCuFtkXOvRWTw/JRGfnNmd97ohmXsLLhc9ux5zMfr/0WHXIvEuPjE3P+RqWFaoG+wfNMpVmaRhcKvwFMOfDSPpWosPLXdT9EvmdKUAUNi996untz51BtvaZzO4VZWZr2S1GG7fzXUnOty2tSomqxGpzqk9zcXfuDdFZpe/k4fB4tV3JH349zPxGXpApCBRbqhaJSVh6zjXWeBP4jr67Nyon3VDOWSi5lOqxudVqGUpS+8Ty5BZpMx7vAHoiS9CZGhdhnqSY0NbV7Nu6dvmzN9WZEmRgSJYgPpcp3ims7Oizg/ZzCIjuY+jrGJe7AFQN3ko4KY5GD4f+WE4soOyPtsZ+p0+GXZ7cQSfhk8wRZd/OBS+0rFCboedJ+PmeE72aBW4MqBdsm/9L3hDmsWCm4fBkbrbdzV0kpYv4sQjofmMIAE9arAcuWIF+zv3rPznPonJMDz+8fyI2VlxPxySMIejYIQerAJIw97JpWjHzifpF90++oqTBvACuwgZ6pBK+x91yep/fOTBQ2gsWVXJN9dEJcEzTy7KY+csd9bpbc7pFwhODh9TUK4b27jfOez8RrB3V28MxGDS7U6JzVmODobrnHHHPsfuwayqJWflAZpgdG0TVt4rK18Sy8G6s9nXLNn/L2fMdVk6qXBA8j9EmDgeO67hwsDGG1bWALFl8w7HnnK/x2grn7HiUXORPTtS7ymEfMioNPp7UvlLME7IbSPA=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-prod
    type: Opaque
