---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgAvmmDOeTMxMbI7dBTmqMGGoFJRxdytbimu6vrSvRLbTEhM/OYVdwnId4rRnSdZhbQTdRmJNjAFFGhVe50maGxorqxDVWrR80Zuio7iDrQ8dHQbf9nSRiXE0KMv3mnkPXXjWhIkMXWbeexnh7DuSDof1hO372qc4gZ0YzU68ylUiP6BtCXnkn3SB7QYgmhwNzw/MHChHYYXDnhOj4Fs7U8zy5HLGFA02UQkRhxNEYd46IVryJNrdvpXz9Fa9jz5+8/R72GrRQFCSHbQGVEU5mIiu/tea3I0mLU5dfcid8OWzkORT9PqtlePTcg1TmR/v1+WHwTNP067fJaJIJBplcOEgGn8lEYI1ii17YhVetntscc3+bOp7JY7yZ3qW7odkkhHvwiTdf/5L9mJI4RTqEmfS9gHLImHqLcuKU8yLo+VbWJPUVLpBaOFfAUbsNXq5224jzZ81YaiE1wT+jMD4aJMaRn3UkVdENban5mFI+GwHPAFBgLd22SDVcrSyhPixBxQccKheofSgQpTmA6Hkug0ECw5s7OWshIKrELzHYO72K59cBLgjpmeCWyiNJ3hK0W48M50eEZhPt2y+RCMEvSEgiRGNq7HJlEGoYz19pc2cZmoWKgytGJgiHNmpruFwQRx2jsjwHIZ8R9t3IoJgyFKD+N/4GiPCXnXhXsadaVfqIouyyRb3U9OeZHgaZJIdXXyZloDqBGIOEOY/x6HZItZ/dxMjUcaXT6kM5q+2YBT22IqCMX6/6+salUWR7nNMeIxZYe68e346DuGCQbYrO8wvSOjU2j5hDVQ7pUvhc9M0NaB0JB9GCov8BevdU6cExcjvQ==
    password: AgCb1tHbCgyiqb6Zod64OoRSpvUCrLNqxjGYJrzEjzODwF2jgFPwB9newc0BfDFJQrkt+g+N3qK8KDNp3MxfeP43RQfaICuO6uQMN3oVuyyhKSNGYWz+sxEOq2qwPB2QIUSrDP/A5r0Yo4urU/mVMinz5IgrMh4FLbtDvUMZrusogNRxX0vL2ZcDW0nvGGJiSH0xvG2s8OzlKYh8QkHcf+wum4IxFBx876RV1o/OYVOce+wDcOzF7txym8+DmM3E0KY2VT2RQE6qBG9sedvK/W6r+Rn5T28rNTJySz0M7A41nu1vIX6ldIJd+osCTKRgj06M6TtwW5+VNF4S2GgO7wLohabW5claINYvzYPEm72JQDdI/thv10kX6KJrfxCa9hywjwKA9B8Vrc1rtc/tbsgcCraMAjw6g+6ADdpIaZ48A+Eem7anXLaPXz2O/ds+Rdod0SUa0Gxu/woPBKXvyGKBj6ZXwhoqtdnd4rG8/5bPujwavIo6VDA7pWZj9+GSdovk18yeen+Es+ITcHehT1Oiljfe6TcKZ5DHAGQg8kQuD2sSRhmgSGPu5alG8EZYsaiTxf9ZJYg0oSMDEg0H+yyQvup4dc2zeHaU8DEPL/bVIiiJv9vjcYXQbi4AKxYjKH0NMElkpNetxQmG74CdnfCBQppf7HOK6jfxqReQ6nDHLQtIEFKtQKrBH/kWd8lGk+DLJRxe6FcmLEq8tnRKEwk=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-prod
    type: Opaque
