---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgCUDSetU/tzU54modxqBDDC6z0M+OYw2EddVspjQnE3eVHcOef0Qn1H1ocWYG/1sCFlriYJ4P8Vacg2kLV88sVRXOYSg96vY0IsVEc7hrk/oVqiDSher84KCLZQXtvB3oQLNbzt8FoVaAgSiJXVY+ld4nq9z8j7yqVUuUXMktOE5LLLXe7p2lVbKJp4hcKKm/sfQ0RTAEAu/owBhisQRNDvQmeYtRjcqg/z+t/+g2V3gPfqBmX5ezGnVjJ6PkCgIvfS/mWz0PTMoPUbIIvSDFAamWG+3AMu76y/S3rXmXdEyUn8VtoUwVE9U4KS52sQn2o1WUezMYS/9lbDcIi8pcuSSnHwgpWnuaLmb9+jgKClNGMurkCIbkOz9F0tEUPgoKirf/rOC5nQ+St6J+vsi7pHgVuoA7+cxDuKk3ubVisezsGMKktVe+lUFazxq4gkJ7jXVSOjDjwBNWavn8GzJ788dnjRCXLd4BBnFHlnAsuRrZAndpZSGdXtyMNYs3Cna5lBSa9evwrRDRFBv+L6iCH4tfU1jg63ZbUQCEkrzXG6EBCYTfpIMlJgv4hk3X968rq4KDUo9/FZpDdlg9ioDQm9V4k54kIzvO/Hvya/TYYU0cxvNSDYwNZz9SPM074hbDqJESNSMcQa38QrxMUeEACurYCbEFmniHSpHOCHhcnt0+7qoyaPgG1nffqH5x43wtdxekeJNI3XpfdmUOil9TmnhSFHo9orRj7JADXuMDQ6nACWktLZ3l+MjveYD6Edy6ilz3NZAEVRszI7hEJ880Q1gMSon5hm3sO76jBVz7xdVvZUcbultS+idphJqRhqFNCeIg==
    password: AgBgnQfNlegKDzTAsV+lRD5uBhztDsxFmHu0kbpmoaHsfvsI1fiPGFOTHZ9YrxQPV1xkm4u8Vfcpl7OyKj14IflekFW9AfoJOAEdADai4gzW6jkByza67RvMvAVCVKEXW4a4RPCQeulKaELm0PinVg61fwa5wem/UEDz2v81VYvPR/REcqymC1njW0LUQoP0R/mn/+zWOY42rhsVkWx9HF9bnnMLV13S+WwvdEJuksn7M2tMjqQ6l034x3Ug5raVDoI7RJh9evImfvvipfijA7iYIXYykh39YzW3okU5LyeaieGy+MOM4qeNsDzJVyVuusZW0zWsp6KRp6E7OfKuh9XkitkeeG0YD7Lq5Lk1tFAo3KW/T7cK6gwd8xtoUHvrAVJmb8g6xT9S66GWMUwRbUXydqMVh5bynTFwPhJNZoiXF3ClwAp6DUJKkd8iFcCUVpxPPatAgz5k5YQ51gZ5cexOfFKBBtDsBE4gn2jc9tOudKiOCoCgrPm8Rn+DZHcgWkNMkXAXwTCDur4po4EjmW79z4JvlHP3pvpJqz8nzXE92OMAUGfdSLbNS+lXD4QHnQmhcS385zaDznLTGntFDmH+AWQTrMSnRC7x7aLNlXCAfpP7J5Ey6WL5Fh6jtt2/ylzyn8pmlId1AZm75r1UqgQOzgPrLJiqKPBECyDyMsXPD7zVaLE+ve0kwE+q9S+PuAQfsxUS1ECgnvqUFqguJtI=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-prod
    type: Opaque
