---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgAbUPvN9H3w6JTjvttdPQfqLZXCtCLiFTj89Eajwo9/YFathxP0YeP8WMQbriNpc9qLM5/wdqoeMpTqMNyXVrvNf9GIAGuM6ay0MMAYcFsZa4F6GHKqOJDCPK3rUkPiVf1h6xGS8m6f6hB0QbMh9YmKkQZCRFDsusOx4J7MTTcwcpXdPYi6B1fPx32eVw3GkeXLV5yKiTrtQnpYzucrtp5IEohuva3zywq4i+M0Bg5jJTK/SVVgOnWCJMHQOr1NSCvFQvkQEauD4yBXEDWzmMSoSk+qaUWTc0fs0wL60F0rJv6vfzNfsRjW/ezSWyzwetHpUAayFmakY6jDVKYqY3YedXK1A4Wl6pj0NaNFeOSf6d+lIPKYsXq9RjgBgABHEXM2EP4wZ46CVBgEmSwhRvtTywV6D89Ko4xT+6ZYk/4tpSekXz7ON73lyYyABCsWlfCkQWL5BtBsC5FtbxWMekvrjZMLCAlTJ++wTGg3O/R///6ODhDcbWYXSWG6JY0VO3aKEv6caIZFJ7r7YsvYDrIJbhsIN6mGcPW3E8j111zkhcKioguL8GqiZdOBb1iJG4mqILgrAyWsc3g+voRfCt/MNnXKIdEDTHG0HuYAjqKTCnMeYwzhCpIQqTBsJ6kgGXnbvS0omDjjSlkKO+plIWrnjkDWj2hNv9Y0fbVibWEg4x8murFFBqBE8V09NPLaHsn+TVTTTDmqB3BEQ5d9ztzTNsfzgmDKpVCHVsgQj8N5FHz/31eZf5Fau3UJCiFAn2p5SseXak5msfZMXoblX/PugBHiqTPAlHG9jtTyp2V4dZBVdjQ/ZKciDbstU+6GNhWa7w==
    password: AgA0py43IWX5mt1i/RvMQrIVD08ec9tjqhmB+vn3+9BURTMPmuEBlySnP5OtxSVvFD9P6RmEknHFWuVxHhNADwAgr0A3eLXY1At/M7UDwCCnV6y4nfX2L3ol4HS1hl4wqDzT+4nYA6aBNPkimymosWa9ppuxWWUzErTsWaUkvCgrEvRcxhTvM5l5UBNwErzkGGNdZKpiR3x752gSNllLc5LLkKqFPz2Zg52FrBy/5hUd8qJs/LAwbuhwddYL8fgAEgocOLiVTJWXc6TzojB80aCvtPH6k9T7YkFr/OzqGdVf5+Z1O2woRbxKdM+/wEuKBKGs3E12FfV4nXuOqyVPhcD5A0TdHLTuAUaiZa1nUsm7BAmUhFta9Ps5in9I6h6zHqCmNBpiJRT80PELtczwqsgqyuJ8DCFqhlfsnnrPE5GSvV/LL8eWnnR9gVrfShqQFup9AN2pKTulDhsnwLUirzfZOIG3hH7Gg0JTeGtOu8EkATyrvU9hwdqNFSeIw3NhCvAa1T8wk+SjbH+RdatWusBV6dqbTav8MUwuvmQEmh1crvlE+7W+GMeqBW7qDSMwrlqRJevusU2UvlnIhQRR9r0u3mHO9jnyYhAezYAHOi7ISxtAL2I8cQzfuMTYvjKBHL5W4tCI5nWV2GiBQjIFdLyHpizI1Wwo93PqG2d+x+WcXMjETQKiaKmaOKjtRLrTHvzHXWSGa1oLcGC09gZ55Sk=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-prod
    type: Opaque
