apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: prometheus-checks
  namespace: vroom
spec:
  args:
    - name: target-namespace
  metrics:
    - name: error-rate
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring:9090/prometheus
          query: |
            100 * sum(rate(http_requests_total{status=~"5..",namespace="{{args.target-namespace}}"}[10m]))
            / sum(rate(http_requests_total{namespace="{{args.target-namespace}}"}[10m]))
      successCondition: result[0] < 1.0
      failureCondition: result[0] >= 5.0
      failureLimit: 2
      interval: 2m
      count: 3

    - name: p99-latency
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring:9090/prometheus
          query: |
            histogram_quantile(0.99, sum by (le) (
              rate(http_request_duration_seconds_bucket{namespace="{{args.target-namespace}}"}[10m])
            ))
      successCondition: result[0] < 2.0
      failureCondition: result[0] >= 5.0
      failureLimit: 2
      interval: 2m
      count: 3
