---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kargo-admin-secret
  namespace: vroom-kargo
spec:
  encryptedData:
    ADMIN_ACCOUNT_PASSWORD_HASH: AgCXGZA5brph3QQRcn1HZ1/BUPfChYFby24F201k1xD+3hSVItC7vMZWTDTDaRgyj1pLZXWEYWLQRozv41U4d5ThxY+zs2wRDTpblLV+V+8FUIhkV8OaWwXjEU4vZPRc8k/7KtZAHzX9z36QI58hjOPBIkE97VQY6x/qdkgWEIehXtAVFH7XwruPu5n5WfiY7gdECBZJun+UsSBeG+B67g/U05ANJRaXgdOwkKXjKX6e7WmZwUPNZyKxTp7EMDrLmZhNTdGEXE+BGmk7aUaQ8d13umZT8fE8rQzWOErIkCG6zWMFTzPjIq2dyhjGYhNIve0aqPVswH4I5abgAiVKh5hphpFaSRP10cicjIhDwSk8kYN0+PKVP16eSrAf/kFn5HVIiAnzNyC1We8CgOMkVRypGSOzpIXY/NutTcOQH2HbyJzOJ/G2JCTNEFhKCt4moOKawPt2wvgBu0oC5fVsVel7juLA5PCL/gDeAOAsuOLioDATjv56RJNNfnvWSYO25uWkzYiTz/YSEjeP3d4Hm583JBOa0ft0C8LZmSwqzRFzjYOoWFt+L9QRBhyxUqerCCXivCMqmupwUqQLaY6iWOU/RnKC3m28fwnMIVV0vCGkn66WdKprD8vW+e6Bme3e1P6+82QK/0rViPZ+40qR4/SnKG+LIauOAoXHsw6syVRhIu7pSMg6Zc0O72i0CrKwIC9W0fy1NT041gqXokKSqrw+jq2LB3Wd9YiVv2L+CFtpCW/1qVpbNJDtcDS7PsTVfctQPjNBt1rEYUTU5O0=
    ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: AgA+pnUcPF29ScgvA9Z0UioMenw4jtCEIGkTnL2g/f1upaz5S2TBMoKwXuYJi14IGfcXI61pPUPyudR8AbwHg61IoJqw/PXj//BQXHGCx120NuOibPLiCWku73VnNVKVFB1Y7F/xlQSO+AQ7Vrca4p/8+xiKwe95EYut0IaZWdKL9/j29fThYE5I8FC7xwosHRolA39oChSXnOLJenNK9App/9miq3BYeCsBL7npBOQzTc/ti2UKmWFhmix8nLyCp4uts88xPIlkL2iJcnGEtsVmjBtR07g4l+CEtOH65hJvJdlE9us41Ve1rTd9kjcfwNWpq7GSb3f2KT2LR5zZdixypMMGcmdJTkhhync2s9KbVC34VqtTM5gTtA7t5XzYQyXvo0rYQPXMRduT5XKcpvUWD2VgceGXJFVVYEW+tTcnZvJ89in6BzA1izpMUeH7tj8Xc80T55B5+aBNFgFUDiea83MMepknST2pRnSu0OlYAjFJtKQ1fC8RmvGSXyROAdWpD+5Z9HtV2ssJaAZoMdoNnwWahNBMzeL6OJzDqrUDFOovTPTbQQm6xnlfLkLWGtylhfIMc14gjgco8fVLGVA3syvJiYTnkrjMPzL0ZsgpnRyuk9OqjWWASMwlrwqDMSXCqiJqgzdYj13uqpyYvlRnBVq2cJGVX+xsNFaQCE1wuGr7yWlCwnLKFWiAil7FxAuRYbDtOptK9ZzgJlQqZ5g1q2QMkWk4uMAGJA2CDbrtUIWhKgSU9gqHiLlPDA==
  template:
    metadata:
      creationTimestamp: null
      name: kargo-admin-secret
      namespace: vroom-kargo
    type: Opaque
