---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kargo-admin-secret
  namespace: vroom-kargo
spec:
  encryptedData:
    ADMIN_ACCOUNT_PASSWORD_HASH: AgBNDfA0odtnLF98Pylk+TWg3WDfgZG10pAp6BOEBMeq9T7StDrfHDZ5oGoI3EEOMiyjypIExNSM53dU90nfV9nNBNFX37uqz0BceJcLBzj1mFPppZLi2DYu9mLJm/VobPitRo1FWXPqgx7qGQ/5TGdJ4bhgQhABXBfX1wDWA+uVsyIGvRH3qbqMFTS0w3kMJ8vwKj0cJTMi/OF54b1lfx/3gYTHIn1NzFgW6r7gFkEUMQh6BRkbNMmXpV1Nf8c669xuqbmXe3/C6ZArMUIH5phACi7Fpcakk+RG2E0z/Gaq9T7B1RmDkUkUFQ50r2wqLXSDK/08HS3dnIceb/PrEPiqHXeSk5tZZz22GLV3os+aBhBQduhgxwju2gBFBY7o5pfraCU+pEkwrPtxX9mAhxA86ap3eoUcLQVBSTDx+EpYhNTonej/CZqANqxZlMIh+RlUDHyOCGWnvN9D1e/NaHoktUdRyw/1OzWdgB9cJdSR9siu7sAl/0vxuH28qcxc1/lydiwbgujUahlJHqY4pn7XBkXtMsPQkun5IpLcyexmQ5jhQnqGrqwjXd/jYDN+IQSbMb9Qoresmqy0PL5vkpgb28fkmqd9z5br7GNL5nxxZwv10/HaPuOk4bzMXRZrPGuOJmZUSDe7PRCWtqXsU7q878Uumt2p3XOamusPO76VPkOwEEQoTjkibMW3ymnmP37M4usGDPG4W8NWPzkYAiJvfU1whn0F2IGp1O+Q3F0ahq/9NAw8TD0WL7/HWpz2rE2nisKHTSU0ZLeZCOU=
    ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: AgAU/Q/i7IudSIxDzETKKfq75ksHEJY3wEwYMMytiBbdsRtF6cEOgy59zNxQh/ET/+z/XnVJHRd6Z76BfwP2NKGp0EVUd5qUcxYY9qkhEYSZdo8qtPCCG0HJMJWZOAd0VRYOifsIm7cTCHzqmUVmUWolmHvPjexeAEWp/IQSm6Q9kk9stULdr5RqNOerUA0RWM2kvIluCFcGH0nMAS7wb0DPeCqZK4r8gHnVioFfvlHn4V2eM4W1469u6VSlooqlmAwZYuIPIV8PzjLFUy5e/lfEmDqNKMHxdiZSdeZzboFmiARfF4YxRytXZK3CPFab82CrrQSjiFvT3zU4YLjjAVuF4JJISkypFD/sL4fRPXlVQI1LZRyvgUI9n1xfLzLs50jy4LufIUMDqv4f51KB/OQxGykgcttjhFPPqTk9KXD2tUTneaoPZ4jO5TelrlhEhExmjJiCvqpSkv5RFb6v0B9bqUI0p3DP43mCGSxkEU+SRThYrA+LSX/YqDfqv69Zds1+Md1Mz1ij6rsSogeyedgFcpKkn2+e+gTOaewnVcHgUjffr7H7aXc44EhzoRl08bt/sWf4d5k4ah4+SQtFPH1FICcjuwKs1p1m6kNgVZGJYPqEzjCVmfG3iQoCtWUK+1vw+JZ5lM9OFcDoRrFLdYIyAxtMHxYQvNZ10dXCcIJdMAu0o+l+NwRscwsOHrsH0YgUPyMqDVUbHbPcc0jp0mthbK+9DXTpPR7nRf1raaCRrWT4rp2qf/VJMb3Ttg==
  template:
    metadata:
      creationTimestamp: null
      name: kargo-admin-secret
      namespace: vroom-kargo
    type: Opaque
