---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kargo-admin-secret
  namespace: vroom-kargo
spec:
  encryptedData:
    ADMIN_ACCOUNT_PASSWORD_HASH: AgChGapcv2EWd7zwrh5ff4Yu4CcXoTGieWqFguuQseKt5H6W+ahhIcktO/3ox44XEOhEIhvHWYrBKrNYHeu5db44JIgR0fRc1Hyne4GFUHvip35JRckUvKa628pbX0YN9VvLSXv5X+Ch9tgIqvta4tlF2/jURHuz2l53SGWoH2XGRdnLEVjtSeJAzmLZo7C7ISyo85kcjitwmc6+GQCUhXlchtPORwN2s+mS7Z84la3nDLsbagr+v4uvDw66RRK/j+ir0TtfOoXX41GGZWkBI4exmh+k2eLRaZ32ap7ujKN2p0drFrBw+utqRTUXFwjv/GXY+WQMhTaO1+hoHSoX54gRlDeUxipwn31OfL4I+yU2H494QOMkGsKNNRO7X3MFQ1trtVN5j+TRAVyDfcrlB+L0F5kmDGy6NNkXgVAso6YJJnY1wFeBjgDNurJnUXUf3TvA4eIzxOmqX4rzYx9TdnYeXoSOQYUhv7OXvtq6vpQQFuiCPM7eX1EBBfC8DvmNRTNedjdffQWR8UVLRiRUN3eRqVeXW/Tqf57/9xkbnBi4pvNXloamY91qZzhlNZUDAIABC1VcWGpxxbfE5Dh2EjwVuClIfS31dVBpqtTmq34CecR+YvWk0V/Io8qk3sDjO0Qq2DBdyeRMfrzzAh/P4/f4GWsQjSG1veSnMLg8n7jPGtSIeLLFodXPdghU9wIEN/uNJ1pkzvYvDznAGYtFr0jHtE/HsgmJGvRk+TDx3idPvEwXPW82yjRxVAQhZlvjQQRx1IlHsrvVYU7igew=
    ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: AgCXwZypsXUQ3269ZUo/ilUmb/aGhaUWPjh4SECRe4k5aXwJvCb6I6KfVCMpDKL/VA1L51Cx9OLyykhufSBTekLRw7teoLptOLAPVfnu61sBPiF2ICFAjiIU1f3aHEwgwJY5wVHLXT+DNgC3/qB/LvBZ8r8KpJVvhRtWDi8aiWMGLB7Jt8bj1dAxG2TdRctvc3D15LuKmpxwbw5iIgq4y9Xg/YWOtbNir5qexfXaPKh9u4Z5q9nsYTonv1p2ITj+e02458UOlBWVUMXjfuTQu2+TlMFXkRT/70xuMIdjzn+Zh4rIDnHjWEIWulqTuB7E9UqeuGmBL8iIYY25FsQ+7mzsa9dS4PnM08U+V1vgfRiZJLvlecNZZDEEadKfFSYyV26S2aQC8LPpe3ORrlOPxHK4695qket0t3sKnPqkPbfLcdXehrRhRfl8q6g/fucnLyAGMQzS7EZvhHAwuoNPoG405rSygO51ACdIuAqJxj0E6Xi61eeemvCogtyNng9aPBe/rewxh3aQ4tE/URdjCWepOJSUnB+VwKZUKHKllA9w6LXC4ZipHVWrRem2FMZvgzWNUBX6/2P6oeT0iqwj5p3MkCr1jwiEik76C3Ma6gXGQaaaamzqVKty60I6Czbcr0PGRmWL1+Fqj6dalBq8wE7rrwKiz3Kq06+cfygUCiu3eZIbs4Y8XZdj17TNi+CgZnAF4iJdFa9PXlfCI592mGSEIIvFCEYHvaMm0JHFUKgsVtgQHXGHn/Qx+Lh9WQ==
  template:
    metadata:
      creationTimestamp: null
      name: kargo-admin-secret
      namespace: vroom-kargo
    type: Opaque
