apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
spec:
  project: default
  sources:
    - chart: tempo
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 1.10.3
      helm:
        valueFiles:
          - $values/infrastructure/observability/traces/tempo-values.yaml
    - repoURL: https://gitlab.com/vroom-app/gitops.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
