---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgCJoxmQJWi4W7+VwOGKm4ivyXeerXw2gqdpyskmpDK3ziZ7omd/L2d8yNLmeipzEWNobepLZgMyASHsTLZsgw4b+Y6skeGkh0zNqCs78AObRTN2h78azHAppZ8NoIrMrOvFI3aeiHneUFIcvF4Y24ziJVgCe9CoLAPeGz8q3uTDZx4yrSgH+iPG8PjAMpj1YCvS5jYynueh83FLlCBpdxDBnX1EgyBSzdgZCtzxNZNidPjjVezG5HAi4FMunnzpbTXC1/+ONPM6IKH+bWvZy4jqKPuqotdjBCYBXwAk3flrOnuD2nmHui2vGiPrXlO7BLEkCVXdkWKzXcgUbdVljyNIbaZFeaQYsMdKr2eYYxfrP53Bb5vmDrMtPwd2DZj73L7D0z+jq6zU5qKe+X1b7bpNyaJBf2fVhUDjUiHavJu8n7MLVtUofIRxhIfbpxyjLTDle2Q9nmBjUVjIdD5eyAxYyQ6nqJCbCuD/zTxgBqy+CkX6xFdzWQy4tUjMAOrrNRv01wwKUbLJTeh8kpykuJDA0PUHTUa0fO17LQScVkD0qsg63RBeFSUs7eYWhGgKTR0CkUwReLC9xZdj3Q9EPYn9upZIZRIZK756AU/KZprNVm9IgCHkt5IzuVK9tg9Jpc1d5H7iR6hLIIqJFy39cEIYdJdUAEesDETIut36Hw3aZfo/bZ3EdUYxM4d/jYOyvm6B09N9CpHrDzNOF/IYYmTLkZp9XviDf+zYtnWuQMD9+xP3wT9g23TbqC2aHGXnkVji98DigQkXYk6RAYtRB4HtopveHmUsPIOmil34ruRXiYBmaMesxLeybI2Qhybg7Q9V4A==
    password: AgAAWUDi7nLtmozEBV4IZdZ6eCHnhHkhKTX7w1NxsGOeR8bmvaDbbcXTreOAyuipuTQNm2uLr9hi7Z1qpCuDmciYB2d0oENoTxsr3xDZPR5v4EuffCrvpmYKxc4as4ABaLIWlUu9Vl09ipJ7Ah5xkOEPIzfmA1S8c8Kep+MoKCmRcIHzi5JaNm6KI81Lo1gRwJTc3wRv2jAhFcuNJt3GxbuJzwzF3wfrm9348dRD2vp+BIYPB5kC1giF+CG9I+HAmd1tczlKEBh3+RL6X5tX5QgAKu/Ogh/eGY4tR/l1kZtzzr3FCIGBF2yAycjtoxCqtSVtn9NbcoYbhiPaMqgKqPw2sygUellUcXvlRs+q7NpzqILr7tjftXNbHjlQ2niBk2MVLdSmYRS5mzJr0aNGP3SUug+F7DNE/IfqSg9l4Z4Zv8Off75x2s2Ok9C368R/hAPqHTAzUdvpKP0tADtqL/2iWimlBHFTESgPQJR/Lbo5qW6+AJ+4eF7PdJkNfyEP7zv5NT8bnh/BQN/8nqw6VLZ4Be4GNoYeQtaz/E2ayAbrxwx36+rETT5xI2Dkl7mqARp1uL8g0rbzw2gyLRX/5fopH9No25DTt9/ZPB5We+8q5o1DBZ7O+UhOfDx8kMndonzQ2OLUI+fzSzMD0GWc1Rvu3TuLTVsV8kFIprIBTvhcjzEAyKO+1qXnrjv9/5wT/v/E7ps6QLTZ587/CUTNFAs=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-staging
    type: Opaque
