---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: vroom-staging
spec:
  encryptedData:
    database_url: AgCQqBVjoo/BJ7YwM9l3otTbamTQR/itOA6F8oSethoMaEdGmqQI2d+ocmTvBrq9a4fL1QjF0obQO0QGT7R6Iefg8eyLZL8NQxrcSriTNE3VJUpCXqrVjeG0+IHeVe1WAxAi802GGMfubZ+ZRUZTe9nb7o/fskHWTMSzh44zkyl8bRXovCt+HlZggzkrMo8Wr3zsTbXsDtMBO4haVMLJfD3ch6fSlukOJsT0AydQVh6oUQIxJKo4WwjyjpufU2Z0/S2n2BUB9AoYE3QWJBhy7RJWjRfs4xKgrAiHNLUBQ782dpidpoummsZgq+WW5BpyxgEi28O3WDpWrrGvi+5Ira/OBzYDhUoLg4jwORb0xsoAqZgS6ChcZeORfixxccvw9pOLqKWwujqbpBYd97aUzFXmmrL/8eLyqFYHzupFH9QTBnNkyTaGYPsDYJbHRLm3NTh5NKJjdl6kXTXtrnrI8hXo3gpLHUsZ7q38xYC99ISMtHPIgGmhrs1GLmTxsCeJbkOMXpfh72m1xLI3p3W0CSyWz7R0TVyO8Oz2FCLughHtYMHxkJmLloAZZdqckmlm5B9hXH72xrIjGUfyyD5cQ+AtkkJzu0evz5XrMXK4wAC51SVv+MOFoxkuO4vvrI+fLEB8xTM++jHc9+ATWq4w7jXPbAOadVcEMkdfDiVE8M5EnrnALUB5ZHNHEMneu0M8EnnpJMqCoJ9Claiw94Gb/cfq0I0hHTbUIMj3xYcH87jtu2DtEAxrQ/wycYonEPhGM6R2s7h8Gd8z0+UPzdANLqxKcCnhkaBvPRwlcd/Ufixusxx5txGZBzwqlA2DOJF5KRW+tw==
    password: AgBvcDWYnRRKxWKWAq/QkT4fqXxgQ4YRoIiQl+kPLIp0EPbcMscR7op7GypGSIdz4oG6j+SXF6hc/qiecMgfiBG4HJAEsG/akG7p1Oz6uRroedjIVxfaCSZZWlW6mX3BRYnVGkljJU2fK9/l3osjbovg4cazz8APd99NoKdrifJVzmaWLsRTZcre1Rd5hGYmUor5TTlqSwYyZCJZgJJvWjQXru1qCPtm473xFR2kwbUQMS6pP9TtZLD7Ot67zCKozPtZitHg9RB+uX2jQ8hn7Fite9vD4Hv8v8FT0C6iosrbcwcnHG7eSJUGWKTUiv7slId03lHtVy58xvwkPX20pGdTNqK+TbAjP94YohDhTp8uoxyIz6KV1/Cy+DrC6DpgYyiEUKUAEyg4xYmS+9i5bcTg/kgCpsSuDS7Q4wF0DOwWxtiZ0NVdTVtAIoS5gNL5HxirIK+KguHJqChPU9je96qZH5Lv+MZHPsqaMPFF3MYiqMx7oM/GCP2t07gHPMb2Q4Kj1j3S9tVSVcYnxnE790amVw6NzRU3ECuBIcF/rLtAUFymtyxvo5jAAXCHlfw4FdPeouS9mzi/mDfExIyBS0oMd9mXiEYvTHz4nJ6wf0lR8862gqYzaW3/9MULz1jk+8+7mwH69TFMHhczIN2PBIvD6gYzs533mA7iIFBs//lMMf7/MpgF592wM4iRByMWmQ1f8REwzJeyYR6fbcyjRK0=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: vroom-staging
    type: Opaque
