apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - cert-manager
  - postgres
  - redis
  - ingress-middleware.yaml
  - argocd-ingress.yaml
  - observability
  - kargo-chart
  - argo-rollouts-crds
  - n8n
  - runbook-retriever
  - kubectl-executor
