---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-pull-secret
  namespace: vroom-staging
spec:
  encryptedData:
    .dockerconfigjson: AgAFAjiWiZMV7eBUtbDFjYWQ6//r/b+e8sarLeT3wyNi8WapcmD3kUqnxAsz1US81DNxopgq2JlHeR+6bmSJdgAfOCsSbNWuqNlFWFDJkOP+FZ65Aq2x422OWcAqTO3pyiv1NulOYN6oNvBZROgOTbawV9TqnU4TZ+C6ZtL3IwwvyMStqJnwfVyTrqEllWXudFxMFU9rWapEULmVO5pFPzitKDs+KxHiriyoT8oiAIGQzMMWm3GddjxNB6fQyBIqPbYxym5ym1TQ2WaPicxgq0Ikz26wym8LQf5RBEAOqTIbhSHBOUdkKVi6Zh3gpNnk5/sHb/tzpY6dUI0y2+3kN4FoWe0oUPsEn8Kd6T3Az0yszLJAG6he4JBRdKFmR3kFeWyETCM+pQAZyjBkOynG0ki/Gt4Bpxhl9kuKlvPvW1Biyp+J5DYGQJis847xZfvRQJJAO7V5BMBZmTwakUP7MW5z9iIh/yJoH+B2twtbMSKhjUIzZHq+pY5BiYVD49gMRMbNvDoyFQAKP2TPVYv7zaAypu+3419DkknZe/I6a+W5wL/StqQse91ifBCArD0kAtXS95VGSjwJRAUOJxeMUCT9Y2kxkmJsvkZcsx+KLgixIoykY3jrR6bggzDUrdTcnOPoQUkvdI1g74bfvGsKYFQTe8o4LqVKOvIJsGhJiHDV2IhOVNXE69iYBnkWA7uCIPctuCHaUMUNFFeBGg/06gWPHyawQV06rtUFxTsXWaziu3xOSrlfQ29APPpF1nO6kZE9BTWMP/sjdtpr8wzVzWPLOMJi2JIBJ+yNxk8Vp5LX6cWzsvjD+YMTFTlE9/2gcqAcLmULmj/7Okcm09HugoJF8MvMBq+1TodQ/6P/nePAbkCz3sYzHoHKzZiZdAHFscoFTNOSLQw2lTlhus32EfYz7N4oMbV3SwU=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-pull-secret
      namespace: vroom-staging
    type: kubernetes.io/dockerconfigjson
