---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-pull-secret
  namespace: vroom-staging
spec:
  encryptedData:
    .dockerconfigjson: AgDNnvTOvBTiIQa+TvczsO5YjOeOnLXQwEmJrc3ZQ5GbT2AFV9Kl8a+JVGNGdVQ1S37oz1Ln5YqCLgVFFZxkDWwE7Qx9zOaS7L9yN41uSop3OQpy5aF0ucJyQazk+Pwcd91Mo8aL4cNCA6X+P2EmtCR84GQ/en+A/Azf7o6aW/HuXwmXJia1mSM+pS89oG9Hn3bfWRnvC7YLFbd1u21sFKnjDqdtDsKAFIbLmGG9zAuW7zFhanpVO0XIJGkzcIehIeNRIOi38MtqH096uf8gIOM1pWZqnqVswIVXH3Soa8kdsPI9dAycnHo6JToDhiUalRHV178C0SGFk+cEtKw105fAbWaj8bN0PhSgHCQ44htkr/sgD+m3+vQTHoFNTiawGAqAuw1NzuAYPZkwYxnjYY9JGEaHd4lvSRYS8bqgOR2ddJcAoHt6lOFvBrm9P0uFi4SRFZbrj5V7x1YPh4O4/IqPjznwlU1hXlpUkPQB8PSA1JuwgfDxThJFfQwCgVUku17YpQgU62VIs5VqesG6raIdWDxFLeAkyErgJIU/RXxO4sTbHvvB0EAcr4B2cd9KXtNXMcs3/m+OaZXf0ttrgbMu4yYPFnE/GnnX76l9kObQiCM2oFcwTSRdVvPkJG73s9Mivvop6Wn96Pxx9j12jcXPpokqNCNlOR1dkSyiIzET1OM/ajLweJY3ngcS8nqQqPuST2D8aUqS3bsqt8FA9cO2MT6Mq5io02JvSvexU+D+P4cxi6SU6mOp5lc2QNkni9LLlUQ20ynA7GY3s7UW8119N1U6hWuo/OrIRmn1pr3z+w15fNmzm7g2sxG+Lik2x+XyNYu8YZoqWGzSr/y9KAAF+134zgAnL3PLmZRUrzay0JCxE1ogtGv+WGGTEmneNyHvb1ho+f+Sy7FWZ4SzNyftG5Ump5KsO5vsqETuw5dqKAps+3HxnhnyNyyNytPh2X4+SIqMkMBxvkQu2Mk3OmnG4uzfkVVruTi7Og39fHfOg4+a6RQ=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-pull-secret
      namespace: vroom-staging
    type: kubernetes.io/dockerconfigjson
