---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ai-reporter-secret
  namespace: vroom
spec:
  encryptedData:
    gemini-api-key: AgA9JqXQ+PU7XsFI6S9Ov+0uDJ05UAklxIRfNXe7ektMfU84Y/Ad69prydgOsC1VU8dBDXHYYVnSbCI1N5qOoeblWKUMtzON5PlhTQygIMvzk2VDCz2+BqRbJeGLGb3HrV5HaK33G1w0Jx2vyVBC2QBdIAOP8WD6RmDgFtOxDnVGjejhv2QDdGy/f+VZh0IaT5jWQLxPkE8c5JV9RRCjAK20sS+A8SS7OGQYIhwZB0LfCbtGjdgaPjTBitPsScDRFSN2blIcfTuEkDOqLbd56v23ajrXddJnIOpPwfpELLerKUAJPE0PHR4tUINovmK00TC95wQO2kwbYaPmBohE3Sf4ixB5FBceWg8sQdDJCPOhsJ35jz+f8EQ0DbYdC8fdc+Z4Sh3KuFVTit/Oig6f8GU+QhxBw938oHG91oZU1RO71R6w4Smt22/7PMMgtPNkhGQN9ccn4WMqp+X0SJnsFWebT+Ahzk3WtZdtKyhn9IvzVszqN4cTF64v7O0NS4lse/uAw3XUmFRajWWKsw5q9oVnYEqFQPUgQpqAWUhrgMPUvVhlH7CbNYfk1OZyYTR1XnjzaCxh/yctuY696gciIEmaOo1P+7QvyNFmkur4054cyOcTVZP4OVijhTxpGIxWfB6dKf1S0LvCV19r+NJ1JXV0iL6KISywlA0onCknxeg4gfGGrGxC5o5UWvWYLpd4AVABHX1UKu+pme99u+eFXxrY/6Rcu/j54yR7QTv8lxfvm3BwuxNjKj0=
    slack-webhook-url: AgCTUrv6Cjzdb3X7KC9m/YTvVCDBowsb/FvDB5xcQ3WijcRPPfWn6SvX3FjZZsxv2gVWc8P3JjJwv92XJPud4HvHPs/MKeu4qpLf5yD+YA6hHa6GcQnf92PWuxjmpEEn/XSinAN8B2PBssO/2jVdtgs8jqCQyrgmO6zGveNnq3XPVpKd8FRs5y8ArFviKdAnmPlomm+JusGyT+34KBH+xL0RzCpQ+K09ze0OFqoMiwiz4vJerGXyg9Ni81SlaqGtQibzzM0swT46uEILiU1qZZn+bozhtYs+tmLOlHDIqyGCEBrBZJ5RJVDXj2ZfaqSslRTBZA0iEZKJKXHEtszDxWBylQQ2qvjUdhE39U3W7vrIDWivGx+bk+8biM191qyjkAcxv0/OyH5kkoxtiP1F7XYHAadHBNQq/s43oQ90aRGxKEtu9cs+01AhT2ePLcEPGZOemlzCLc9ve82wip4lR5etoqAgWmSHtb0I9Be9mDZGYkDFkExVS4BoWerD8r3ycmRUn20M7V6FfaAE+KoJKyeRikPk5XyCCGuyWRXSrJ6DLyQun0DMIKRNbchfBVQKaQlWTCvwNhIFPp7GQ4G8seVyVjPzc/YuURx2FxrwaaEwJrxwOL/ZRQQb62MVv4OwHBZphQmxhiPSykH1uS4LFa1RFHU/nSiDudeQ29TMqwLTFRQuFK/MxLlw/AwaTfIc+5vwvY1R7thuF4jRNP0fJ8rab9NYcW+xHezSeVI6TxFqdiPBpeOwpwZ1nVFeIEDwTSbc7kkGohuxEvpd4EliXpg9l/N+cA4G5OriAtkI8RFARJs=
  template:
    metadata:
      creationTimestamp: null
      name: ai-reporter-secret
      namespace: vroom
    type: Opaque
