---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ai-reporter-secret
  namespace: vroom
spec:
  encryptedData:
    gemini-api-key: AgCSShvFARm+knXnYEPbOKNme/e5QjSy6pfUT83QZA462UDhAMp4lrs9YZ3KqhummEQTL0rlgVFnE7dCxbNgnDSHGuzKEo5Z/46eCEliPdXYSTphafWq32TXgqcS7K6fZpzaxfShsFYx1LnpUnyGicL868Xr6aLPP9P01va+s0+QD3o2qtUvqV/ccCiUyGcV3icEMmWAJjcilg4kEg3m8YMocMYDIaQsf3iHuuiZSglGlBbajHrBwyIAPQF31vn8oTzg8yNQc5jZwd178qYZFF3emxta5zp0EYX4g8E14RunxQmoKuoGxs2v+yufUy9aOezWKk7k/sw9u2QD+I0t9fjHKbPwfj/Lmx3FVCnJivrmLgGFkOyVh5kikxBiv4CCH9NHBX2n8FJC9M57fLoKlxI+Bxai2WppDixA8aTrivbfzQ8+vxBW5ibYEWv4hVP4CnRT7q7cg4SHs50AC+aAEefnDitSx6fReiIt8E+IV71KZOI44hErwRoWORyDyJGbXZYa0sShyIoMPOorp6SITiHNeCfeuRr9lIS4pqcv++C3AMBPJBiJaNnEJ3proOkF9DmwFT0IRZy29ZA2239TF/jDNFE+eMh3EIIlwLuk0WSpaFEPuHKY23kwT2OR8DD3yU+ryiXz9xXjxPpNG9HZ2ZQt3FEHDa9L5KtlRYAI7j8F/AydyI5iLT4Vm5Bp3tV2Gi49xT19wmwpanKMxABK5sooOzFLCG+Afm+MF61yu8cIbbj84GTMvlQ=
    slack-webhook-url: AgCbfvUAnF7aJY039hnqC9JXZoGovJCCj+XoWyXz61ck/I6GzqGxeG8Ir4PMAZ99zbPbrG4A7AG3YcMcxTYObF8jkkhZELdRPS0H8oEs6v8q4hugGmSvIUM9zk05Rr2jkgQd3DtFjtArwRwjCH//6o6vBRhBt0qLdj+jZbwA37a3AIwy60IafPnOi8gIVqowo80o/QBgJoZ2ojtXBs1oqJUuRtA6nsbfQ13kBo1G4BCSDzZLpy1LDdrCIJDbl9MDm6Ww0voDhiw7wIxQInx+JfW7IuTezOicF3HjOqEOZVaAVjpsHA1hvtF3Vbr3gMY+e0XrRYNlHD/0og66fWJ2csXFpaqnIBRhC7DueRiItDzLXvS0aB+LtDeLN0tmC2J4mkckkGCJXuUHAMW80r8LefqC60s9m8yD60kZegZW88UpLHa/yrIB0htu4LKMR0UBmTFkfDdmOQ80MqojgPBw0cd10eLF1Js+s+GtJexe1BOiMpTi4Ub4bL69jtEAhVHRt6kMn5WBx9vBWCQz7zkFOvKVZKV6Ng+Qf91dQ8DVFHRTLh6tmY8RJ9NzIFoh/LIgxPZqEOFzdhHhV1cVMcpNVtwZVU+EpxIRW6doMwua33vxw58kpqE/4jO86qDc71jVqOVESFgOzZsxHDfxTRiIFpO/q/1NgnMh3a4ySn0qhyPqVyoNKfAOC7Ukd116Cio6mj7yRd7oBrewrmA15MW8B+HRYo8GXpRsR+QmBo9TPXyKrATdhBRS0yv1sMySLjoCQt1HXm/X3XGCrNOQ9gO79xZp8dbSrG/CkBvnj5ud2VJTIaA=
  template:
    metadata:
      creationTimestamp: null
      name: ai-reporter-secret
      namespace: vroom
    type: Opaque
