---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ai-reporter-secret
  namespace: vroom-dev
spec:
  encryptedData:
    gemini-api-key: AgBAe/jUm2saAIZ+bKxIdxAnLfpNLZWBBeBZejw+CcsWTN15cp46fjpnxWZSqZnE2K1K3KP9ZzIgDP1XaBYCNDZN0gDRaThMV0Q4IRiICQ7KwHgcdke3R4q1IliwESNiAWMmgfVzwQRoWYmGf0a5PUDdbm1PjmHHggJZQaT60HE/fE9H+uD/KJUzBjaTXg3qS2fyKIRS5HZ+LRfcyq+SgMKZoZvdUu5xlypsNORtjj/ShhlcVUaT9HEv/QVAsvdpgCFYCfbXM1+sQh80NXmNaunJp7hOEo/u8lOkTw7xaIz/tk5H76Mh9iRKjaqqXyYlTOt9pu/cXGJzaumPtVKSR+AhYLCzuIf1OJ71qngzJwG02u8C+4ERLhWoN4SbftdcFAZt8rD+WVCMT6nVDi84tQSvv7rkcXMg1hIZVfn8BBxobUm/6Vl0yTqNvgesMDnrLHh3XiD/3v/hpn1yTGWQV3LOqIaPeu56UP5iznmKdWJafAN/OHSGSWIAG00D/5X5Nrk5meJdhZ8hrc+L3gGMIrV9E4IDVSymC53cXBYpy0XjpCHy+bNB9ImYnDCdtoCz0sZDgczySS+IGKtVRQy5+JkjMv8qgHCdYsR+ZSp1+Gm0GvVBMkAifjXNqzCqSTShsNMFQOH/I6hmWcw6PGmTW4BBXSNzMtKzHUJ5XDvckL1WKwoMUPNNqcFmWBo6Iww5AzOja2auhN9phnYPEVnCLnQaJmU8jFa4OcFI6EpuyqhKDdsoDVEZhN0=
    slack-webhook-url: AgBo8r/aLjYvML2nRlNQr/VdNsG/lh97GcD4bljH5sOKhbmDy6ZM0z6XimEFC6DuEl/6a4WmSsvLJYMbDdCQsMzVokEJviW8R9PnHotIHD9QqESjoFIs6ijgIRJnXVcvpOjXjMV+02PRFtqjPsyLLnxhAqvm86ca3WD4G7FsCZnMhCHHqlRimnJ+pLm6tqc3cLQbC1CkHYcv8kHnGSIvMdAUS+QXZNMNXncIpp7OHNgq2MhJqKXmXC8jWQeP8kdxQWnTce53V/38A/Cb55mXaL0bgrm5cS7w5WgyDJ2/I3qIdSvHT7LpNPDoBTPIHLhgAWYIBdW/7rs0Lr9liRgn6Eq2qtIJXU7jaXRJGLCStFHpnfc9d2z+4Vw1a4Hy82uornzrTZm7/dvROln/9b89j8XIk6qP8D1kjOWwRHuxP9R2bAdwXi4yUI1wba4BuODzOA1fyCMKIzeC47x0bEse9fYM7xi567e96GQmwVIReNNBEpHi7l4GQ+hOT7/Gw9TzYl5P7Uvm+17FyUTRE6vUk6M+mjXrKyzyJAQ5UvvVZ2Frr/KHABUVnHLE5jJKn2OPRqhwDn4mGMElvjOX/5hke3n/kVa3pnLJf9OY2x5XiAuJt88NAxZ+Qcx+adTj5GBJxltae4yWEAPkGHq8C+d3KKhRZhvxwnoerixdexhLkuZaf/4tDcvBeHEE6Aw0FM8u1NpcCO56L1UazS09zRDDlH3MI5GJemgYMjiZ9/TNE1iKd3ntqdcpKDTvbflPgh5nmbludckDs+nzY5iCeWDLmgJJWIpbv3TW0lZsQCbN6JjwYvU=
  template:
    metadata:
      creationTimestamp: null
      name: ai-reporter-secret
      namespace: vroom-dev
    type: Opaque
