---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ai-reporter-secret
  namespace: monitoring
spec:
  encryptedData:
    gemini-api-key: AgByY9vTiFkRbozu9e83i85irj/W3qd/TWxSuZLzv+AWOUOtc0eWTNCsxjgsSRbiSpxeJZ4UKNsfebQcjTXdg2DL0Vr3OCsvs0sYaTANs/6TSRH3ydI+fYV/yWkrPSOLtSaBDLQkBqU6vO8y1o1BgXPCRUDiKcbUBV6nU+e+feMigw1C+8xBtzXqGwSed3EIxhhv2ugGBEXp+3PacM/+aaCXdDZA7WkRF0sFwciNBA5k16PMn0gosKwuDTiVuyUtuY9fETShK16BedbQwhSunGh4rLWvH2dghlMAfEDdVNLPv1chexfeh+7K6uLqy4KeO6LLdHMdNdlMNWhyidFcEQ8X2f/7qpEI8g0/3KjNZBu6KhzdQWBrig2dM0vML04ZCOzZKxHES9QgoANytFHS4HB1WmU9dNJn2ed0GkYCoSJ1aQwsjbf7yL71blS9V+vrqHIF88qgcMZwV57yvts1pizvxVgWwpHh+CfckgSOTcToMdtfuZVXxJaCfavFz9lU34TLTy49o9eCuebFmcFhAZZ22ouVzhWTujDZg1VIzFsbty+0I/qjLsYvhHSC9ll2gJGRyGti7b/hfdI5NwIvYMlJfck6YaD1cEi8Gm0N2sA70rUaniw73N1qEGYovX0zEBW7sF9pv3/2zVlW60vEHP2Dm3mjWZPFM/g0AW5rwSLlCikcmf87hjy/vLFT+cUh7j6tynC+nZ47/1m5SjP5OMiI8r7sKT9ES2jJ9blg7h3RFQDcof1Z9Kw=
    slack-webhook-url: AgBKhAEfPidLJK+rO/JtPnQh5yj04DoPxHhBDl3zfPYJs4D36BKmmWPvJd3p/qVNJgfydtSeTFLDhzOqhRaKLwvdFCoEDa5FMwKqsRMLad2NjBz/ZNly0/XI3XFaUZd0bpRb8JoSnGySLB8fmx800eM0mg23OaNnDjt381kQtdRDS465mtORnbEn/y16NKzQSsWTecib6p41R610sHckgYPG2ucKgBuiE2beTolgyCc9Ylkb28b56CORAo9bvx9bX5lb8C1+nH7ULAgdB7wdCiGmK3LJYi4d54fzJ1ew0CF5VPTJNxs8tW8irUB2Jmf/ouaCM2U9UZ2sNYx4mLhuRBMOKUu2WsmXgLElL4wv/FCFl+4h6PeFFS8ZtYajGqMnMeZsTNd5PSlzd0I1/tP09KpGuSWGPSC2qOvQtSXCi2XHPrgzFu2EHE4TnqDwVk3Zbr+RdzihbagwJqABCRnn7hjM7DpBBTPQ1QQ2C7kICfCxqoNldMhfbJf3j4FTksZROBwK241ZOdaSOaCuYuFcQwv+kMJAxlQdO7EtM1fec16oM8y+ukob6cAh814cE0NfgBoo711dJO06qysXmR9Afwy7W71CZSEpdKgY4rNmqU51q5yk2eeYGh2EQEM8C2WYG8JkRYmKkxeGKhHbfZIIIh40rzxs79/w4V4eIXN7xmey397SacL1SyEt1pd9pT1wFi9APmmsz9VtFlWbCYnlG6X0W3CQuLXfj8EIyJtereTpiAZziqH0/dRXMGPVqBbjEsl+8ruK0GvP6liXR9ZFbeCmI6YolB83F609yioQRb8sUlE=
  template:
    metadata:
      creationTimestamp: null
      name: ai-reporter-secret
      namespace: monitoring
    type: Opaque
