---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ai-reporter-secret
  namespace: monitoring
spec:
  encryptedData:
    gemini-api-key: AgBbrICAjkjwxYM4DvrIOK5J8HrYzz13uA9f7NLekcMiWK32sGtlmxym6upBDwOPaO7libZwm3uwOHvno+YyVToiXqfMZndHgto0ecPtLvmSOkI7YD0+2vMTamKMh2t+79un8qUlaEq+31481B3sgBgCeyoOU1eTv19Ga6Dtt2mLiDUybQBIyBaOQ7YSaO7x0TeWwU96y/aneS9IVrEpPqJmsgToR3xpCRowQoLeHMVw2EBQVmXwg5it/G3zs5mjQtazx7R/zmUHViMv0MDG1d7cP1CCzBI+uhIRO/72bZHgy9fuAOf+7rCvAKwKLjIMKudvJpQtQkMKzUrmfMYAf7XIWAvSdxttXDk+OF6vDtjNMvQPQpf8JfmX+3VA1JSExVHkO5Swno0DjDivp0XydCf7PL2mmZNm1cbLFF1RBBqaRaxDvS9KXYkeBauuJQUXisQzCsmDzhbs++J5DUISJaZBvaH5OtbZPVJnt9zWi7tMmrgQbTHkmUvH5Y+URs5MMJV/kYh+/I6QFXQh7d0pKXGSdsSOJz1SyWceJl5qKgg43vWocibAs93eico925yDQ+48UcIfAgq5+R5ZajPi+1G5KPpJcBYMLkr2TC0UMGyXPsnfzU+Besr015mZTMixS2PhY7zBSg7qM7eMZGhx75S0vaYl8B6Mo7cNQZLeWOIp/lkUl1ogdtGXUn+BEvHWSf30Ulz0kj6OAWs29OjCyZIW9Hud6y0JpxdRH5jRyG7hkGEhvHJxCHE=
    slack-webhook-url: AgBIc1Bn2rmzKh++fJ9ii1Wy0oiZ31GHytGBJO4iItwJLvWMscPzBY3L4CT68XoDw8pAGCUQR6XfHucVXyop2/adkOLTGMfn9fHTd9XtPMKg4g7Y9/9RjukpGD7LK9q5zA3Cf/9yJlprOCy6y9o91PMuWrJ0Ht257Rb8f1ucSPScgN/IKh/IMHue8dV8nl2miBqksBmIe3NvulubeAoIBCiUg0m8Lqm30xmZPsiqqD0/IDCHTF/34jGsRftBfPsd8Q4F/Cx+Sc7ZHECSmkIUfheKSWGtPhn368A9OnmYUqmRtotZAINhpFUJ+5zTd7yzin85uRdnxyj9nNdqTc2nCPPdEgMka7Fk9gl9yXSbizbD8FltpTJfOX1mYhRk21syufAOJaFzfG5RtKd9r41Yw1ZAX/RejYR0QjE7smMyhGReH6ZyQv6uXom7BZW63sDVAm5LgQfe0toHo43vttYrI7loXIjuvpzMDFmuxUFblDnhuuTcupgLMWBIS1KgUkFOcJQQ7Q4I048lKQHWig+F8eJ6rgB7lSKj5F44WbqYxbyWokVlx4bvaElcFFaSREsW/6r+qHLxtmu0P+zkpDOPOi73J0IVBA/pSR9tJyUpYItueVGQIb2N6mwSt4VeajvAUGSKxoxE+LBMdaMh8Oqb+SXXFIf+15+6bVBhw2eiuP7GO6fe20/8K0Wq1ze1s67Qn7ZrWaSMSFhqnY/rSQfVZjmiYdrW2F13KihGQQ4NHQI3aFnaX4y/VLLXXVLzBdUfdUq/g2N+lno/s+p6kg7gXtuslCoL0CQa1ndIqSkpNJNDodc=
  template:
    metadata:
      creationTimestamp: null
      name: ai-reporter-secret
      namespace: monitoring
    type: Opaque
