---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kargo-admin-secret
  namespace: vroom-kargo
spec:
  encryptedData:
    ADMIN_ACCOUNT_PASSWORD_HASH: AgCFoY1dgqvNaMeKWPlDRxPLMEwDdX38FLj4n1+0Rsw3G/cIc70nzNosLxQJYzSKPf4zBSCMgC3uqG/xYD8Q/1XwvnPN45uUuk63CkFgsPSr4Po2xrahY5oOQQW7bTpbPCNcAZMLeRV9oWkvc9RF2BMAvFDblBgFrAxYOQz+kMQq2HUjtILDkpJVbiljC5h1FvHGpi0l2l7cM7FHRhAr8j7mmMQR/KwVx2DBdAOHRv5OlEQPv/xsGS2BNJGkMVT8vDJWXtDnJmXCNIeBK3m7IZ2ofteZeLj7FGLn55ZFVYRXeZA38t4xF3f2j+oF1S9HE5wp3UsY0j2JcTBTfuS0vnvjWWzB+4dTqMQlv8eGEqNQiQrcn1SrnosapioZk8gUxoT7gl2tLNh+rrLnXmpM3LX2waQ+YVwCvDzGzNXFSODibRb4d+0pUrs0RxfLVoHDBq6+3k9YUTNdPisOrtYqFg4WHGIfqYHabMyCYRX3DSrmmQMPCYUbBe79np6tFnrdYaywu/VEhMYHy5KoIAkvD/XY/caYtcAo5AHxAJbBnbzUjMbzn+PIrGaDxEsFDrDMWM1jwmTLVHOXpV1VyBrp+dxwdUCy0klSJ7V1Sfld3U5ANVw8IsICVKmQ36xAiZSQw+4ahjZzPkGXguBPVJjTx6R7BUX1mJ1K+SFsvtNh0ku6DVfnrUlh9tGAVAI9YstSfyYkw+1kacql2Gv0HcNxkxALrpM0iabM1+JW7D8zwVi9cdWbLmmOGtx8xJMnemO6HFVRXyG+D3d8NhbPtYg=
    ADMIN_ACCOUNT_TOKEN_SIGNING_KEY: AgB2B8CJrXMETuPM/viMrRdpqs1IaTsK2GY9eztRzDOYHGPgVefyqaIy8IcFPtYZsdwbtE9cPUhQ3Z14TRPw5iDW2Zkeir/Fy/FatQxRmwgSDwYliTmZz05BokrcONJXhFbOEwcRdpkzrnwn9TgJyJUJjW9xDjwtNt1SuR8IePUS6HyJmP1zmmRdTMwUt13qaO8Lefoq2huA0eQK8DdxECidkCIN+vhhXz/zx4bqnGKgJTNYk5Waq1qeQPu3neorX3lP9baq3KT8/O/udRgWDVrUhOqVp7ZyKUqO+tCxrxlcKbgjcQ718tYoAH1LXW4eTRmNbrNjtsPITG89j9yyjCkjhG/tprdZ850FdesGmPpPaw8rx6TxI35tqGO2iDt64jAdbyHE4/GTEVN9VAsHB3EfO674fEj+bE0uCrSJZVgZ7ozJahLqEi3j7QuPnALJMmqsdTKqt1+yFln02khPzSTR/reh/2ZvZm0qha1/mpSKJmIqjyzjAXSaF49GKZK39CBHxjGYicocHMVQ8U1rN1xHJCMi4ztCDfWqVTW8Mkkk+uwsfwODt3j398Ofa67kgG2v5K6XRNKj76ZL37xh491RiPmmnqsPWtd542x2WjJr5USE7iFTe1GF2iqUP8gWFsvdpiQrjbD7EGYIoMVEXhJPzH8CKoKAeALBCJCb43KoeCS8Lij0hpXwyToFPYBGQ4/FMpTGgFMmHDAhGEJ2+3KM3sA8jVpj3T0VYsgyGglALn4h6vpqXlBr9oXefg==
  template:
    metadata:
      creationTimestamp: null
      name: kargo-admin-secret
      namespace: vroom-kargo
    type: Opaque
