apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vroom-apps-staging
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Ama2352/vroom-gitops.git
        revision: HEAD
        directories:
          - path: apps/*
          - path: apps/ai-reporter
            exclude: true
  template:
    metadata:
      name: "vroom-staging-{{path.basename}}"
      labels:
        env: staging
        # kargo.akuity.io/stage: staging
      annotations:
        # kargo.akuity.io/authorized-stage: vroom:staging
    spec:
      project: default
      source:
        repoURL: https://github.com/Ama2352/vroom-gitops.git
        targetRevision: HEAD
        path: "{{path}}/overlays/staging"
      destination:
        server: https://kubernetes.default.svc
        namespace: vroom-staging
      syncPolicy:
        # automated:
        #   prune: true
        #   selfHeal: true
        syncOptions:
          - CreateNamespace=true
