apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vroom-apps-staging
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Ama2352/vroom-gitops.git
        revision: HEAD
        directories:
          - path: apps/*
  template:
    metadata:
      name: 'vroom-staging-{{path.basename}}'
      labels:
        env: staging
        kargo.akuity.io/stage: staging
    spec:
      project: default
      source:
        repoURL: https://github.com/Ama2352/vroom-gitops.git
        targetRevision: HEAD
        path: '{{path}}/overlays/staging'
      destination:
        server: https://kubernetes.default.svc
        namespace: vroom-staging
      syncPolicy:
        automated:
          prune: true
          selfHeal: false   # Kargo owns staging; selfHeal off to prevent conflicts
        syncOptions:
          - CreateNamespace=true
