---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    slack-webhook-url: AgCYczmqe4gPMoMeMmxEogHLlObr0RHOeaOKywDFtlfsr2MpRWy16LV5gMPYCGkdYfsOfoTpaOLX5JD0R+KV3ukTi1LtPGHhHzizhqqInxnQ+VGj5xu0sLQyeypfd7XvnBjjTsAFLfiq9DHuY5zuIjDQEg41GvrNpnlrp6sxlX8kJSph42ShXvmsTGXVc1+HJA0TCWhqLbZyN3BZu19kvmJdyDYSPnvmdcHtxuEtCeWJbOOw0Jm9UNwgNe7OZgfoZs0lmQU+ZotV0edE5PYIv4lMzk72N7L8yexQukHnfvxG552G9oNNHhmM4Kme31ubKhAknonLRIRxnTD9tj0Gs2Ij88quiOnScoHDyrS3CtkOanrFDvMTX0+RqGYWXhgv/v9UTlkQrqZA+IKFL1i7bGZJgKCk+66X0rCkwZwNQdmZPw4lGSOrBCXw1yLw5KrOmvAbYD4yg0bYEUNhudmCxuXw8QT6ZmLNRmT2K0P+6aZ9NgIJh8tJOCjEzXO9FgbAZzzZL6FpXzUM4aSWeKg6Iz7t1Xm6zNty4SquVXUHv30o9bE3ATkHuCL7BU5mVebrvc6YDwkV2TDM3IsepYpMCaPbSlPvMgFCsSxDPnuVveq/Mhm0zS/j7yzE/4eDQ/uwwL03J9iOZjVXgNhq0YYiImj2OFDDbLrcmai/8hRwKfIq+/FfdaxloLho+y4PJxJAnam5OBZMgcS4kQKHKL+y7lcQ5hGLNGsDAhK8bCD3tBoW+OPoENhtzdaFRHQfPVYJW4xXVGNqnWRdZcrDm/6g4uQAAEls1xmRXVAJseo5qBuD+jY=
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-slack-secret
      namespace: monitoring
    type: Opaque
