---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgASCIxMtLiqIsfBi+UasouEC8zvXP7cHEtXm/mWC/ng5QI9CynZIuEcml+MkVVq1JKomG4zi5y5P/JQQLG1k8oX63CzQtBBNnN8RcFTmRIl167vVKsg8o7fUh88OcnPl4b+QztJOJUfGduYZLW7ELsf0ErD+Akd6JFdJl1ty4SNEFbyrfekZnqPdlpoyIgecSMxtiOEcETjytw56l1/ky+kDJKAF5lJOXALf5zNHMKpuWIfCVvD6AAjfklt/PZf8icfUPdkn7MrKHeDd24eMZfJTASMnH96iwk5o5ZFmyy8ghc6i6G7Ust+noXlzBh23URqgkdQUrf6cJzpvtSQtAVJs/ZQ29t0H1Q7a12oDwuOdZFfs+51KwgvOfLx2GpRgtXK7NI6rDAiMTrQKlBZ0ItuQIvWiVRpMiawiyHqovy83jCGxPtZDIVZutqZ8tdkZMBH7TOT8y7k9aY1lwjxQdQJMPqZ0Vkqoyq1t6TkpQoGHf1mSxzQkpQlnAIs40ctWve6hqUFHbWCuvUO/z9xQwrXwIjPF+tZXk5B1oy+P/7xIKSKOCJtdbRvKbXFfd3TurIMdCwADP4L9SY5tHtrE8VmBs0iOjrXsTw/Wve1hWD5QP2WIK2DekKcy1nR0huQhuKV0DYQo8SSa1jktl7Wb7/XASVf2WX+XbV5ZyCYHX39upwuZBBc6dGTZBzTo6vNuR63y257r+8w1lez3feIyzRIAiu88Ap1XRmhBezml60HAoq2uK7T3vYW7g2564+wlSwiAXFDBs2Z+JG2V45sLdBLEPUq/4/bQVOjuaUfGPOyg36MvGPFRLPaNUrczXuS4LtRGQ==
    password: AgCnEODEtnEEp5H8B2cTqsCROFPTgMZgW0e24Tk75yeqSS0yM1FKzs/JHNeAk8PLF6TYFl2hmuJUSsTmbLNa9+JhE66VbQbRH195t2IUvQM86o+YyliKIYmCOateUy+zK7xVxrJkBPI0FAYm4bRDMMsFNom+BcYw5zNhdXp7nOHXrZ5SFI3m9VcjYfAdsynDCX7OFy0pkDZXo6fEufYSsYrKOv+Xlx1x5a3sp6WRXAmGQLBzgxnlq5dsJImikfBCMFReaOywMfs5DnyAZviuwbBxvEk7b2k/bal44DcJbQEtkUbjfG+YWnVioOog4meU2D2ard4k12o5xBgWckoCaD+fnrwyjlUi22YXOjIeFSX8ifccwnvgG9n3AWPrh4KqqDJGtEDDjARlFPKzaNCBC1Ix78IsOVxZEq+NZ4rBGC1UL8vZsSsJYDwWnqFRx4204j0FjNELDpYKgYZOKqRLfxg2uUAurUTBJp6eVS1Bs4QvGe+jSstBjwmUfEFVRcyMvAz63TrEGqxjGLgA19PdsZ1wk8a4g0iWS1dTtGLWBFmb7wgNBgOAB2naodZAFYRJrJIB0BokDI6/jW0L4fupumxwiBx6kNEI3ON7+W0z/nxdj9xkrAadZ9GMwMTl26tuwcvqEPyeSvWaPJPDfh08StWBZumCSPiTx7b0QIXcnYkLm7ZtEU9kKnPoNQ5mDAgSlMDYNBSLBpjaFhc8CStcDPc=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-prod
    type: Opaque
