---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgAe8yQ2Yz+KQDbQRnaoT4Lct2oEgWrDyuTHsfD5AP/Tk9b9KACExJqwQnS3GHr3lIFVQX8n56cYlcPtwUElW4mwg0RdKdCNrL10OccMcxPnbbTp6lWRF0bCl70Mz/VfGyxW/L/qXJ1/Xew/A+pcOl+wY7BHznd1EGg86z6b2BPJ2pzww9Tyx9/tdJn7ANqGryj/0mYHpSvsbNv9iq7ETNlM31d7ng5+o4Y9ev8DTOGoLmoERB5FsqQ4mvcj5LUgsrHPIcpBBRTaZ/9+T8z6rBkTo7LPg8ckJi/q54sVFIP/k3T6T0YkgR8yPz/Ka8sVlCWVO4TT5q/mccKfe5G3xpRdoU7TDh3wHvI/L4IuSU6lSaBAWzgLgpgSkMvnZT2lUvYs77s9/vrxmdqQPSLGbR2ohcKgtvxEzfvB7sk05vxj49y5AJRa00uh1e9FB5X0qdgJ7hrX053qbFvo1Qb+W7k5NG3C5gA/qBXzizZMITnvBlfFwRibAqFh33E5YbT86kjWicAhDNG8+fYZ0sjWeiPR54MI47AV+NQiMN2tHzbEybiP0Al97TvZEQ+RDzuUVWH7Og1Bq2XRgX3KW7TndH1alc+tyo61y00K7yftP0yzLdtSY6d7KIgh9f7fViXdp/mF+LUEcwkmgZjYtFoirVOXVcsohrnBB2hReWtern8UFq/MAAKakBjF+WbRWfNKiouO7mdELKRDSKQLTarI865m9c0SNAPAkUY6BHPa1dBXYexV1jOLUBBebJ4wJ4cIfh55ImvhXoB+iKj9gqaKMK15l45c0v+XDUvhuXrB7pMif1klrr1z9v6R8Grf3/AH8SNTTA==
    password: AgA8kAvvIVTnQGNB0CBeKJ1DHxZ8w+zxudfhptnpjbXlKeH5vHmSV2j5vOcYgmb0ES2T6jbK6MNJGb0U9dpOw9aJuc5xAwL9sv+PmFfwoKf+Rb4K4gnSLesLEp2uStWdrLErVPHe03F2iEiritXIFrZRAUEV+6AH3Re/RYFfh365GmOvHaVhC8ixDEUBoJ89GacWIbBTgZny6/erzWvuhUUnNpcYNmefvXKF2rm2i7mJ0o9ZUNCtL3MNJqOkcp5RYfIMZrDJ35co4DtC7diTn/fdccb8BabrpaQQesTimEQXAsUYDB9fImoG662UQeg9ek+x921ekMyUIGPM8Y+hSUiOpmKRUDSF+u+aD3/a9JeH3MsyuF/IV0XU2/4tSPLePqkQLWfJL+17ueeLX/OWae3t8aGwrJ9uAAcwkIYbPvOldmb+/1h2s0IncDne/+1KX6Zyx8PlozcqVcI3iT8BKOf4dRLLZW+aM/Xd9HP3AvfsS3X1jR/3pnnXhOL+PvC1KKe5iy/SPXBqfEQNAhWeFPrYpXSTT5cQv+Nq6/kyKYfuy6KMY01j1gyY0Nfg3T1I+lf2VZPT0WXjNx+WdG261XvEPX3o/jRzR7PDJ3iMkzY+IaQhRqd68AfchuSFNN25fQtECjIVWDsig80cioKDF4G1dQqYl0Z9FZAf8Jls+7a8vuZEwBJOWQqfoUhTSABxJeMfOxe3BpvbL/jOWglrin4=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-prod
    type: Opaque
