---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: platform
spec:
  encryptedData:
    database_url: AgABXGA/O2Ps2SJWMHBY45v/nimqoGL+FHXOjr561Dw3nv2VAzZKcy8qbNAEMXCKRJCLZMn15IQAu2f+L3sQT19iOC/z+6MIpOX6TcMME4IbftGm6trAkhlPEYAHD5ZY8wi0uyMFRyP36SEwOXGtC56dNSYXaDmljjDloRhlA5TwUoDqSF0IFFIYCRAll9c6tNGdbGv5pxE+OHHsomZ3Je6CvXAVSgwY/6kBj9XSQMYocpAtHyoWIAa2dZon7NMgcWSKRPHh3LJm58jofNW+4rbFiw+bjVFrYsyeCehAs43cnY9RPCTLwnhXHHytuLU24qLpO3vCe+IEsNhCiLpzeqSMwFgo9xY8qB55sE7y41TJqbWZuo6LZdKKnMgcUnOEzFezA6M8BgerKDSXzHTIYsc4GMnEVeGzPsfF8VP48aEuKQu5dexQV3FVrhVgaXSA+Gao90LksVFPKo4oJVsqJJMCr1cIbHQkKQbNwXYXdJoZltllMxLC5xs2+znShQ84cxaBtStu9F5AMyIoHrVWU2Yfo7OcDnm8zIB5RlPnYUEmwwliomlX0ReytAtKRj0SXhhBIEHzifOJ/u6NtDJuu4UwNy6jmxKxTOd+N6Sp5eRzv4Paht5jP/TExyVz8dT0hcOp8+Y+LEhS5hALyrvrIejh8GohHsFXcH6BejgbOSfXmykf0a0k4N34CtSZdpT/saeu96TtzSYXJT4M3CWR/YUnxWvyzGEXpbo5G1wU3wEK0mly7YyfQ2LprVRXxcWiT4OAenEc1oZtQNkZp+F+FdbfLYHKA82+DHwxbvJPAEaEpi3F2FZ0N0nT9e52Ah9wa4dV77Cg5AMVcMhwK3FuBEZ8BCM=
    password: AgAl+V1QY0AqA/tZfk3nlhnUDJIOdy09frRxcTOWXtgyRVolVy8PHPQrIIxVYmoz/HZmHxHLz50ovVWjzqkFyblRbCMVxSNAVeXDlrZqB+tjaTiSqRbI614dqpCfaRtvEuj8GWskqf+BTZ/pKu2COX3nsSv7D+fiBpxO0evq0x/CAMR6hSjEJNl7qWqr/jOU3y+SOxoR7399e6p7Qs1BhjmZ4l1jvP/oEvfnc+wygsr8HSlkBwSTF8aagASQzvQ+p/N09GRj+hkBP4uioQlDF4Xzi9zz5R/kXdiYYZWpPStCJgF4HG2KGBwXxCZO19JzOdNmSzE2Zx6Lh9M8WbtaQgg/Rpl5sncEH4IoOF8222ykgbh++Q4P4a8onzAADdgIqr8RDaQS43VazSnt9yG2R/tkYWFKvj7UzBMc4yu0eKLCi29yiasXQcQZ/X//Ny/hzQkF/mTE6h1qZU0+uKfZLLh5/3bUAuGZd69OkDEICCz7m2VJT/WMp4sJZtEYeu5ctTikJOAsCW4cdBgiOuOjlaDBBgMk7jxOL5evDJd+T0Ce+fwIFsa2ncUn9w8hk/PV3FKq+dD50kSv19QsFUXr3Kn0eDDaNaRbXKXpY9Tlr5I3QQX5o115fpuf85HUGVJlujS3p/C8amsEO7G0HboOjUXibMQRZVCQ354U9bEOKDH7IT5amozg46O6xNlS1GHGk2o68qXPvF8iJheocBMJWsjZBPOlOdCn7g==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: platform
    type: Opaque
