---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: platform
spec:
  encryptedData:
    database_url: AgBJ9xG4Aw+WCW8mSrHVdY4ertubxNbbIX3erJ1pKM2lwmBZdbE+OGhAXPRGZYf9ZxzRpJImcM8YPqudCrL33y/82gdiuGqvVglJJ2U+K62SPC2PkbAVEhB8DwVMjVVvNx9fbVtTo9moOo+mAKCJDobSohV9QiS6NYl39c2n/xhlThieGYAYI0C259RGmzQEqhsSA2EigExVulsQ59P71x5pB7rcwluMe/VOg7ytQczM1eLcD9uj3YzIE7A0crXmJwfMYVGZa6Ejo2ftU9cSmzVSBs9sMMn7Ma7OJ5omAGv6QnVFfp55tmP18MkzdzCkqxJzoojkdfPo3nUKM/sD74qJnuBzZ2NSdGaA15/ZfE09tGtKGkB+vX37Pn1WTjpHB0sVJ4dQh5gsuEUKY7CLXB0KsFygtxxSaE137qDgbNhh/RfeS5q2UJ01qn0pk99PZcnw+LkeGTVQOoZX6wHdruMyOXI39pzsaoOZWCpN5EDoVSRceI7Ue7zTXmp2PVoBslbAHfWP56pjymH5kwX6vzSTAAESffLQnoSKJrWW2Bx97ef94muoAzV+vdII1mip+bdFKWshezFCoXW86sDTIpymLIORSw/CTyK51ddtiynougVTUq+h4nv8KyxJ7I5orKgDNIK2hIBx3jw12gmBsdgyDYEBl6LGEhSoSS7tiBXeF23MMmMP1XvfsF1aL2+YEFoCczjQgnJGwKDFyHW/Td5Uks+6/4NbGysmxpUdOu8IEd2IDPLZEuSwPC4zZxWZx4YWis3lauDi/syTMQuTHZgJmAt6mGFVIJu58EstUBgfj6MyILe1gf0cvI22D9QOfiDqQkdX9+ixsXIgoSBLEGZLcXg=
    password: AgCmz7oRhzeWGba3abYvzh+nWlB3/ggIenIyktlLgdw29Xmri9cof9icfqxWItVnJZcsxKZocGHgF2GaEpJ0u8SajBezJDT993J8Vbp2obO+nQL9iekPNXH0ptx+GZToaDc8SIDRHyLke/Yt2U5Qu49LkP2wcrhDJ3f04VLzrp0h4LbbcIXDFPPTafH/vn7eQvpF5mhtNhJ2EcYsoIacf93mBPWlGJIJaXukXl6eQznPohoMMiS3omFhPs48XZ8TISWf6CkLnc+/Ex12Po6dGPW2B+Qn6hmVnhwuHEVyxgerZsfGQm1Mn3KbL9Mv+APhRJN4jwHZPET62uMqrNz/xIbL8xAYbb9ellANb5bG5YOfTB938Lswrmipp8egdAdExookKVGnhjwtg5o6Od589J4+DfelzZxJ3u6+53DfaPCsy1ocl9uQM9dgkuCS4oguby9jsU/+5ENYHhJyzS2vEHgTnYhKOsvQLmdU6/A6/IZ5s+25Mqst3+1PG9jDeqKEB1D4U2HGuueHABBb7TAoiQmtP9YiFbqyTuYHEjSXscQIlXQsfLCqOeQ4DZFCpiOGjCFwHeEhX7yCoZgHt1EJMNzSjzXLIph8Qq+iu0DnCOwHPHgX99KZOYcMNB88P4FmCvhoHc8YTGXDdjWIrTWPHc2u2E5ELHbUljEItf2Bai8kFa/X/5fqCeq3koli/mQ7VMOWjMIPA7UqNXIV/zgQ2oNNBNMBQ6P8SA==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: platform
    type: Opaque
