---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: platform
spec:
  encryptedData:
    password: AgCE44zPIR1hYUgNpk+d9XhHyXruxqDxk1NBaUv1uunIPXjECymdZVqNX2e8Oa9xau9Vubqmf60bZw7TfXpKtyLUfFYNID33Lpj0GE9mp6yAg5cMqlhGXxfYI2W1CwxodOgNVHA/UM0syhMdTiVTZsLvOO4w7LPP13RlKE0fBVZojtrVLEu4eI9mzVJMx6V5TLNWFLoETM2gUPeSaEx0EYW65yrT7lhP4hEoH0yK329JMqF89i19wNWnv0eFbo0swrQpFwXVMAjNOOfgOC8CVa0mzmEKabnqw7q/yiMdSxiUbeZqFjz1W744rmjru9/woMzzN110dkWSep/js1SBKctvZjLBcCaOVeg/UorYmu3zVgjOJnvBH6V7xF7sgIfzDUapWaYtwP4kJoPAWDOUzMdFwMhg1gY+b2QDXWg57WVBcfeGOflE6124k5y0UGrUY8ysT/7W6B40YdGnNBMZ0cunqxtQs5CgJ1zkYujEBz/k1jYEAiWyZm02LkC46qNmE0Zx2PCo5KxtjHynM50t59C/cC96S3p7n/IeAhXl8xjLVzcPUtVQEmHkbcD+v/sUXJExEUNKvi0GctACaseWWiCcFcjUohwEwS3vL4bKm6xqu0iBDUDs2XZDc/ImmkfzjvzkaaO4G7eBTn/Ltcvfix2sMx/ZzcZFjRjEA67eO8rp3JYXUxad2uwxJ843rXn/xmmwQat/TJtijzb736jlvq3mKKtRNc8ZCw==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: platform
    type: Opaque
