---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: platform
spec:
  encryptedData:
    database_url: AgCsfm76/5toUY8U572YPYUkW/POkbFFtdQ/dLgvVwaZQzR5NEFH0f6DaRj1WGo8oMkhVqN4MRUWV1bkmXvskhXvRd0PA4N2OJTnzLo+xusZfpaClO0kp2+OwRAkAi66ENc2wU474GQA7E3XszUh83VBHZ5a4iQdd5QRqzUNIxg98yCO8rF/8IKTjGdZVbTMrlP67bmnhhUt3MSI2ccVUdEtgQSCvTO02JutfEWmi/dcrwaxKChbYj+svIdk1dD9ebPAelhalheWqbvUZg3iOOkHu4GVZk4sdxH/q+6WHq4W6QtdcMqPLs/+J/DhWddYgQM0R2fl/7cAMk5YgpBfB1iICpvGydfhq2pQkF17lfH1OjB02/Y6nHxzGlapxWAlltFNyr7mdiChv4t0jPjGlQVwhb9WRCb//oTur84BgqlafE8ONB9E733Og906cLYfdbI+4wpgkNEYk08RSZbjxRmX2i9tKf7fHeKkeFfh9yzN6R72q3qXdQ+P4RxSSa/enswey67ouz9rGhA1Ae/Ura7l0UcBJMkiRwWfEunTFZN4KxKewV1yqgC2Z5gtv4vjCToWgvQ33jz2e3QI4q/rTNm3WfnHMVO32W3BC9mNDBZOOr31HeDKy6ZsfflrK+fKwIwrR8OdISP1qD+EjJ0wtyrYwsJYMIfxMY6zsf561SXWZ9uPxhBcwhY9YCW4kEVKvHLO2idLn268ZxCCYoKiqW3FkTH3GYqh53f6XebRX0GXUM4xOOJ9DxiCB7ef8Qs9ZiXfmvCN8nLF8ayWRQsuWUj+RgT5Pmk9+ze4HvLkClMwvbUnrV7YdKhVfrtUlFShuBGCBw==
    password: AgAwCf2PU9N/ln1aALusSfrAndLIidnIUc7wu/UE9DjL8m4afxvO9LCFuuBZX1C976lavPg0G/NVXsx6/VeMj0KXqJ1tAuexLlYLW8okx/evjYEtWEyvI59tgxTRHnIxtGnx57JrRONuvMEBROu4t3zU94sQVuPyb7MBAp7LQOq+NKWSwe5O3Fnb5jLQJ1PWLo7elu3AXk1a2H6BHts0zCqWSw+Tm2I/GT8e3nIs/KsFRPKUQR+QRtS4FWm0sOdrMyX6fQgGT/WWiZLlupHFU25ff4S0Gwej09W2y0QEQbXRtpUcBqETKqYL3Y8AcZrQFgQyij+WKUeFXOE1VYiHH08yjLosNzJryiDwQQ420ASBKiHCOE+Qs72NZIwMBIn2nBu2K82ey1UtHtQuTrDa3b8LbVPtD476WHwqk5C9pmiOUoVoteyO/HM7is+eGUi/ibRzc6wdr4q/XG9kODPdlAzgv1lZKHq9UjRjzrR9QFprfdm+k3wVfM9n0UiC+HTlsNdppXEZFD4bj2JqD1I5w7WVBjU/BRs0L2EoGxcFQrEgzBcBIdXJVeM3FCNMkNSXdVdt7i3TCXItCajvRSr3l8s466rEI0HduRLzJSCxhDvY/Wqgmzj2dAHckWVf7QmE4VotVxizRMBn74GlWza1tbttBOo3s2MPj3nSx1wCQqKiFlruNkJlRfRno8LVScrtqXlS/oJCHg26WEtEg7PGKm4=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: platform
    type: Opaque
