---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: platform
spec:
  encryptedData:
    database_url: AgC5UCxl8HU7qWBKrZ5QZG6FdXT8qwh1x1Lp6pSrKeVgFLjYih/lgImN67A2y+zy1WEssCRq1XR9UUAaO1rIqwlRgShK9M7+6loyI+IgNFIeEgTlAfO4izhJ+gt+WoVt1HC2bw3kCVKBjdcbHNU34qCD6oTfXTW7WrVV9DvAtKi3o+GENG68LegYsL1MDRG+7Zc2qK6h9+kFfX8ReVYshjJvrKVBHXipuYZ1l49upFEJpThpPw83JIJqNTJ/58oW4ElaRwghNws1w6KnwBITGtqhqVSb6YaCHWQ5U8q82bxWMEuJOQN2VzD6LmZEG+Yp55Wsk/uMkVh23/ePxmRWe5TSwYk9+2RMI+r+R3K9s35aAy8IlobXeC2ivpidO5voqD9Vt29jIhHh5r+KxN/E+lvYQsYXcBj2/qxaFy8J1qoi48WeQsngGwOa76W0sChrgw5iSpK6mR1ShM3ts4erIBfPKE0qvIA1VeUckyLbn8/rT1hVV4az87NRTga7iKSVhCAWSPY+C8oWM3nV0AK7dR/4QLuXJFxTnOgWtiVgPng/OAiQJV2KFdQ+ABG5VYtfquAFqFlB+/JiJ/5xbeBduXjTvp/GviNoqI+UM6CqVS7S0c8rNxwpFzyLHKDFRtkYNFq8d0SvycV7sXiEgo5ROVtqMt7BfIrsBbJILUlcfVM9O1rRdyWZNc1nLaXIF88rJVby36F6tzIe9conmN1fcOJ8QumTL94RLJSUvOD5VhD+YJsqQ6G5oXOIXRW2SZwo5A/PyRh4c2twOc1IIRvJMkrG9DDXRzlpmHrVRsZ17piQvrf3j7FOcsRc8XxUhg0BmxaKBQ==
    password: AgALELjIXpN+CVzDREN8ZSLlk4p24wvSNf6gB1EN74mdCtT60thRf27FYJnoJcuQDuIT3T9A9R4t5rJWETieKSjTZDoRq0Nj4UjS3atpQ4UyNbAdbDy1PgKNptKk57s09QkuepLBSUaAMck6ICdd1J0JdM0tkdVEHEVB0pDfRqp9TAVD9oOYIB8+6L5TXhZMAsrj3NDND7I+kZ55T5taFbOIppcaoOvu2Nlhy6WOUawXzg6VV1SsGUpWsyNI4S1b1SyIsIk8FyxXtIoRg25KCDfgZifNX0wMpcAqPdDTR5SN1EMmioKJDmujnlTdNzrKaMX1IOrSMR+jMrPLnNjdHfKGuV4jYQ+ez88BHfpau4jUh7c3YmVyVILXK7rpJsNEzJo/aFDzDuCXkbOM+5ADeqTjB0Gyn8zzPMeFRizh7xCDXgQignkvDweBsSpKWGc4d3kYPQLbzAXvUcILs3AcVVwkZpAt9y3PIu1sMkp1CoRvHsoHEZP7UUy8RVEshQi+qOi0FzN96Hmi5nIursFGsQ1job6e11ey3HCWXEcQwkQLDfzgUTfm5xtFhyJVD/O4zp/9rcoaASTq394w4eMA7CEm57Ez3wCwzb4HlAKJNLrL6lK4eBl7o/ososc2FxG5dcJYumm/fw6xCEmRX144eTF2FAm3Ruqb4mvu8zqulWsporKDg/MtoV1KZlYCQcoUZuxcoCHJuUPYXHy8gPJPHUU=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: platform
    type: Opaque
