---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: platform
spec:
  encryptedData:
    database_url: AgCqUExCRKwN/c0krGo+4gG6uH8y2lDVqwLxUmFhe35OJR9XRSaVcAr7DFCwdiZYCsSGRBImu2XZ+3nsfnJHCvs3Sa4LFzGNoaPzjDP42rvMdkz4l+KCKFd4/qKPCM+KcAmQqU0XPJZYdkrCRyE+FsvbKoZvJEngrM5rv7Fs3DLEiXhvF4gmelElV59TKfZLUIJ5HOS54GFH/q2O4/ZeZ3gXVYumkLORG18Gh9p/UDOqB1uwBdWzg6Th11hPAlj3OIXOnR/8F5ZNeVynbMMwfSySU8vkqdnEPyfxB1dEd/015qeenmYKCmlHfwe4UreXn0FPep5Oicshky7rH595vxU/dT/6fmigCXOZOhEy6Br49Van1yOUQpbw+Hw+tk9oMU7OwbhCzRelU/xRQRw336QG3401M4vxrSqlvWzNNCIiEKwmo9nEdSYa0egmdJ4Wn91WGnkbzxLpaA2Fu39Q0vTDmdE3s+9rcH86QsgNfCbxslhDcqvp3ffFPXHo67y0uBGPS+X1sqrpGHwOLGP0rsQ00KmBY1acqjQaT8dDGuqJlmKh5P70lHXFQYkdJmKpIUozfc9DRQJlCz8UuvJFq/V79ZlMp6fRdzJikxbPY9bHxLaXA4LOaJ2Bxau1VdoVTYWSZTuKON9VmZQz0bwm/IN58G7hu5GNxSuO3wsToHSgWivlzMVIDgOXwITPitw9yqC3phgohCLvThPs0gBSIU2ZfE9AL8pd6a6I5kIjoTMBnMPW1aUw+At/0tzKVEMQrQvMUALvdn6JSc3hshdZaMxd/7qJoEEh12gd5dIOZ3mJL+peRmp6zVAMrnXw32vqLs2/eQ==
    password: AgCIy5HR3KDgWLpIA1Bi08nWHY/EJQxUOqDDGeFVSxqQ38Y9mUS7G422f6zeX3iEDjllNFYPPVLcOG/IpSoYA5YSLfbms0fqfldAQV8G0++YXTIi98tZDm8iesmP/T8O0ko4GJZZNl/6pWjvoEv0WApHBolzHmi3DKtwc68sOXzI9eSKvifMjyLy0Tt14jJzNMbYBNrJ8R1607yyUUi4nITwTQxhLxfcJ+ULqubXUTEJwVWpQaKRT7WRq7jIQS4SfPKZ2ymy+P8VSBOA3+A2vmvQjiU/fIZKA/g9SrAfi3SD/M8K2dhxamTqZTPkEshJAtbC/jOnduEUwJT+puk257CbCBp3JdrpPmTL79W6Q5sMCdznxXWUH9YOMDkyWC8z0UPIByEyNPiFhF274/MZBAdkG6+6WdcA8ONEnpuZPoK+X1ycfIDffGsUvXjbiQ8ZIU6xJahYvtzNLSCX3oNFVlUPvp/O14L9XixRKghz8Pv7ujumLkySvOCgkJAWBM3Qh23u5hyqUAx89wj234jssQHi1PG9htqbWCC2+rPsYs+s5//+FpqBuUNnRkd5T7L4KMxv0J0urhRnoaQiKGmRa7vDbBBjaYwO9yY9EcPDECqdj0sxFXWgPO3aebFYLjlvnb4UCB0DMehLbDzNrHg5KVhkAw7WkRI7N4q4mgXDIiKuoLqCpl7trrSbkx00ndiuCU1FX50AkCnAGU+8WQ/IoYM=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: platform
    type: Opaque
