---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: platform
spec:
  encryptedData:
    database_url: AgBMJgGx1HhB96YzZv5pBgWquXkjFptKo3aI8A58i0AQCvSY37vt9MoFRVyxu8TeGWpiNMd3HkdTjsY65pFJzRmR3TT8yD0zOeBzbxjiu/E+DH5jWcEnElGJDrM9+uKOwvjow8uxVOX24Ir3VnhcyEl4R6bLGtAJxMxaeAOhzuWej9OyJ9SiORGfAOjsXvHYQ9qj/IMejqmJtO0QND/wXSqtYiPif8cjMOX55UTvZTQHmCwGEc6yXtKW+3LHj2VpX5blvuS3qhE8SDO+slJ3qjnkHYIkEChYY3Oq0PcEWf8Rg/J7dKwmTl13Z2AKb2Fue7wc9gMCUBE4O10dz+HSH3TdO8abxVr22CJhL1WiO1kiyZ9yAoam4GoZs0+zKykFegl78CTPuv5IglkpfBvj2kx7dbUbRKdM6pAve/hBQGwxzs4CKBLaWt+VVyGFmr/DUbdbZfmDSsQTyQTVBmTC8+FaL4Uq8XkeAJKp5X1YYQGwV4kr8OMqA9i07zCmhERXM3T2pttRa+ak4SntSGcm+eq+RhJR+Ckptli/ye1vQe7aTyfqxcnkYN3LSKgAGOaayztkDLwhm4jhAPugChekAqruMQmFsOAJAKyIa35tHGR/RuwheI6TUAg25qzqFgjzqLEzBB9k6yQjsmMbFkR0UDlgYBh8NTRiu7duJMZ+GVcypUhiLdMD4VetigggSSbKVPAllbpAc11zxbCjHL8t//4w0xB7jlEX5QvmCt+9VQXnwG75gfAQjev3PRSd1idDkv+oXHvyHGoHhvF8hHsmOm5OlUWXplm2bn5PCPFm8mWt63o0lozYauRJHxdeabU1GneJ6A==
    password: AgBz8nRlzZEHkw9k17G7ApKQSc0pOpvO33+CJbmQIEzdpe/bWp0+kpdamFSKwabhyUtkFtluGZ6hvLJfZIhu8oVezTeFe4oCasR8NZ93siWlBptMR6CWw3WCCGn/EgW8LRH28uaJS6NEUJNQ+zeVFqUNiCMKd4imVaMWJU8Reyx6OuRIgAjuwBZu3CvZjxPKZ5iQ/DSH9OZKaat7OCaPNwZfSKIYhJ7fF4EbMc58Osqwep63dE2DF6GqxNIITP3z9zXTApbsw/oWDJyfiIxv/eO5InphunsZZQK22BcHXH98zWjnSsf8wS2edA9zS4Jg+I3F/ZaTWn1pkCCQIxwN2CiEhRzPPzakjd6XETzkB9fiDEiu5CdJape1o2wpUOukMx1oEADC+UhlsvkSyq/gIPdlD482ESrFL2BQQ1jnr5e7OTPFu9rX7668rC96dKoeYEgsSi5OCZ1Oe7vBSArG/QWiuKBMF63PixTsGqHSqBHJHt6js/FbY1ap8hWD3kWFuPCuLsSJmthrbTo4mQxq19NKaSsokP/8tfpjZAwHh9pq5gp9MsH1QjAdAv/mFY5t1BmfM5XjOQqHBbu40k3X+i3FlQyg65oTMTsgOqsn24VMb1C4Ge3brJ0ROlnWs7VhpFMahz99ec5SLi1odOW2Nz0Dy/e2SakUfbCixjREAVCD/6sAUQ6i1nLe1XphU6OgfKE6JPy5LLTRJQBPHlwFuiE=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: platform
    type: Opaque
