---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: platform
spec:
  encryptedData:
    database_url: AgAW/nekjsbscvESfoARR6abBW+5dHNRCyCgmVKpxhiEECaRlQVNrNBejlMMYETQOlimwu21bRnvBVFTAY1U4quyF3MYISTW9+kkUZENBFCTfmJXkkiUETTjNnRv7K4w5fY6h9vURXrpetEKQKJdha7KBkiUmbNNZTIsZyrCc7JYaoG7siW4y+RIErVnV4fxwd7naLUaeDXWShPI14+uMgvc6DTXvPA1lvPJo2GI4pJ01mqzum17K2cIBt8Zq72RVaqFoNyfLciL8CqN2HdbZyMFAVnxehbfXSDb91m8Gz9Ibane6sWNI9hd1Uyv2WnyivP2AiX5FlxxB8KVdbRtHhmYSDgts7HqZiwbtIKBy+nQbjqTJPIauRCxPzS9s0QqSvLtVHbKwFSHiibfdgT1AtV9A63b+iUmjxDjf5pMlZ2QjWKTYTlItsLcZtyIgaLkXMuNzLBPw+noHjEKiawN1XpGJAZKqz2rOB7mCmxhjIj6YN0C4TKgU7WjRCNzxQj+vAijT/n6HeT/7a12hc/Q/8kiRV+K2OwXT7niDRU5IxdNWzNr3W7bvLvr2BW5TYIGIG3pwcL+moirPQ8PzCmloOeIcranrthPHUyGNUm/CcT/I+miZaITFMMoFWCMVLa++7+hSumXXGIQOd+ppFoSKquQiJR60YaWYGBlGco/5IVwk2i66r3frpwEj3FwydR0t5XawFcVKCjcgYE8EbDBLoFL4JI77uvZuxIA1BZBHh4DdTNllWL2cuv6UrbXsxQNk+wQ1SjJ4u5fbrDFdLwZ+7g41dQloSixLOlWvskrSP8lT+op+E8lO/K+YWCaRzV6N+0/jQ==
    password: AgCFrR8GcPXp3xFCQCuP3kXx8Uc5IjSIWvQhIeZwHjr6J4WA/Bei0d1hxr3U+9LU5VtXUzNpbvW1A6CjLMiBnFDoYC6UYkuHCiR06WekNws3suepu616qd+x0PfzvEqCN8kmwI5gzf1IteihWS3/TADtOlbTjO4oNWGDOpT5YhBop+WvKA2rsluraIw8gyUk6Cg0bQE+/fY2qtendJ0/Y0729xEQzYzl2RwwW4CilMxsuOzHJhx3Z4A04NA4qkG6WDlQSugCuasfM526U5rTfL+EbU5APNWVYVtfsBliNKj4fpQwOn+Tdd8+fRVFIvbA38CEhnrOa0fkjboYPHwmrKwVCWe1DMjNwDG+uCil28Hg0jWvd7Jm/p586ZMDyWovzeaQFNjd4LKltKFTIsR4RRFrehqDpbNAgW10JJn6l2mNzfxFy5bJhswuNZ84qEt5NJ/0/50ZyDLIoLtuc5XAFDtkIGoIh8f2my0xEkEEAnuSBBGQWl132G4yW/PI1t37CySE4+okebeFGp+IUKjvjgY1M+ZrbADETRo/vL/qG4gqIm49apNXPu1E3rPyKflJmBi2QU11qMVLxyWqbgzXp6gXJmgYt7zqYIMkiBSI+02Pu+2nx1UM9zfRsAtNZPdmPyNMughZDf6chvUHm4MAUXA/4IqWjteedQk+iOCRmjlqO40IruxNEl8YUpXeVEvwcl10p42cEF1szwN+9nEsbbI=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: platform
    type: Opaque
