---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: user-db-secrets
  namespace: platform
spec:
  encryptedData:
    database_url: AgBu5bjnsjqYhdElHX+zfRocI3VkRIVkZlOS25d55WbUENC/LsX7y5ibjV0coQWqB7shvzx39XGaqflYaEwFzHudiGhfEruPgN8J839yVvFx8RZzaF/s8TX38/UvxSvX+BdgHJiC5ZKJL5ji3+7YTG4wzRt4Vzk30FXKKeqoELTqVasDbCUxWGHuCBebYtFCv9L8QzF2W1cl9mOND17+4cx0GHNzMODBApe9o8bnsWip+IppPwZqOub2C15UwjDBnEbUKyLwQdFYBGI+OxTL1rw1R9miRD8VW3FWIaZLRvMCLybGXN45kuq4wWuPEbu6CpRoCymQDx4mcpbd9L86dJhDHbmD6G8pkOETWXF9RD6ltdv9nux5ri+EUM2xh0XvGSiEAAFD2r4w4rYWAgm0TFByCfmw5zzXBsWqXPv+MSe7kA4okgHAncE4WFO3kwk5CsZYf5p7K9cZxLUcH/9G48e3nLwrpsygpgKlgSgXeG5JC++MHV1DdW4PdddvFktqV13KG7rsBSZ4vctYILQ0TMDMB9HTIXKFVh22Bh6R9FSiMRZuLRyoIpzRynIhPntIa5Xd55+3X56konUxoKM71QOSL1FJ53VUTWQ80APQUHsoZTQWrdHexA9A7wRqY5AV63BM/Kw0qotELoczm5zMzpGScP3t+s9UfrpqD+3c0s3afZQatgrpJip+ZBhwjH94xdiDktOXD40qTEeJTqXc6y08dRI54wAVouCixFY7dohXJPjx0porl8pcmhd3+WVueLkjDy4dNHGw7pxfmSaPMhf+zTJnpBG8cOBrGSlhCzo0q3Racd/Be4Gf+Nsw6WeDT4rCbA==
    password: AgBV3zfIC4RrxwFxtNwn8SmXj8Bxn8NGHzscq2DyZ9pEkOh4P9ep+TJ5ACWMrNkYhtMOV5NUw0JAjtH+vaNjFr82ISNckS5tlRuPd4afZw+aHMsAYF6FnRBTAboRHk8l9/Yg3dqBra940YgBymr9o5o/y1jottMZ39m+6gjnpiotFJw8flT4Aaop8jovOI4QTGy4snMjQeMgMt+ef1ImRfDbePLNsyAlIE9ca9QUalPeXJnMMthgvVS9GaI9P7j+O80sGevMk9Q/6C6TJBdijGYk+UBVQOp6ww+xVUOtFvBZAje+Hd6uZyOHYo0RN1pE04nBc7X6Jg+F2mH2JHCnbeBMESLtHnh3RMwlp3VvZ09axXhK69B9N/TIABvmoysS+cJoqTUl074gMyP37cmJ1tBFmJIRg/NJ9Jf9wpulg0f7+Jq8s4EBgV3tKe8wb58zq4u0XnRcfhhQsOC6gcH8UT2/oHYDOmHBNvJ5EHJO8dDxS3b6rsb17oX3YItQ6Fr9AIPx10h6Z3L7Gkn1DApGtMzfn+ymharJ/RBeFfXVjTiRjAGbANU9sqUI1bEVnOzDjGyp/C2ncLbo955RnYROipnMy+Chltp3BAcRMJ8oKJc6evvLX7rBwErf6scIRnBAGk4hh0qiX3w2L8TzTqMPn0Ka0xOWJ4ubm27Cu8AzamTu+lDBTCbKj98AISh1IgXj0yRHMNLRp+AnWP2s4QYvPlo=
  template:
    metadata:
      creationTimestamp: null
      name: user-db-secrets
      namespace: platform
    type: Opaque
