apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml
  - secrets/ride-db-secrets.yaml

namespace: vroom-staging

patches:
  - path: patches/resource_limits.yaml

labels:
  - pairs:
      env: staging

images:
  - name: vroom-mvp/ride-service
    newName: ama2352/vroom-mvp-ride-service
    newTag: latest
