apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- secrets/ride-db-secrets.yaml
namespace: vroom-staging
patches:
- path: patches/resource_limits.yaml
labels:
- pairs:
    env: staging
images:
- name: vroom-mvp/ride-service
  newName: ama2352/vroom-mvp-ride-service
  digest: sha256:9895a14119ca631c67c767860e13d65fc87739b2695bcc1961fe2c0e1cfe11a2
