apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- secrets/ride-db-secrets.yaml
namespace: vroom-staging
patches:
- path: patches/resource_limits.yaml
labels:
- pairs:
    env: staging
images:
- name: vroom-mvp/ride-service
  newName: ama2352/vroom-mvp-ride-service
  digest: sha256:f2514e74b45cc7e51a9db69ab77fd5c5d63865af634d4ecacaf5c529f61528d0
