apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ingress.yaml
  - prometheus/prometheus-chart.yaml
  - prometheus/service-monitors.yaml
  - loki/loki-chart.yaml
  - prometheus/traefik-monitor.yaml
