apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml
- secrets/notification-db-secrets.yaml

namespace: vroom-dev

patches:
- path: patches/resource_limits.yaml

labels:
- pairs:
    env: dev
images:
- name: vroom-mvp/notification-service
  newName: ama2352/vroom-mvp-notification-service
  newTag: 7d41a3ea
