apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: vroom-prod
patches:
- path: patches/resource_limits.yaml
- path: patches/replicas.yaml
labels:
- pairs:
    env: prod
images:
- name: vroom-mvp/notification-service
  newName: ghcr.io/ama2352/vroom-mvp-notification-service
  newTag: v1.0.0-build.32-da02e4f6
