apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom
spec:
  encryptedData:
    database_url: AgCanhENwH5lLO/ayVkZYa7Dud//GqFVD5u3mg3rtdmOTwtlh1jtYGUKNx8lufp110xV6+45XBa7q9ifeffK5jg4IBH/xZEpPXlKtFuWDCLur8hmPgjaGH50iI2Zspw7R7Hqd35Me2ZeHD84eUCA2vQaUsb2Wo77Fr1p/X9d+3/txklNnKyDSw2qd6rziNmJz7ThHsx6t+lfrV1hvInc8lBjDzzQDAqYhJSrG2iQlTlizn78Y9LeLdjwGI14eRqsgCbs4GbOXZwt8XS32/79vlYrwy5oKj8j8RA9FFLLmaJq3ptOGag7uOA/uvWr9ywap6pBfNCBKdF4LuzU9hWHuMCh+BE3qS4jA6dL4UbNP9EWzrLNhDwMS01oRqX0xIVXM5JQMHa+98KLjjBOZNVyNa90SEevB9YnRGYZbaYohsTKmGICQd6p9BICluhlUULrObs0Yv275qfnz+m9c2evjA7PSyYxeKyi4EKJ3QXJMLidU/bKXWI06JYeKEa41hYzJOSx2odFeDAegICz3UWBqjAB29J9Oh/+wKQVo/Pxy7SGzrOM+Ng9PPwU6/BBEfqaxljRGhiA+HtQHb7C2IWy7O+2ZJo3/+BMmBmDUjMF789PnjFx1lhjdSK/EPIMFnsnDNcZdEQIb3R47i1i6Mu9hfLmKw4mMR11UPQl1pBCA2+r5XkuRh5ZHh162iKwgQeFrRsbYYhtPLJC2xZR+KOJiNrsRhp0qVoLraiT8F9AkaxTzl/wOaYu0nLN5zYIfIx3FgnhRD5VQ4S0XR8WtRNtw/4W5Sl2zBSLwdjnonNhMjI72u1MwDB3JXOKYKOA6+bI7FKHQw==
    password: AgAvuFNQGedWHY90DRG/4s+okAMRGe7Dfg5cH86oUCnlW2o6m2hyo3XS+5XnT30gMXLotSx9w+E7tYgpahD+BKzcupNHNZITfsUZVWkTkjUiRMmUeARZ2MCStJqIyxCHy8TSSfrE6D//kIX5CivduGxa8EDhK26qNMi4Tzmihl6DxBTfuxYtyIXM2qjo6ejrZzaB6h1GDRKrMO8Jq9TZmo97NcnsTirz2/SyxU0Jn53uMcSUipesghFf2XK/ybBJNvzUszytrKTKCXog8OZSuS8f6qvY/Ttw6vrzv/ZGpUpAB3CIfEC3LI3YEsORvP6/WcF/hvnTT7cQCZPnIcR8n1s6xeamgbcuIlqK6pIg8YF6A99Ztovbaw8PUSH+OD7hIB10rck5DvDrWAJbfUN3ULBiQ//QbGR54WA0JsSAjq6nStPJGqZLzjZxbw2MMJGqqu+KXxTDy7IXK5QmJgda8sHMm+ZdiuGYw2qx6bbzu0qkoCf4g8IQcRhEYcOWly1CFS8Q73bCISumVCshkfbc+VFqca5w0huOZjAcAsceSQUQHX3OPFf45tLil+C4p2q0XEXJPxkxLurNOqEt2cMki7Dpcs7V00K60i/xY6zXr31PAiJEbOhiH2CaEW/sd8nAsXJtPaXxtfxEDVqtJCYgCW3Y8+ufb12Sd4XY1TIXDX9XEosLXf/js3qKh/FSunm/20V+4jWmdyE+VG2lB9rVjRde3G0VL3OojQ==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom
    type: Opaque

