---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgBQyfxjWJxh3WqaPqYJdMwAGWU11ISGl4YgPRy2Ndzt4Im4kwD9usz+cOs8fi8/s85qaHihlZmsu8+5mvNGQ3fHrGKPEQm3hUQdhWPZgXrqIzEv7sZ41Ctsb0JUhTIYyqSPtSxMFmGNquoA0E1kb+XhUHhMmywcWJSJdj+ftSgdO3HsTl8XwD9mazO1SP9PfL5GD5tpRmV/7YagZbDkXBbqEBvxPl0Mt6S6e0TlfdXdV4TLhyTOsM9UkZ2VwM2GJiciAaGklbRt8SDM9ee6y0+RtD/FoHI6cAiptVTyN5OeWuBTlUanC0glg7PZ69/id/l5sHJJZw8U+fCSpv+8KmqZ0V6E3Oh+pVX4xUJry50kCXw+mTz4HMVQ1CPZ2aMuImWisrrFXhrXU0OFydeS5/OxQH2rzF1ynysZygKq1SRmqqfTbWWZ/bqLpcAEq1lAs/iVo+6pYqJZXz7B2zjMnGqrbzEPmGCOQp2641Szv01qwc//eLMfcwkrFerYg9qgV7FGbzmeIqLEz38Soq1RWOw/uEh4BfvG1SyHykkrDaOlNUMRbzbZu+UuJMTB+G5UE7DtJw7LMT6LBuVthw1EGgZWPieXsVSLNTehO0L8odeNEbhTR2T4YPw5Yz6W/rhjP/GvSLd67BVQ66FAz3HRwQs2KsmdL0ZQ4PrRQ93jnT211h4QhOTXv9axQh8MLPmq6kj4s1hO93ulTLLgRAcbzILXuipnTU2a+RbcNX60fPIcLCMhnD79PmCNKkguxNLtij/AqHAeQOXYYFCF7tosyYaIiIli5DP+2zDNh6Vcu+tKLwS2k74xoKbdnWZJVVTcxdVhxpxVWSScr/4B/qpgXxJHY4A=
    password: AgAFZyASRKxmm/yxjjRrqx0zw9J1L7jchyZ03IAcd3KUULliTTtkxU7wrPAZrIM83vX96/kBYkKcUSS0xSZIkAfYjM8r+F6fz5RKN6oSvn1fNlJWieuCTDyjDQlpv2Nm5PQhEFeQWYSn+Odv9hcg32ZE3nuFFMOHlOqI6uMBuAru/eW8WFtnOZ0/xycHRkxCj7JJwp86K07oYk/9DAdeVKK5lEImqUi69G2pxFw412FPBcryct37WO5fyi7ZpfLl9ZtvAaWJDw3VZwRshZKaywFZscD9cnMlLKtxfiyThuHJ0zIyUXjkQm9neCkItC+W+1UPdJF9pF4TINSk7TLJutcVTgB9L/iuNNO120xq2BW+5CSH8gTdxLeCN5G1R5tGTICZrSFEPCoiaHj1f77fOAJwUPDJUxyzfGP2gK7r81wyOSk3KCc7V1JXyQtOeZhuz995Say4MlZw7M1bs+bwiZeCx3217xmKZZ2l3ib5uQdEw3xxz6E9MB0hLSkDrDhoB5pnYiHR6D9Pr6ZKcRxeESMY+sZyJ4dxfPEI2Is9buzDmgvc6zBbpUB/2jwGtiwj4EL51RouiqMFMe4HivAiTgJSxugKaENduLCvt8Sl2ZKE2RgUAwZ5aPEkmG3r0hxgFMJ5QjGkXkYpru+B1QDBSJd/HsbpvE9fLu8Ef794w0ule3ppnKflQEyt4XYYuFlXEQUMBZm3q4L/HL10TIR26GYbFvocl2DOUg==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-dev
    type: Opaque
