---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgB6/LktTSCD/KX/dbHKTfQAxav2JDeTeiWwRBkY2ReDKgpTTuv9MM2JfojLIJWQLam9xBvDy5eD1hvGT2+oSmptAwBl4OCXXQ57eWcVFasTqJ8aMHMdoHZ7SRIH1AfyGI2HQWortmUUUCOLaP6zVwz9nKYY+K25zG/kNRksYUMCfT9bbStNPOB929z0fbhjZF9X2AcG1fFsEpGdxejOnltyQfshe1MBvNVh1wAWJ5j8pKuQVUbtQ9lYmmDa68pPwPI/ZWyhuvomaYgtpay7epTfJZtFvF5N4atLNqp1+6kzAmG3M0eHqOr4dqkUkyLZCVQyENeOpDWMjF8tAP5B8fn++07kfe5U+XUzqnGST2IJ3p2RkIl/N2hRoAqo73vFIuHG0yjXJdzYjZODKEQ3x71kd7V1YO77a7JtROXf6RWRGmqU0DXVYYpYCtux0pAYZQibsAKKe/7XitD741Y1AhPj/0BKu0KEBrIofAoWi+B0sgwO+fFXlRNEfeMsZW8B9pl7vWZVwEQ+1uAX0JE0DfJmMgOPLbslSsuimunslvm7+D2RymQLBtHueGS8BEy+H1Z0gahW64ncaNqd48Ba1jAT+QG7HRTX7VTK7C+29QZlTBA2oLq6G6uAYvQyVcSrQrJH0cN1eKm+yXjLkA3eQVswb96VG/dwE32+dlg4bwYrIxVVoWoHdvWFWHGzz1JCXbtU8FvsGsXs2nBWAzrkz658MecQ8QNBes6N+Yk5WIODBb+u7zCXXZ8Vh0q4dyOMgYRhYoIRyel+ukbmVBUcxyGaqhDJ1uQMEpd+JcmXypsOx9GmNLKhZAozCHejJrotKtYJDHBGaT87MDlaakQn2LiSOfk=
    password: AgCHmrtmfj3qUyw9m17qB2qAlZOGmkvOqzoMDBWdDp9P6EUJJ4H2RJMxZlbvYJzy3VTMLlDlyA83VqSf5Q/FPiZuXGAuod7QBL0siEp4zkZG5cs7iOgrpV8Szk2n6vZHObDPIAMv/K6PF5uuxFd1wXrxBZozAgrmi96tHrl2/oGoP42htpuVLd1VT8oBlpslQHU9ZEeY7zfpERkt1RREwOtIof6Q88HGopuKmYXQcbMbNcDraBA7H5nYH8ooKEmxoOQM8fimdt0f78UB+FGrb/FVt0pRWBuB/7/RDdMNh/3D1FQWw/bsxPRUzNl52OlnsY2Z1cpYyY1TNoNhdD0RCmKnEDYPpyTRDnBsQobsFFcny+bAaj6eWapufizYwmgAPSnO752NoPgcGBJDFawCtICsHCOmvZ3Pvx7jZBMeNNRuaDv8F3TjZk0F3UEqtB7+p0It0G/hGZxeMe37uD6JS4rcUWBOO75r055kNIkuOtnuy/rtsc2a7B+oljP9UD4yq3KlD/rdaGVyeZfwIA/dU33jJPBVapRDShBnR6pbOi8YFIjUTZM0qZ+/5yB6HmdOYeTKyf4PCvFR4UIhK0ZsNZ3B5owKWeMeBKNIkJDfbldI0/cmZOFQwhWxYhWYfKbz86lFy8DyTw2tY6QN7B4BH9g7vq4bSnNRAETb4ItXmErB6an+VIz6mcWQB2A0JNnRvz1Ryo7RIKhMIcLjaVTazTFf+Iprwc4Q7Q==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-dev
    type: Opaque
