apiVersion: apps/v1
kind: Deployment
metadata:
  name: ride-service
spec:
  template:
    spec:
      containers:
        - name: ride-service
          resources:
            limits:
              cpu: 200m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 32Mi
