apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vroom

resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      app: notification-service
images:
  - name: ama2352/vroom-mvp-notification
    newName: ama2352/vroom-mvp-notification
    newTag: 5387a4d0
