apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: vroom-dev
patches:
- path: patches/resource_limits.yaml
labels:
- pairs:
    env: dev
images:
- name: vroom-mvp/dispatch-service
  newName: ghcr.io/ama2352/vroom-mvp-dispatch-service
  newTag: v1.0.0-build.30-ff0264fa
