apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: vroom-dev
patches:
- path: patches/resource_limits.yaml
labels:
- pairs:
    env: dev
images:
- name: vroom-mvp/dispatch-service
  newName: ama2352/vroom-mvp-dispatch-service
  digest: sha256:911a2c5d9ca9fdf9b107c838d6428a68856158d90a0a610ce805701633e68444
