---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: notification-db-secrets
  namespace: vroom-prod
spec:
  encryptedData:
    database_url: AgBkk7nTjRXhQnSALRW54Vzed9tvoGqYH1WbLAwjpDkFZk2GsDrE/f8RT8DQKyHBT/3kesO1BG8iMsaWQTPXENhETN6by+D8lF/zXB+Tvg8c6I6FxtlVNHOFkGKWbEJGu4yUGyckqVDdVRAZfEhxnoJH41RTHaNX+kTnzyTYIDIZXgNohBnwZsLDerLljBRgpfnaLophmRoFrvVBX26XFrZDlHWXj5XosgBiRIjcDxPwCveLxxc6RwvoqDEHOU9cnYrQCA9y+W9HmtdTwrn+DPlcXHW3GIL9rBdF2bVAkr2TlnEwJgLdGrr82WmumfHljUfRS+V9hxYoRL74eMBdVXZlr0m+RAYCAU2Ayka17zvgixDhVFCba5SsFLSRn0jEFewRWuvR2VX+iQ2M+1X9CbFY8EoDbpzvWEjNirDhr3O9Cf23ZGVXsn1yxSf2awo9bakn1/Y5PtLIhGel3I+qnPSzmssHYlfcHp0+oB9Al+4dCy5H9pozaizZZBM9ytmeGnhqX92ue2ciC8bcJUHlLdtURGljIrkcLF44EvhcJTfwzHH3+r9r4LYrAh3EWDQQR0TuCaM7ms1zkVXXQEf2hpT7GJXsb0hw2Kbgf7sbFXZiC+6lvyCkwoGG6eRYYtuRYW/foFB+6XNxVLJTSUml5DjNqeUJFdnDWFLsHEWDw/MYpmY+CD6U8gX67toRM+kl7FYmeQjAxG0TZIIcRLiNDQ9Pg2qkhjzCSkwzwO1+oRseo56ZqRnTAWOuiNz65BK4lpCJsKbiolzO7Ci3nh2kAKuqkthIVP0pDgyRNdz/Qn60HZbgpVRT+4u6/Q1jPe9x9b6R7pNxq/bWCD9mZ8IqLuJ79TY=
    password: AgB7gid5Crt9+GAza+v7Cjjnub7ui8Ptbh+XyRPl97URoqbDhwkC8cU2E21WS3Cs+AkBaamjAEEkaXQ77UdLsTXMCwnScRp++P/fDhX6TX7G22mgXG1CcnCNHpOmcYduuTMqK6c/J5dGhytL+28Hz+riSdVXzJCXnYa4H2yWfIf84nSNNjZgKyrBCan5W2H5mGAIZBVrbwvq2I81ky2MSwLTRg4eEr+nfBwjtoGy4jcamLF8i6np19bdfyxSBPa1Tg31pMwZ38aVYeB4IAZeQKikL26/OKyNclcNlBXnE4lo9wMnSBNRroXUzzoaXreRgZGhbtjoBFMmgUFB8qB++vne3ZcZSfmyZkZnODFpyNxbr0EJBiBjJs+TlB1S/BgsNYc5F6Yg7UXpafvb7ufzqL5XR7Ss91aALUnipH5KXJcxB+IiBNd4Ca6GWBuuYguQ8W9eXK5cFu+NwHHSneLjmCOH77RnjC93C5J+nzVVL3c6qxRSxo+QdqINri+USc3LrxNS1nRn4xxkuxFMBpf96oR3ANQ51hpCubSHxk96xEFApcR+dCgy+bgsKdZ/xu0UzON8TJ5+6EIiEGXYN19UcFc/WxZOWSlX8Ei0TYzOpLJ/to13rli7ej7BPJrApYdR+YKxDsGSyUw7Wp9bQsXWr2L0c7MECDrpeX4mpogu/r6dEHrqNp2UTuHn0cv9haz1Blo2MUaNut/+gR1V6BPwE6ad/DuLi3DzJA==
  template:
    metadata:
      creationTimestamp: null
      name: notification-db-secrets
      namespace: vroom-prod
    type: Opaque
