apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom
spec:
  encryptedData:
    database_url: AgDbHbTcyYVYNZ++rAV7USyuIht+GqkfrZLtHuavtpqE6Kxm0FWWYy+TrGseeXYmnvD0XOdXl6o6/hP16gBDI+Sr0mExgpl1dXsn+TGLxlEG8sqAyS4FL0sYUb/RPlkyNJz9lzJjX811xu0hW/vAYgisp2F5y6FiEkLJ2LNs9xeXVfC42bNyKGGy0mtCevrnxK6QMQk2BPLbeLp7I/ANVmu/Iw/x4zA6XwzjXoFqxYBf/ixzgFaLl47q0Y0P1/uuzorqCE/WisKhMM8BDUxkWASiQlj+5Ej5EvpEKaiwcuw+Djx9JDzXuSVRSf5oWdXrRdvQPB5QFFsdTMus05GMGK+ciHEq/lCYc71nV8+o2KwvlI0Q0sn7GgIWnkyptYpWIE2f9x+1xrFuLkGfd73BrYG026YGW7HHyJHqOKhD7j80aXZ8rE6bVceP3jAuwCYiFqR2XYDZ3KURylunFIZZQDXo1/kg82nzU3zxDfS7kJWB5pyvpw/37aq5vXTcHVs2lS0QKAUC2ApnJlMF0W8b1fcNlf8puz8JmuQUMQ1elyY7Zi8bOCg23YSTCaCn+JAyw/t0hips2P5kyMV4G1RpGdHUt3/wp5jAXche5MB1jeJRsA6t0ERpYcSi7jiu4dfKnB7M2D6LvUqcT0wlQJFPoF54I3loZtWCpMZwgm/F+MQTBYjiYAt4RlJ4mgjoSzQAa8Sre0cJip5JEXvYQa4S7RDMv8rsmtuRQx4JpbY9FyY/YjuRoUzyIlCkC0PfN2CoXDbfUPmIRAud9Sstr1mR8051wKmq6qeGfQyM1pnIfPCIUHSi
    password: AgDWcuiWzDRT28KgvCDtZOs5+7ziyMXPlY4YW238Xvs5ei9B+5shLM6i1WOQC4vrHjqlCvXDgRzLu/uZtzKoVYvApUJKL2wQ2u3PWvKuObWCqcWt8EvbTYrhOP7LutmXppRVKhnY5Zl/4+YfqsX2GLKXJjNfjQjMY25xPiUZ1gtJB2PssXD7SuREllVPSPa0ZU/noOSXFRO6qMdEC2h6g7/ovCgYAyV0Q93iiReNXE4ExjTjrOKTrzaa4jOBofaMG6+MQmckSc3rY4ME38X1cUVAMUb3qnGB73aQf+BZQeqZ0id9NadQruy1m0TqRqrqvlZhQ52ULr9bLqGYrB0xzOm/S5bkRA4+rbCTsfR1apdcAJjl5WqPPEBqu6eAgzlUUUbmPzwDYHZVEFw8jVRPK+pAwtAQ5sumYMhJhJbvKzdO3mJ6E7Xd40PrJKuqUc0fvpiXbWTf7IHsL4a6fu6m1WCMiAQWr8zEZ9bjIvMCAjCIxWsVDxRMcbHaBSWBvuYff+wUeYzWr5/11w6Y4Dc6VHyTb5+/8xH9bAclwp6QYrD+/nTE/4e2+Q0KYVIAGE7NnK1Gg4uc0Og+Z423VLem6vlz6d/KVGTJkq8tyrFROFX+oT43/jXn78V6nIATnR3iUzebIz+RKstSSbaDOmBR325+z9VcC0vEQ8x1bNlLIMTOSmR20Klrz9wIZgKUXJex0o0RhtCzfds4OYrcZNEQKUY=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom
    type: Opaque

