apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom
spec:
  encryptedData:
    database_url: AgB9vlht3KwbEMF8vzDvW7EoJ/tYZwBkDdmsu2EFfZaLcaZY7xkwf1161vJ++1bzQGCTVbo/TMXiWLMw4gXS0FZQlBfFoHD1634uOKhsWk+HuTiq1WAoJDJfyw1drOLsVq2Qito5NxYIVncSHUNRwvNmOt7wKgkRMB3/2xa3iAc+RTQz/UqR3PWb+PH8Z3DdzbONzSrhvgQmbuAyLi3LhhTgHQefI5L2PFZtbhuRtGW4BJZ+LDO3lWSOszMJ3dLLMqZe4IuRGiI2DPWre6cr+A52OTGslDKxK4/TVRBsxxriiYJ3vQFeBFDlsRghSZ4feQNW3F6sbHlDaNZia7zZHH84esKqV9dBDfTvnPwxRns+fv1kZQLvEg93noF7TH3Bmae6V+bv0hBdjdP+Awcs4en0+MOR0farocBWHwxHkjqUPloNzNUE4hlxTrqbSa2wijo8rhARfbyXp14V8oDiA/aRp3pgW9YWy1Ju6yccPxp7MC+viPBCuBZ4QJN8HAmbGifjCqUJ8vXHOAODMFcXLVHMApMupYe/N+Xp7JhtQY3Y4cHEMKIu4RrpYnXBQ/htxrdc6faUsIgBDqI3h8L7QPd0rYtIWBFcmmO85yJSJIbX4MnWuUA0SdhoDpuCltVgcb5jcxIfDjN/DI9kvTxIA9k2WUV6PZQ4uuhQPvConkpPTGNUcoEJitLHZ16gqB+euWqEVo58gSeDUoLLaVFjKKfyoo3UIAeTbCNkQ6Ln1f4ISz1Bmqwfm4icJOgjcx6stzGeZ/9P40DeHPoEVsVkMyfBjuCZqiaHvBygMx5/oJK1/rWi
    password: AgCiEokeIdyg/d4jA8HFFkd/S4sJe7zTsKq5tfz0q9OZ/RS60nePY8KjfPgeQc58EuItlpRyW2Pycd03t4NZsi5OKeJMxIpiOn5OJgV7b8cQML7WmP8RjpmY3W+t4IacyYBRufgX6tt0kCJZg19g3VqW14TOkpsoj/2xfMMCWDS6Q3NemY70fgfgG5MIcp/Qe7CO1X4QNPzJ4fTnNAKn9XAz5QtfuEN996VNs/rFVt5ZAKXM/y9pyyJAHVzQyIQp769mcakGrwwGffbOD1HiitxKB+9jD7dBm4aFhN0zTMd3eD3Y0oEh7tBMTUga3WDubgWIReQ9eR4FTGXf5qXKiYj4SPqfR4Snsu2SBjRFZTlqsgjOHkPDyKQygIUfn5efhpR6yCh3JAelT4n6tlXVoxSHmi6lNJ9exHQJAjDz85w4R8cSDguZH6JqimKmL6zMjr4RS8G+HY6ZG3kVXraWUJ32llB+WnSrsv/upgCBj7JLUQxwOH8KcVQ+11o7rwUuQRVfYqkX9WthO8zvj7Wp5DG3sM6u6u3u3Ux9wuatQ2J28XAqxGB883obgR0Q3rc4nppCD7jhuOCtu68uNLAsqiypTEo/QgD2yv9WFT4X+wEYT4H4UYVwdi3rWNi/yRbiRBu1mZnboWBdkaEMRRqmmWgRaRWMUyoGoc7mtnZuNOToD9QzhISJebO7dy6Vz8v1lIrbCQy9zpLFFQ2yQjLYI04=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom
    type: Opaque

