apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ride-db-secrets
  namespace: vroom-dev
spec:
  encryptedData:
    database_url: AgBE0S+1lCo4Cy9NPVXKYL/20xwQiRxRPo2qSvpQmeC1okiSdRzyNfMxhmpFaoI5KESE2u7/UP3S4KjK95NFAG4XFIbWxadcDnXbMLgQdjFTczUJBpHAYSMdUsxo/I6qWnAv+jgKlNlJM1h3mJIqXTEodNwKsWWKP2irraR//XLsyzY4d+FwTC0ksbV8TgVD+y/1WUMzCLgUFl9bpe1KHMzb7UWlktQoA/q7el+Z9YTjKHWraVzVfrPhQva4E49ljMmHqvhV6WUeRPuum9Fxt2X5nXGq6TWPVIVjm2v/N6z0rjKN1f6ySBgbNObnldfv2VrnXN93O/CdL7Xo/UNT/XueOQmTjIgHU6Wn5ZsegB9fZ4lutBvdcNKQN3zLsZVf1+WlWV6M4mKhq+WWf2EGkgQDzjSL2z8p/is3CAGCyPwUO8xQuFCF+JDqWR+ng97uCBnGfpQWGOIJWOSRoE77ZDK/drb9t7bwDvOG/gK4lyznYQbHtnGpQ3a+ey/d9ZMJNUy73o5tqZownhcuLZi6mRB0LtfbJNCYXTCTOM6PygbDWSkNXO6RbWtZJ9ll637tvKdA0UQtYn6mEX9oL1D57kiyX6/JqeIg8L/TJgSiFQju3p6TnIrUjH9C8tjAp/0/xgN1RfhV5CfyjX4e/YLXGUDMdYhJodMMw6ZxuZ6lOEynd2aReivz/7Jr7Kj4gTJZsFqSqLTSOah+hmIyGwZ7GNEWVOS1w4aLSUaGHOsvf6U2AGPsERQJqFEQUJkSn6HlC4K68IMmaVXVaZgu2ZGiXA7zjGmdLH+nV5FeUEy+DV+rLKlH
    password: AgDK4UhTuZpdUtSUZV8up9UKW+Io1Um6ZG0X0OGfmr1CXoH/oGvEjldiwH08ILWGQeYC0RHypAg3S5YHeRaTJjAQB9f4DD5yQrStbEa0t0pff0QFYFVlPXYWWPhIRbWb5YG6muOkTLd9iPOk+3bJVhH8C165j/OV8D22JEG/OMFsu065GcqEKmCwA5Ox9UOYRyjuT0DHkIzE0PVcjb0m0sOnX1CSsiQsr2TJu6b0mRR857pTlyvqeKr3H+UsftcxkilJZ3Y3L6/SubyQxCgGaE1GbS0yrcErQy0bd0IaLrdOI4BhA22l9j3iGdNBTJaFg+F2cp2Bqq2rKB4P4eg11UymM5WBoynSjGicSTa0EwnRoixuL0FZlQ9qiH4UF+KFg76XnPGoB+Pj8sqd1NpGBc7mMU/iWhfzbqONhfDiqNY0aKAu3LQ9VRencZVvz7zqGeJeCvuthiD5lwMoyjA+P9Ji9Gc01aZ+3qLQHSBLDjikQoRMUtch/jx+JDTJ4rycfqYkZWBwsQtTxv9p13mCBsz2kvUsobZKT+i5Gm9mdWiA9+I1U3wpSrR4AW63tHN3JYmxhYs+yW38JMtd9s3tHA+F3fLfVgxPvEbhjj6J9+46kKyD3lT9P9LIC/U51+I6CqhFvdLagaidkizt9JI4Ab8waKocVZZNX1w/7I+JPT9U3/cRPTOpxBPyqY/16WfIxiNW2CjqGzLhkyBwUxt7ucY=
  template:
    metadata:
      creationTimestamp: null
      name: ride-db-secrets
      namespace: vroom-dev
    type: Opaque

