apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vroom-dev
resources:
- ../../base
- ingress.yaml
images:
- name: vroom-mvp/frontend
  newName: ama2352/vroom-mvp-frontend
  newTag: 7d41a3ea
