---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-pull-secret
  namespace: vroom-prod
spec:
  encryptedData:
    .dockerconfigjson: AgA3RIaMylCagoq/XWnoUigtMRO9EohHE8TCaSnpo9fO6PZb+cH1C7lZY+ibnQxq0YOpkFIbamFy46aGv8TiXanytYNSEeRhx6nrH1QVFQMQJwPZh/jJ8XEauAk64JbkaVDtBbcvL6F82vNoPTP24suPuYkgi3FgIN1CulD+TwdGlexlgXv0dRgk9n9Prm3vzSfxL12l6F56r32BOtTNQ9iX0mkbRCe4EmtZKn+O03V7MlSkmH1UCm0p6Co7quLRVinkQwJL5yOCJbrAhrRWxsG7P3knjDhpU6jQXObYNZN20EUm92aCY0p6InLzCOaavn0M45/zCOC6pUJiAiN9JjklkDZpCoJLP+N7sql1MEZrbNxF2RMxdK3aFtnOwE71J54GFhq4so2b83xKD6KyQC8Q1Dfn8Gl9V36XkvTsCKjMHLuhJ8F2Pq54qWJhRYWwJ6j5jpEg4KSXzYUXjtqjCozAnnuLvOi7ctW+vp4RPoOGlV8Tcmi1qYnlAUGA4vFGousZTnl9uGNprdNrspHu9t/Y91CM2xzygvl/yVUebW2O7fkVCFYYAnZKXT6oOWUzTQph1GEbEqdsoWQDcHNys9lSSdnL7OIgdeLo8o2qYTQfrt+tT+dBYAG4fbJvH5qncn0CXewSfhF8zEfl/FWuQ6ujJ1v+JDbPT2LOJ44/iFvNG4AVemVjMgxfgzA3vxWKdAv7IV2g/SDTBdcH3yuK7Z79BauzrJKh5CqQH7knHFbrR6nG6ENMvGwnr9lpvz6i3eCwOf3h9ADzJcii3wf21jeG7oCzZc8DMYKTyHlvzLstra7rsFgAGCf5qOu3n7I7V2aoo5ol6ptUB/d4seFIMFxGTmzM10duaz1xKL5d7SmJDj/7yBc5P6JJ4k3VWlWG7BmCojkkQqix8VMFfZtlaZ5v4MLSkGPg58lNEn7z3eMJyNWKXkc603cEKzC0cIuRyk7HPOpqMhKTo3+RkJ9GwrqPzZvjwlfwK8dnSJNxKpDvUwiaLU8=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-pull-secret
      namespace: vroom-prod
    type: kubernetes.io/dockerconfigjson
