---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dockerhub-pull-secret
  namespace: vroom-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBLJNnfkHFXFba/N4aiVazC7BAIyvReTdff0BsLgW26phzXL3GhTq8GQjyCfCY/Yh/KTwslXR83Vyu7VQIvMup4sEqEt6T88Lzc9QJhUCW0I5i/GBAiOX56zIgUps5JEtyT9MiJHWj48v8+sY9k7idVkmrJrmKG5GTAaJwaOji0IPSQ5nrP6h/cADFQwrPDkiWVGaOfWwmWkuONi4G2809GsYGaxMY9Mw7jG7diTjlJZ4ptB4zeiWuHDcm/69JcpiV7sWl8wGGQQMZiCxM9jldICdS+51JKCCMLxbwH6YqY/SQuR8Sfz5h+uGnWz/n4HPvhSL/9h9Y2ombfIYrnt4Miy+btq37BzEuWziR3xGrv5C+yxt3u2xIFrgp5WAGrHsUbLJXWR6aEvjWeJIlfy9WKLnSykZKnc0/6C5YQofqrKt49Z4kT1dSCuZo9pXyQpji7iXd679IUhL/8Lw/gmIttQKOCr7mLmpCjHSgP15T0Zeg9Z4NRITsgjjNurJzolhr4v5/5fWLXX7opRqiNo/oFvjTgvP6d7HvYxOo3P6/voXiuFQp9mPjw2xQsQqr1HvlQb0oMKIOpja+HoI5aNFxBws5vsS+8FHs70cOV0qAFbXWr3oHFLEyE8hViAwTHCvsGXNWHGB+9fcyMO+5ZWpPaR3qNtnhI7SFgOFtBC21xxbY/QlKbUJ5nogiLEhAn+iEkAOWLn5zi3kmPaYkUUlO3sUvOusyEQ4dAHIOUYZmS8MjIkRlu29sJaZOM30DWD1q2KI+//u4sN/xTO3WwaO64uya4hR265Y5vwlF7Lv55lr7H0Rr7wbZpRvKRsx4PBDkKHlctnJf7KfSuf0aPOgaXdQ8ay6rht402Q9wKhLrsKul0QL2u4hQ6QXz4OU0KWSNq5jy2Guxb7eKN2qdN3T4audvQBsAhlsA=
  template:
    metadata:
      creationTimestamp: null
      name: dockerhub-pull-secret
      namespace: vroom-prod
    type: kubernetes.io/dockerconfigjson
