apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project.yaml
  - warehouse.yaml
  - platform-warehouse.yaml
  - analysis/prometheus-checks.yaml  # must be before stages so Kargo can validate references
  - stages/dev.yaml
  - stages/prod.yaml
  - stages/platform.yaml
  - project-config.yaml
