apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- secrets/user-db-secrets.yaml
namespace: vroom-dev
patches:
- path: patches/resource_limits.yaml
labels:
- pairs:
    env: dev
images:
- name: vroom-mvp/user-service
  newName: ama2352/vroom-mvp-user-service
  digest: sha256:23179bd4a188bc322282e62e7fef65d2e69092547083a6a6085a584b4e52c833
