apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- ingress.yaml
- secrets/user-db-secrets.yaml

namespace: vroom-dev

patches:
- path: patches/resource_limits.yaml


labels:
- pairs:
    env: dev
images:
- name: vroom-mvp/user-service
  newName: ama2352/vroom-mvp-user-service
  newTag: 456d3e85
