apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
- secrets/user-db-secrets.yaml
namespace: vroom-dev
patches:
- path: patches/resource_limits.yaml
labels:
- pairs:
    env: dev
images:
- name: vroom-mvp/user-service
  newName: ama2352/vroom-mvp-user-service
  digest: sha256:b81237226e7c1dbcd13c57ef74c4b4346f2eaacd601bd54b32db0daef074edc0
