apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../apps/user/overlays/dev
  - ../../apps/ride/overlays/dev
  - ../../apps/dispatch/overlays/dev
  - ../../apps/notification/overlays/dev
  - ../../infrastructure/namespace.yaml
  - ../../infrastructure/postgres
  - ../../infrastructure/redis
  - ../../infrastructure/observability
